### ISSUE TITLE
exon numbers does not match after conversion of gff to gtf with agat_convert_sp_gff2gtf.pl

### ISSUE THREAD

**Issue by ahmadait** [NBISweden/AGAT#101]
Hello,

I used agat_convert_sp_gff2gtf.pl tool to convert gff to gtf format. After having a closer look at the output file, I found out that the number of exons reported in the output file is way higher than what is present in the original gff file. For example in the original gff file, the number of exons counted from the 3rd column of the gff file  = 177880 while after conversion the 3rd column of gtf version shows that the number of exons = 275560 which is almost double than gff file.  I have provided a link to my gff file [https://drive.google.com/file/d/1COMfjoGZ8XOWv_l3hXnsKDKzHbw3ocCS/view?usp=sharing]. 
I was wondering why it might be the case? Theoretically, we would expect to have the same number of exons after conversion that is present in the original file
I would really appreciate your feedback

Thank you

Best Regards
Muhammad Ahmad

**Comment by Juke34** [comment]
AGAT does not just convert the GFF file, it first standardises it. To have more information about the standardisation process you can run `agat_convert_sp_gxf2gxf.pl` it provides a log resuming what has been done.

**Comment by Juke34** [comment]
I checked your file, in your case it is because the factorized exon features are deflated, e.g:
```
contig_167	maker	exon	551127	551241	.	-	.	ID=Leryth_003213-t2:exon:2718;Parent=Leryth_003213-t2,Leryth_003213-t1
```
becomes
```
contig_167	maker	exon	551127	551241	.	-	.	ID=Leryth_003213-t2:exon:2718;Parent=Leryth_003213-t1
contig_167	maker	exon	551127	551241	.	-	.	ID=Leryth_003213-t2:exon:2718-nbisNew;Parent=Leryth_003213-t2
```
Which is part of the standardisation, the file is bigger but not all tool succeed to process properly factorized features

**Comment by ahmadait** [comment]
Thank you very much for your quick response. How can I avoid it to have the same information that is present in the original file. I am using gtf file for differential expression purposes. I am afraid it can cause a problem in the downstream analysis.

**Comment by Juke34** [comment]
I didn't implemented yet a way to inflate (factorize) redundant features.
But it should not cause any problem in downstream analysis, on the contrary.
The information is the same, it is just displayed in a different way that should be less prone to error in other tools.

**Comment by ahmadait** [comment]
Ok, Thank you!
