### ISSUE TITLE
Error converting RepeatMasker output file /  New feature request

### ISSUE THREAD

**Issue by githubgig** [NBISweden/AGAT#102]
Hi Jacques,

It looks like AGAT can be extremely useful, but I've run into a converting issue with a RepeatMasker output file (see error below). I had a look at the .json files, but it looks like AGAT currently cannot parse repeat elements. Is there any way I can add repeat element features to the .json file?

-------------------------------- parse features --------------------------------
=> GFF version parser used: 3
gff3 reader warning: primary_tag error @ dispersed_repeat still not taken in account! Please modify the json files to define the feature in one of the levels.
gff3 reader warning: primary_tag error @ dispersed_repeat still not taken in account! Please modify the json files to define the feature in one of the levels.

Thanks.

**Comment by Juke34** [comment]
Similarly than explained here https://github.com/NBISweden/AGAT#agat-throws-features-out-because-child-features-are-not-provided, expose the json feature files in the current folder. Add the new feature in level1 if it does not have parent feature or in level2 if it has parent feature.  I should write a dedicated paragraph in the troubleshooting section to explain this in detail.
In the future in the feature is relevant I can add it permanently.

**Comment by githubgig** [comment]
Hi Jacques,

So there are two locations for json features files:
./lib/site_perl/5.26.2/auto/share/dist/AGAT/
./pkgs/agat-0.5.1-pl526r35_0/lib/site_perl/5.26.2/auto/share/dist/AGAT/

Which one location should I modify the file?

Thanks.

**Comment by Juke34** [comment]
Tab or space does not matter.
I don't know which of this location is the one, maybe both, but this is only if you want to do a permanent modification.
The easiest is to run:
`agat_convert_sp_gxf2gxf.pl --expose`  that will copy the json files localy. Then you can modify them. Then if you run AGAT from the same folder, they will be taken into consideration. Indeed AGAT look first in the local directory if the json files are present and use them  by default.

**Comment by githubgig** [comment]
I updated the feature in the first location (./lib/site_perl/5.26.2/auto/share/dist/AGAT/) and the other location got updated automatically. I also ran agat_convert_sp_gxf2gxf.pl successfully without any errors. But when I used the agat output in maker, I'm getting an error related to the file. Any chance you can take a look at the gff output?

Thanks

**Comment by Juke34** [comment]
Maker expects specific repeat input file. Are you sure you follow the rules?

**Comment by githubgig** [comment]
Hi Jacques,

Do you mean column 3 of my gff needs to have "match"? My AGAT output file looks like this and it is currently "dispersed_repeat" which was assigned by RepeatMasker.
`
##gff-version 3
##sequence-region Contig10007|quiver 1 5918								
Contig3956|quiver	RepeatMasker	dispersed_repeat	4161	4198	289	-	.	ID=1039;Parent=1039;Target=rnd-1_family-83 1 38
Contig3956|quiver	RepeatMasker	dispersed_repeat	4450	4520	321	-	.	ID=1041;Parent=1041;Target=rnd-1_family-103 1 64
`

**Comment by Juke34** [comment]
yes, with a `sed` command you can fix it easily.
You can find more information within the MAKER documentation or looking at the MAKER mailing list

**Comment by githubgig** [comment]
Thanks. I've made the change and trying again now.

**Comment by githubgig** [comment]
Hi Jacques, 

I used feature type "match" and reformatted my gff file using AGAT. I didn't get any errors during reformatting, but the file is still not working. I have also tried all possible solutions from maker online forums and maker developers are not responding either. Any chance you can take a look at my gff?

**Comment by Juke34** [comment]
send me your file or a link I will try to have a look tonight

**Comment by Juke34** [comment]
It needs to be a two level feature match/match_part. You only have match feature. You must duplicate each line and replace match by match_part in these new duplicated lines.

**Comment by githubgig** [comment]
Ok, I have rectified the file and trying again.

**Comment by githubgig** [comment]
Hi Jacques, 

I duplicated lines and had match and match_part on alternate lines. Then I tried to reformat the file in AGAT but the screen gave: WARNING level2: No Parent attribute found @ for the feature

So I tried the file directly in maker (without running in AGAT), and I get the message below that the file is not formatted correctly:

ERROR: Non-unique top level ID for 2105028
While this is technically legal in GFF3, it usually
indicates a poorly fomatted GFF3 file (perhaps you
tried to merge two GFF3 files without accounting for
unique IDs).  MAKER will not handle these correctly.

--> rank=4, hostname=m30G
ERROR: Failed while doing repeat masking
ERROR: Chunk failed at level:0, tier_type:1

I have sent the .gff file to you again, can you please take a look.

Thanks.

**Comment by Juke34** [comment]
No need to pass the file in AGAT. But when creating a record with match/matc_part relationship you must add parent/Id attribute accordingly. So you must get
```
Contig3956|quiver RepeatMasker match 4161 4198 289 - . ID=1039;;Target=rnd-1_family-83 1 38
Contig3956|quiver RepeatMasker match_part 4161 4198 289 - . ID=part_1039;Parent=1039;Target=rnd-1_family-83 1 38
Contig3956|quiver RepeatMasker match 4450 4520 321 - . ID=1041;Target=rnd-1_family-103 1 64
Contig3956|quiver RepeatMasker match_part 4450 4520 321 - . ID=part_1041;Parent=1041;Target=rnd-1_family-103 1 64
```
If you follow rigorously this format it should be fine.

**Comment by githubgig** [comment]
I formatted as you described and reran. But it seems there is still some problem in the file because maker is giving me this error below. I have sent you the file again.

Died at /home/user/bin/maker/bin/../lib/Bio/Search/Hit/PhatHit/Base.pm line 188.
--> rank=1, hostname=m30G
ERROR: Failed while processing all repeats
ERROR: Chunk failed at level:3, tier_type:1

**Comment by Juke34** [comment]
This is now a MAKER problem. You may try to analyse shorter chunks (see option in the parameter file). See other comment about this problem on google it might help.
In the past I had a problem with the PhatHit_utils.pm file and it was actually related to perl version (Perl 5.10.1 was failing while  5.16.3 was working fine). So be sure to use the last MAKER version, try a perl version that is known to work and try with shorter chunks. Maybe try on bigger machine with more RAM too.
