### ISSUE TITLE
perl Moose not listed among dependencies

### ISSUE THREAD

**Issue by nomenia** [NBISweden/AGAT#104]
Dear authors of AGAT,

When installing AGAT from its GIT repository I ran into some failed tests that could be fixed by installing perl Moose package. I wonder if it should be listed among dependencies to prevent this from happening.
---
lexa@matej-HP-ProBook:~/git/AGAT$ make test
Skip blib/lib/auto/share/dist/AGAT/features_level1.json (unchanged)
Skip blib/lib/auto/share/dist/AGAT/features_level2.json (unchanged)
Skip blib/lib/auto/share/dist/AGAT/features_spread.json (unchanged)
Skip blib/lib/auto/share/dist/AGAT/features_level3.json (unchanged)
Skip blib/lib/auto/share/dist/AGAT/so.obo (unchanged)
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/gff_syntax.t ....... ok     
t/gff_version.t ...... ok   
t/scripts_compile.t .. 52/65 Can't locate Moose.pm in @INC (you may need to install the Moose module) (@INC contains: /home/lexa/git/AGAT/blib/lib /home/lexa/git/AGAT/blib/arch /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at bin/agat_sp_prokka_fix_fragmented_gene_annotations.pl line 21.
BEGIN failed--compilation aborted at bin/agat_sp_prokka_fix_fragmented_gene_annotations.pl line 21.

#   Failed test 'test agat_sp_prokka_fix_fragmented_gene_annotations.pl'
#   at t/scripts_compile.t line 39.
t/scripts_compile.t .. 65/65 # Looks like you failed 1 test of 65.
t/scripts_compile.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/65 subtests 
t/scripts_output.t ... 35/47 Can't locate Moose.pm in @INC (you may need to install the Moose module) (@INC contains: /home/lexa/git/AGAT/blib/lib /home/lexa/git/AGAT/blib/arch /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at bin/agat_sp_prokka_fix_fragmented_gene_annotations.pl line 21.
BEGIN failed--compilation aborted at bin/agat_sp_prokka_fix_fragmented_gene_annotations.pl line 21.
diff: tmp.gff/prokka_cav_10DC88.gff: No such file or directory

#   Failed test 'output bin/agat_sp_prokka_fix_fragmented_gene_annotations.pl'
#   at t/scripts_output.t line 399.
diff: tmp.gff/prokka_cav_10DC88.fa: No such file or directory

#   Failed test 'output bin/agat_sp_prokka_fix_fragmented_gene_annotations.pl'
#   at t/scripts_output.t line 400.
t/scripts_output.t ... 47/47 # Looks like you failed 2 tests of 47.
t/scripts_output.t ... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/47 subtests 

Test Summary Report
-------------------
t/scripts_compile.t (Wstat: 256 Tests: 65 Failed: 1)
  Failed test:  54
  Non-zero exit status: 1
t/scripts_output.t (Wstat: 512 Tests: 47 Failed: 2)
  Failed tests:  36-37
  Non-zero exit status: 2
Files=4, Tests=153, 154 wallclock secs ( 0.06 usr  0.02 sys + 147.77 cusr  5.65 csys = 153.50 CPU)
Result: FAIL
Failed 2/4 test programs. 3/153 subtests failed.
make: *** [Makefile:1568: test_dynamic] Error 2

**Comment by Juke34** [comment]
Thank you for the feedback, I will update the readme.
