### ISSUE TITLE
product not catched when GN missing in the header

### ISSUE THREAD

**Issue by Juke34** [NBISweden/AGAT#108]
Hi!

I noticed something else in that script (that is more a real issue than improvement).

It concerns blast.

case 1 (everything is working fine): 
In the swissprot database I have this protein : 
>sp|P13607|ATNA_DROME Sodium/potassium-transporting ATPase subunit alpha OS=Drosophila melanogaster OX=7227 **GN=Atpalpha** PE=1 SV=3

after blast it matches one of my mRNA:
maker-Bi03_p1mp_000155F-exonerate_protein2genome-gene-6.7-mRNA-3 sp|P13607|ATNA_DROME 69.59 1003 299 2 5 1007 45 1041 0.0 1454

and so I have my annotation in the gff :
Bi03_p1mp_000155F	maker	mRNA	737106	740129	66.73788	+	.	ID=BALIMM00000061851;Parent=BALIMG00000029106;Dbxref=Pfam:PF00689,Pfam:PF13246,Pfam:PF00690,Pfam:PF00122,SUPERFAMILY:SSF81660,SUPERFAMILY:SSF81653,SUPERFAMILY:SSF56784,SUPERFAMILY:SSF81665,Gene3D:G3DSA:1.20.1110.10,Gene3D:G3DSA:2.70.150.10,Gene3D:G3DSA:4.10.6.10,Gene3D:G3DSA:3.40.1110.10,SMART:SM00831,MobiDBLite:mobidb-lite,SFLD:SFLDS00003,Reactome:R-HSA-936837,PANTHER:PTHR24093:SF322,PANTHER:PTHR24093,PRINTS:PR00121,PRINTS:PR00119,InterPro:IPR006068,InterPro:IPR023298,InterPro:IPR023299,InterPro:IPR005775,InterPro:IPR018303,InterPro:IPR008250,InterPro:IPR023214,InterPro:IPR004014,InterPro:IPR001757,ProSitePatterns:PS00154,TIGRFAM:TIGR01106,TIGRFAM:TIGR01494;**Name=atpalpha_iso2**;Ontology_term=GO:0000166,GO:0005391,GO:0005524,GO:0006813,GO:0006814,GO:0016021,GO:0046872;_AED=0.01;_QI=0|-1|0|1|-1|0|1|0|1007;_eAED=0.01;makerName=maker-Bi03_p1mp_000155F-exonerate_protein2genome-gene-6.7-mRNA-3;**product=Sodium/potassium-transporting ATPase subunit alpha;uniprot_id=P13607**

case 2 (problem) : 
In the swissprot database I have this protein : 
>sp|P28774|AT1B_ARTSF Sodium/potassium-transporting ATPase subunit alpha-B OS=Artemia franciscana OX=6661 PE=2 SV=1

after blast it matches one of my mRNA:
maker-Bi03_p1mp_000636F-est_gff_StringTie-gene-1.3-mRNA-1 sp|P28774|AT1B_ARTSF 69.83 1001 295 3 26 1025 10 1004 0.0 1457

and in the gff : 
Bi03_p1mp_000636F	maker	mRNA	93264	98077	1000	-	.	ID=BALIMM00000067022;Parent=BALIMG00000031555;Dbxref=Pfam:PF00122,Pfam:PF00690,Pfam:PF00702,Pfam:PF13246,Pfam:PF00689,SUPERFAMILY:SSF81665,SUPERFAMILY:SSF56784,SUPERFAMILY:SSF81653,SUPERFAMILY:SSF81660,Gene3D:G3DSA:1.20.1110.10,Gene3D:G3DSA:2.70.150.10,Gene3D:G3DSA:4.10.6.10,Gene3D:G3DSA:3.40.1110.10,SMART:SM00831,MobiDBLite:mobidb-lite,SFLD:SFLDS00003,Reactome:R-HSA-936837,PANTHER:PTHR24093,PANTHER:PTHR24093:SF322,PRINTS:PR00121,PRINTS:PR00119,InterPro:IPR001757,InterPro:IPR008250,InterPro:IPR023298,InterPro:IPR023214,InterPro:IPR004014,InterPro:IPR006068,InterPro:IPR018303,InterPro:IPR005775,InterPro:IPR023299,ProSitePatterns:PS00154,TIGRFAM:TIGR01494,TIGRFAM:TIGR01106;Ontology_term=GO:0016021,GO:0000166,GO:0046872,GO:0005391,GO:0005524,GO:0006813,GO:0006814;_AED=0.00;_QI=214|1|1|1|0|0|2|465|1025;_eAED=0.00;makerName=maker-Bi03_p1mp_000636F-est_gff_StringTie-gene-1.3-mRNA-1;**product=hypothetical protein**

This not an hypothetical protein it is a Sodium/potassium-transporting ATPase subunit alpha-B, the problem is in the swissprot fasta file there is no Gene Name (GN=).

There are two possibilities;

1. We change the fasta file of swissprot and force if there is no GN= to add something like for instance : 

>sp|P28774|**AT1B_ARTSF** Sodium/potassium-transporting ATPase subunit alpha-B OS=Artemia franciscana OX=6661 **GN=AT1B_ARTSF** PE=2 SV=1

2. We change the script, something like if there is a blast but no GN then in our case GN=AT1B_ARTSF and then the rest should follow in the gff (like Name=, product= and uniprot_id=) (or maybe not the name but it is not an hypothetical protein!)

I would prefer to change the script, what do you think? @nylander? 

also it is kind of high in my priority now as I have functional parts to run :)

_Originally posted by @LucileSol in https://github.com/NBISweden/AGAT/issues/103#issuecomment-808374670_

**Comment by Juke34** [comment]
Hi @LucileSol, good catch.
It should be fixed in the origin functional_gn branch. Could you give a try before merging?
Here an explanation how to try out this branch: https://github.com/NBISweden/AGAT#use-a-version-of-agat-from-a-specific-branch

**Comment by LucileSol** [comment]
Hi @Juke34, @nylander 
it is working! thanks!

Is it possible to add the name after the | as Name, for example in this case AT1B_ARTSF as the Name in the gff? (sp|P28774|**AT1B_ARTSF** )

It would look like in the gff as following :  

Bi03_p1mp_000636F maker mRNA 93264 98077 1000 - . **ID=BALIMM00000067022;Parent=BALIMG00000031555;Dbxref=Pfam:PF00122,Pfam:PF00690,Pfam:PF00702,Pfam:PF13246,Pfam:PF00689,SUPERFAMILY:SSF81665,SUPERFAMILY:SSF56784,SUPERFAMILY:SSF81653,SUPERFAMILY:SSF81660,Gene3D:G3DSA:1.20.1110.10,Gene3D:G3DSA:2.70.150.10,Gene3D:G3DSA:4.10.6.10,Gene3D:G3DSA:3.40.1110.10,SMART:SM00831,MobiDBLite:mobidb-lite,SFLD:SFLDS00003,Reactome:R-HSA-936837,PANTHER:PTHR24093,PANTHER:PTHR24093:SF322,PRINTS:PR00121,PRINTS:PR00119,InterPro:IPR001757,InterPro:IPR008250,InterPro:IPR023298,InterPro:IPR023214,InterPro:IPR004014,InterPro:IPR006068,InterPro:IPR018303,InterPro:IPR005775,InterPro:IPR023299,ProSitePatterns:PS00154,TIGRFAM:TIGR01494,TIGRFAM:TIGR01106;**Name=AT1B_ARTSF;**Ontology_term=GO:0016021,GO:0000166,GO:0046872,GO:0005391,GO:0005524,GO:0006813,GO:0006814;_AED=0.00;_QI=214|1|1|1|0|0|2|465|1025;_eAED=0.00;makerName=maker-Bi03_p1mp_000636F-est_gff_StringTie-gene-1.3-mRNA-1;**product=Sodium/potassium-transporting ATPase subunit alpha-B; uniprot_id=P28774**

I had a quick look and there is around 4% of GN missing in uniprot. I have not looked if some species/family have more or less of GN missing.

Thank you!

**Comment by Juke34** [comment]
We can but should we?

It sounds a bit dangerous to do so (at least as default behavior) because it mixes different concepts:  
 see https://www.uniprot.org/help/fasta-headers
```
# UniProtKB Fasta header
>db|UniqueIdentifier|EntryName ProteinName OS=OrganismName OX=OrganismIdentifier [GN=GeneName ]PE=ProteinExistence SV=SequenceVersion
```
[EntryName ](https://www.uniprot.org/help/entry%5Fname) and [GeneName](https://www.uniprot.org/help/gene%5Fname) does not mean the same thing.

Is it really a problem to not have gene name? If you use EntryName as gene name you will have to inform the customer and probably add an extra tag to be able to disentangle them from real gene_names.

**Comment by LucileSol** [comment]
Hi @Juke34 and @nylander! 

What do you think of my suggestion and who should do the work? maybe we can have it as an option?

Thank you!

**Comment by Juke34** [comment]
I'm not sure it is relevant. Furthermore, using an attribute (Name) that has a specific meaning to store value which do not represent what is supposed to be stored is not a good thing to do.
If the goal is to know how many of the genes are missing the GN from the DB, we can add the information at the end of the script (using a counter). If the goal is to be able to catch them from the gff we can add an extra attribute like `gn_missing=yes` too.

**Comment by LucileSol** [comment]
Hi @Juke34,
I don't know why I do not receive emails for this issue so sorry for the delay.
I think we will think more about the naming, in the meanwhile I agree with both your ideas.
Can you add a counter in the script and add ```gn_missing=yes``` in the gff ?
Thank you!

**Comment by nylander** [comment]
Dear All!
I'm looking in to this issue at the moment and hope to be able to add the functionality described. However, as usual, I would be helped by an example data set and the commands used to generate the observed behavior. @LucileSol , would it be possible to pint me at some data on the nac server?
/Johan

**Comment by nylander** [comment]
https://github.com/NBISweden/AGAT/pull/138 now made for addressing these issues.
