### ISSUE TITLE
agat_sq_repeats_analyzer

### ISSUE THREAD

**Issue by mylena-s** [NBISweden/AGAT#109]
Hi,
I am testing the function agat_sq_repeats_analyzer.pl and I am finding the following error:

command: agat_sq_repeats_analyzer.pl -i repeat_all.gff -g genome.fasta 
output:
Total sequence length                        275419902
Reading repeat_all.gff
382271 line to process...

------------- EXCEPTION: Bio::Root::BadParameter -------------
MSG: ' 6.0' is not a valid score
VALUE:  6.0
STACK: Error::throw
STACK: Bio::Root::Root::throw /home/mylena/miniconda3/envs/agat/lib/site_perl/5.26.2/Bio/Root/Root.pm:447
STACK: Bio::SeqFeature::Generic::score /home/mylena/miniconda3/envs/agat/lib/site_perl/5.26.2/Bio/SeqFeature/Generic.pm:470
STACK: Bio::Tools::GFF::_from_gff1_string /home/mylena/miniconda3/envs/agat/lib/site_perl/5.26.2/Bio/Tools/GFF.pm:475
STACK: Bio::Tools::GFF::from_gff_string /home/mylena/miniconda3/envs/agat/lib/site_perl/5.26.2/Bio/Tools/GFF.pm:435
STACK: Bio::Tools::GFF::next_feature /home/mylena/miniconda3/envs/agat/lib/site_perl/5.26.2/Bio/Tools/GFF.pm:395
STACK: /home/mylena/miniconda3/envs/agat/bin/agat_sq_repeats_analyzer.pl:93
--------------------------------------------------------------
the first lines of the reapeat_all.gff are the following:

##gff-version 2
##date 2019-01-18
##sequence-region genome.fasta
REGS001	RepeatMasker	similarity	3	13022	 6.0	+	.	Target "Motif:rnd-4_family-1725" 1 2707
REGS001	RepeatMasker	similarity	13022	13069	16.7	-	.	Target "Motif:rnd-6_family-644" 1230 1278
REGS001	RepeatMasker	similarity	13207	13237	 9.7	-	.	Target "Motif:rnd-6_family-2059" 1286 1316
REGS001	RepeatMasker	similarity	13479	13935	34.7	-	.	Target "Motif:rnd-6_family-2059" 610 1068

I tested the command in several gff files and always returns the same error. I do not know how these gff were obtained since I downloaded from published genomes. I guess they were obtained from the repeatmasker's output using a custom library. 

I hope you can help me,
Thanks!

**Comment by Juke34** [comment]
It sounds that BioPerl is expecting an integer from the score column of the gff/gtf file.
The value from the score column can be replaced with a period (AGAT do not use the value of this field). You can perform this replacement using an `awk` command
