### ISSUE TITLE
[BUG] Intron lengths are calculated incorrectly

### ISSUE THREAD

**Issue by ehscholl** [NBISweden/AGAT#110]
The statistics reported in agat_sp_statistics.pl gives one extra base per intron.

If you add "Total exon length" to "Total intron length per exon" exactly 1 base per intron longer than the reported "Total mrna length"

I actually went through and extracted every intron, calculated the lengths, and checked this. 
Also note that your "Shortest intron into exon part" is 1 base longer than the actual shortest intron.

**Comment by Juke34** [comment]
Good catch! thank you for reporting it.
