### ISSUE TITLE
Undefined subroutine &AGAT::OmniscientStat::rcc_plot_from_list

### ISSUE THREAD

**Issue by Hans-zhao831** [NBISweden/AGAT#111]
Hi, I installed AGAT by conda in a new env. But a report “Undefined subroutine &AGAT::OmniscientStat::rcc_plot_from_list called at /home/zhaohansheng/miniconda3/envs/agatenv/lib/site_perl/5.26.2/AGAT/OmniscientStat.pm line 169.” in the endwhen running  “agat_sp_statistics.pl -gff out.gff3 -g genome.fasta -d -v” , And without plots generating.

How can I test the software installation successfully and is this problem caused by the software installation?

**Comment by Juke34** [comment]
R command do not seems to work. I will have a look. You should not use the plot then (avoid -d or -p parameter)

**Comment by Hans-zhao831** [comment]
Indeed, I used conda to install twice, the first time is when it also showed that “R could not be found”, I uninstalled and reinstalled, I thought it was OK. Then I guess it's still a problem with R by conda.

**Comment by Juke34** [comment]
It is fixed in version 0.6.1. It it is not yet available in conda. You can install it following  this procedure:   
https://github.com/NBISweden/AGAT#use-a-version-of-agat-from-a-specific-branch

**Comment by Hans-zhao831** [comment]
Nice. It works.
