### ISSUE TITLE
Use agat_convert_sp_gxf2gxf.pl to fix gff

### ISSUE THREAD

**Issue by chnyuch** [NBISweden/AGAT#132]
Hi,

I'm using agat_convert_sp_gxf2gxf.pl to fix gff file made by braker.
I compare the output with the original gff file and found that it adds one more gene on the same scaffold and with the same start and end positions with different scores (the gene in original gff is with a score of 0.87 and it adds another gene with a score of 0.91 after fixing). My question is how to prevent it from creating this one more gene and why this happens?
Thank you very much.

The command I used:
`agat_convert_sp_gxf2gxf.pl -ml -g input.gff -o output.gff`

Before fixing
> scaffold20368   AUGUSTUS        gene    1       1168    0.87    +       .       g16980
> scaffold20368   AUGUSTUS        transcript      1       1168    0.87    +       .       g16980.t1
> scaffold20368   AUGUSTUS        internal        195     359     0.91    +       2       transcript_id "g16980.t1"; gene_id "g16980";
> scaffold20368   AUGUSTUS        internal        428     582     1       +       2       transcript_id "g16980.t1"; gene_id "g16980";
> scaffold20368   AUGUSTUS        internal        661     813     1       +       0       transcript_id "g16980.t1"; gene_id "g16980";
> scaffold20368   AUGUSTUS        intron  1       194     0.91    +       .       transcript_id "g16980.t1"; gene_id "g16980";
> scaffold20368   AUGUSTUS        intron  360     427     1       +       .       transcript_id "g16980.t1"; gene_id "g16980";
> scaffold20368   AUGUSTUS        intron  583     660     1       +       .       transcript_id "g16980.t1"; gene_id "g16980";
> scaffold20368   AUGUSTUS        intron  814     1168    0.96    +       .       transcript_id "g16980.t1"; gene_id "g16980";
> scaffold20368   AUGUSTUS        CDS     195     359     0.91    +       2       transcript_id "g16980.t1"; gene_id "g16980";
> scaffold20368   AUGUSTUS        CDS     428     582     1       +       2       transcript_id "g16980.t1"; gene_id "g16980";
> scaffold20368   AUGUSTUS        CDS     661     813     1       +       0       transcript_id "g16980.t1"; gene_id "g16980";

After fixing

> scaffold20368   AUGUSTUS        gene    1       1168    0.87    +       .       ID=gene-16980
> scaffold20368   AUGUSTUS        transcript      1       1168    0.87    +       .       ID=transcript-21368;Parent=gene-16980
> scaffold20368   AUGUSTUS        gene    1       1168    0.91    +       .       ID=nbis-gene-7758;gene_id=g16980;transcript_id=g16980.t1
> scaffold20368   AUGUSTUS        mRNA    1       1168    0.91    +       .       ID=g16980.t1;Parent=nbis-gene-7758;gene_id=g16980;transcript_id=g16980.t1
> scaffold20368   AUGUSTUS        exon    1       359     0.91    +       .       ID=nbis-exon-168726;Parent=g16980.t1;gene_id=g16980;transcript_id=g16980.t1
> scaffold20368   AUGUSTUS        exon    428     582     0.91    +       .       ID=nbis-exon-168727;Parent=g16980.t1;gene_id=g16980;transcript_id=g16980.t1
> scaffold20368   AUGUSTUS        exon    661     1168    0.91    +       .       ID=nbis-exon-168728;Parent=g16980.t1;gene_id=g16980;transcript_id=g16980.t1
> scaffold20368   AUGUSTUS        CDS     195     359     0.91    +       2       ID=cds-207243;Parent=g16980.t1;gene_id=g16980;transcript_id=g16980.t1
> scaffold20368   AUGUSTUS        CDS     428     582     1       +       2       ID=cds-207244;Parent=g16980.t1;gene_id=g16980;transcript_id=g16980.t1
> scaffold20368   AUGUSTUS        CDS     661     813     1       +       0       ID=cds-207245;Parent=g16980.t1;gene_id=g16980;transcript_id=g16980.t1
> scaffold20368   AUGUSTUS        five_prime_UTR  1       194     0.91    +       .       ID=nbis-five_prime_utr-1789;Parent=g16980.t1;gene_id=g16980;transcript_id=g16980.t1
> scaffold20368   AUGUSTUS        intron  1       194     0.91    +       .       ID=intron-189265;Parent=g16980.t1;gene_id=g16980;transcript_id=g16980.t1
> scaffold20368   AUGUSTUS        intron  360     427     1       +       .       ID=intron-189266;Parent=g16980.t1;gene_id=g16980;transcript_id=g16980.t1
> scaffold20368   AUGUSTUS        intron  583     660     1       +       .       ID=intron-189267;Parent=g16980.t1;gene_id=g16980;transcript_id=g16980.t1
> scaffold20368   AUGUSTUS        intron  814     1168    0.96    +       .       ID=intron-189268;Parent=g16980.t1;gene_id=g16980;transcript_id=g16980.t1
> scaffold20368   AUGUSTUS        three_prime_UTR 814     1168    0.91    +       .       ID=nbis-three_prime_utr-1959;Parent=g16980.t1;gene_id=g16980;transcript_id=g16980.t1

**Comment by Juke34** [comment]
Interesting. This is not suppose to happen. What version are you using?

**Comment by chnyuch** [comment]
Thank you for such a quick response.
This is really helpful.
