### ISSUE TITLE
agat_sp_statistics.pl stuck in v0.6.2

### ISSUE THREAD

**Issue by sanaek** [NBISweden/AGAT#133]
Hello

Im running agat_sp_statistics.pl with a gtf file and it gets stuck giving no output, it can read the file and performes parsing to 100% but doesn't end. Im using v0.6.2 installed via conda. 

Does anyone know if this is the same problem encountered with version 0.3.0 (mentioned in a closed issue)

Thank you

**Comment by Juke34** [comment]
On which step does it get stuck? If it is in the check for l3 linked to l2 Is has has been drastically improved in the master branch (to be release in future release. Follow this step to install version from the master branch: 
https://github.com/NBISweden/AGAT#use-a-version-of-agat-from-a-specific-branch

**Comment by sanaek** [comment]
Thank you, It works now
