### ISSUE TITLE
agat_sp_compare_two_annotations.pl does not output gff3 file

### ISSUE THREAD

**Issue by anshu406** [NBISweden/AGAT#134]
Hello, When I run agat_sp_compare_two_annotations.pl script like this :

agat_sp_compare_two_annotations.pl -gff1 infile1.gff3 -ggf2 infile2.gff3 [ -o outfile.gff3 ]

It does not write a gff3 output file but only outputs a table comparing two annotations. I have a original annotation file and then a manually curated gene annotation file. I want to replace old entries in my original file with curated gene models. Gene names in two files are not same but coordinates are overlapping.

Any help on matter will be appreciated. 

Thanks

Aditi

**Comment by Juke34** [comment]
What you need then is to complement not to compare (see according script). And use the curated annotation as reference.

**Comment by Juke34** [comment]
I hope you found your way.
Don't hesitate if you have any other question. Best regards
