### ISSUE TITLE
could you provide an example input tsv file for agat_sq_add_attributes_from_tsv?

### ISSUE THREAD

**Issue by pan-genome** [NBISweden/AGAT#139]
in the help file it only have example of one line:
    --- example ---

    * input.tsv: ID annot_type1 gene1 anot_x cds1 anot_y

but it is not clear what are types of value should be under each column. try and error for many times and still can not get it working. Please help. 
Could you provide an example tsv file with both header and values.

Thanks you!

**Comment by pan-genome** [comment]
here is what I tried:
cat foo.gff3
##gff-version 3
##sequence-region supercont1_1 1 3361134
supercont1_1    prediction      gene    723     1818    0       -       .       ID=gene_1;Name=jgi.p|Fusoxvas1|1;portal_id=Fusoxvas1;proteinId=1;transcriptId=1
supercont1_1    prediction      mRNA    723     1818    .       -       .       ID=mRNA_1;Name=jgi.p|Fusoxvas1|1;Parent=gene_1;proteinId=1;track=ExternalModels;transcriptId=1
supercont1_1    prediction      exon    723     1818    .       -       .       ID=exon_1_1;Parent=mRNA_1
supercont1_1    prediction      five_prime_UTR  1514    1818    .       -       .       ID=UTR5_1;Parent=mRNA_1
supercont1_1    prediction      CDS     1160    1513    .       -       0       ID=CDS_1;Parent=mRNA_1
supercont1_1    prediction      three_prime_UTR 723     1159    .       -       .       ID=UTR3_1;Parent=mRNA_1
supercont1_1    prediction      gene    2528    4046    0       +       .       ID=gene_2;Name=jgi.p|Fusoxvas1|2;portal_id=Fusoxvas1;proteinId=2;transcriptId=2
supercont1_1    prediction      mRNA    2528    4046    .       +       .       ID=mRNA_2;Name=jgi.p|Fusoxvas1|2;Parent=gene_2;proteinId=2;track=ExternalModels;transcriptId=2
supercont1_1    prediction      exon    2528    3058    .       +       .       ID=exon_2_1;Parent=mRNA_2
supercont1_1    prediction      five_prime_UTR  2528    2648    .       +       .       ID=UTR5_2;Parent=mRNA_2
supercont1_1    prediction      CDS     2649    3058    .       +       0       ID=CDS_2;Parent=mRNA_2
supercont1_1    prediction      exon    3108    4046    .       +       .       ID=exon_2_2;Parent=mRNA_2
supercont1_1    prediction      CDS     3108    3810    .       +       1       ID=CDS_2;Parent=mRNA_2
supercont1_1    prediction      three_prime_UTR 3811    4046    .       +       .       ID=UTR3_2;Parent=mRNA_2

cat boo.tsv
ID,annot_type1
gene_1,Sybindin-like protein
gene_2,Peptidase S9 prolyl oligopeptidase catalytic domain

agat_sq_add_attributes_from_tsv.pl --gff foo.gff3 --tsv boo.tsv
##gff-version 3
supercont1_1    prediction      gene    723     1818    0       -       .       ID=gene_1;Name=jgi.p|Fusoxvas1|1;portal_id=Fusoxvas1;proteinId=1;transcriptId=1
supercont1_1    prediction      mRNA    723     1818    .       -       .       ID=mRNA_1;Parent=gene_1;Name=jgi.p|Fusoxvas1|1;proteinId=1;track=ExternalModels;transcriptId=1
supercont1_1    prediction      exon    723     1818    .       -       .       ID=exon_1_1;Parent=mRNA_1
supercont1_1    prediction      five_prime_UTR  1514    1818    .       -       .       ID=UTR5_1;Parent=mRNA_1
supercont1_1    prediction      CDS     1160    1513    .       -       0       ID=CDS_1;Parent=mRNA_1
supercont1_1    prediction      three_prime_UTR 723     1159    .       -       .       ID=UTR3_1;Parent=mRNA_1
supercont1_1    prediction      gene    2528    4046    0       +       .       ID=gene_2;Name=jgi.p|Fusoxvas1|2;portal_id=Fusoxvas1;proteinId=2;transcriptId=2
supercont1_1    prediction      mRNA    2528    4046    .       +       .       ID=mRNA_2;Parent=gene_2;Name=jgi.p|Fusoxvas1|2;proteinId=2;track=ExternalModels;transcriptId=2
supercont1_1    prediction      exon    2528    3058    .       +       .       ID=exon_2_1;Parent=mRNA_2
supercont1_1    prediction      five_prime_UTR  2528    2648    .       +       .       ID=UTR5_2;Parent=mRNA_2
supercont1_1    prediction      CDS     2649    3058    .       +       0       ID=CDS_2;Parent=mRNA_2
supercont1_1    prediction      exon    3108    4046    .       +       .       ID=exon_2_2;Parent=mRNA_2
supercont1_1    prediction      CDS     3108    3810    .       +       1       ID=CDS_2;Parent=mRNA_2
supercont1_1    prediction      three_prime_UTR 3811    4046    .       +       .       ID=UTR3_2;Parent=mRNA_2
Job done in 0 seconds

you see no annotation attribute has been added.

**Comment by Juke34** [comment]
Hi!
Thank you for using AGAT.
I agree, the help might be improved. Moreover the rendering of the pod is not optimal, we do not see the column.

`tsv` files are tab separated, you are providing a coma separated file i.e csv. So you must inform AGAT that you are using csv by using the option --csv as follow:

`agat_sq_add_attributes_from_tsv.pl --gff foo.gff3 --tsv boo.tsv --csv`

**Comment by pan-genome** [comment]
Thank you for the help. I add the --csv flag, but still the information is not added:
$ agat_sq_add_attributes_from_tsv.pl --gff foo.gff3 --tsv boo.tsv --csv
##gff-version 3
supercont1_1    prediction      gene    723     1818    0       -       .       ID=gene_1;Name=jgi.p|Fusoxvas1|1;portal_id=Fusoxvas1;proteinId=1;transcriptId=1
supercont1_1    prediction      mRNA    723     1818    .       -       .       ID=mRNA_1;Parent=gene_1;Name=jgi.p|Fusoxvas1|1;proteinId=1;track=ExternalModels;transcriptId=1
supercont1_1    prediction      exon    723     1818    .       -       .       ID=exon_1_1;Parent=mRNA_1
supercont1_1    prediction      five_prime_UTR  1514    1818    .       -       .       ID=UTR5_1;Parent=mRNA_1
supercont1_1    prediction      CDS     1160    1513    .       -       0       ID=CDS_1;Parent=mRNA_1
supercont1_1    prediction      three_prime_UTR 723     1159    .       -       .       ID=UTR3_1;Parent=mRNA_1
supercont1_1    prediction      gene    2528    4046    0       +       .       ID=gene_2;Name=jgi.p|Fusoxvas1|2;portal_id=Fusoxvas1;proteinId=2;transcriptId=2
supercont1_1    prediction      mRNA    2528    4046    .       +       .       ID=mRNA_2;Parent=gene_2;Name=jgi.p|Fusoxvas1|2;proteinId=2;track=ExternalModels;transcriptId=2
supercont1_1    prediction      exon    2528    3058    .       +       .       ID=exon_2_1;Parent=mRNA_2
supercont1_1    prediction      five_prime_UTR  2528    2648    .       +       .       ID=UTR5_2;Parent=mRNA_2
supercont1_1    prediction      CDS     2649    3058    .       +       0       ID=CDS_2;Parent=mRNA_2
supercont1_1    prediction      exon    3108    4046    .       +       .       ID=exon_2_2;Parent=mRNA_2
supercont1_1    prediction      CDS     3108    3810    .       +       1       ID=CDS_2;Parent=mRNA_2
supercont1_1    prediction      three_prime_UTR 3811    4046    .       +       .       ID=UTR3_2;Parent=mRNA_2
Job done in 0 seconds

is anything I missed? Thank you!

**Comment by pan-genome** [comment]
Now I reformat the csv file to tsv file and it works. Thank you!

[ke]$ cat foo.gff3
##gff-version 3
##sequence-region supercont1_1 1 3361134
supercont1_1    prediction      gene    723     1818    0       -       .       ID=gene_1;Name=jgi.p|Fusoxvas1|1;portal_id=Fusoxvas1;proteinId=1;transcriptId=1
supercont1_1    prediction      mRNA    723     1818    .       -       .       ID=mRNA_1;Name=jgi.p|Fusoxvas1|1;Parent=gene_1;proteinId=1;track=ExternalModels;transcriptId=1
supercont1_1    prediction      exon    723     1818    .       -       .       ID=exon_1_1;Parent=mRNA_1
supercont1_1    prediction      five_prime_UTR  1514    1818    .       -       .       ID=UTR5_1;Parent=mRNA_1
supercont1_1    prediction      CDS     1160    1513    .       -       0       ID=CDS_1;Parent=mRNA_1
supercont1_1    prediction      three_prime_UTR 723     1159    .       -       .       ID=UTR3_1;Parent=mRNA_1
supercont1_1    prediction      gene    2528    4046    0       +       .       ID=gene_2;Name=jgi.p|Fusoxvas1|2;portal_id=Fusoxvas1;proteinId=2;transcriptId=2
supercont1_1    prediction      mRNA    2528    4046    .       +       .       ID=mRNA_2;Name=jgi.p|Fusoxvas1|2;Parent=gene_2;proteinId=2;track=ExternalModels;transcriptId=2
supercont1_1    prediction      exon    2528    3058    .       +       .       ID=exon_2_1;Parent=mRNA_2
supercont1_1    prediction      five_prime_UTR  2528    2648    .       +       .       ID=UTR5_2;Parent=mRNA_2
supercont1_1    prediction      CDS     2649    3058    .       +       0       ID=CDS_2;Parent=mRNA_2
supercont1_1    prediction      exon    3108    4046    .       +       .       ID=exon_2_2;Parent=mRNA_2
supercont1_1    prediction      CDS     3108    3810    .       +       1       ID=CDS_2;Parent=mRNA_2
supercont1_1    prediction      three_prime_UTR 3811    4046    .       +       .       ID=UTR3_2;Parent=mRNA_2

[ke]$ cat boo2.tsv
ID      description
gene_1  Sybindin-like protein
gene_2  Peptidase S9 prolyl oligopeptidase catalytic domain

[ke]$ agat_sq_add_attributes_from_tsv.pl --gff foo.gff3 --tsv boo2.tsv
1
ID
description
1
ID
description
##gff-version 3
supercont1_1    prediction      gene    723     1818    0       -       .       ID=gene_1;Name=jgi.p|Fusoxvas1|1;description=Sybindin-like protein;portal_id=Fusoxvas1;proteinId=1;transcriptId=1
supercont1_1    prediction      mRNA    723     1818    .       -       .       ID=mRNA_1;Parent=gene_1;Name=jgi.p|Fusoxvas1|1;proteinId=1;track=ExternalModels;transcriptId=1
supercont1_1    prediction      exon    723     1818    .       -       .       ID=exon_1_1;Parent=mRNA_1
supercont1_1    prediction      five_prime_UTR  1514    1818    .       -       .       ID=UTR5_1;Parent=mRNA_1
supercont1_1    prediction      CDS     1160    1513    .       -       0       ID=CDS_1;Parent=mRNA_1
supercont1_1    prediction      three_prime_UTR 723     1159    .       -       .       ID=UTR3_1;Parent=mRNA_1
supercont1_1    prediction      gene    2528    4046    0       +       .       ID=gene_2;Name=jgi.p|Fusoxvas1|2;description=Peptidase S9 prolyl oligopeptidase catalytic domain;portal_id=Fusoxvas1;proteinId=2;transcriptId=2
supercont1_1    prediction      mRNA    2528    4046    .       +       .       ID=mRNA_2;Parent=gene_2;Name=jgi.p|Fusoxvas1|2;proteinId=2;track=ExternalModels;transcriptId=2
supercont1_1    prediction      exon    2528    3058    .       +       .       ID=exon_2_1;Parent=mRNA_2
supercont1_1    prediction      five_prime_UTR  2528    2648    .       +       .       ID=UTR5_2;Parent=mRNA_2
supercont1_1    prediction      CDS     2649    3058    .       +       0       ID=CDS_2;Parent=mRNA_2
supercont1_1    prediction      exon    3108    4046    .       +       .       ID=exon_2_2;Parent=mRNA_2
supercont1_1    prediction      CDS     3108    3810    .       +       1       ID=CDS_2;Parent=mRNA_2
supercont1_1    prediction      three_prime_UTR 3811    4046    .       +       .       ID=UTR3_2;Parent=mRNA_2
Job done in 0 seconds

**Comment by Juke34** [comment]
Thank you for your feedback. Indeed there is a bug. Even with the csv flag the file is handle as tsv. I will fix it in a next release

**Comment by Juke34** [comment]
fixed in commit 00c842b8c05bf73050add95d02da564ff911317a
