### ISSUE TITLE
agat_sp_complement_annotations.pl does not merge/complement properly

### ISSUE THREAD

**Issue by nimarafati** [NBISweden/AGAT#140]
Hi Jacques,

I have two gff files reference.gff (12824 genes) and add.gff (8627 genes). When I use this script (reciprocally) all the genes/transcripts are combined. It reports exxact number of queries in each file at end of the job. TO make sure there is overlap between the gff files I intersected them by bedtools and there are may overlaps. I also checked it on webapollo and there are many features overlapping between two annotations. 

I appreciate if you have any hints to merge these two gff files and please let me know if I can provide more information. 

Regards,
Nima

**Comment by Juke34** [comment]
Hi Nima,

`agat_sp_complement_annotations.pl` add records (level1 features and all related sub-features.) from B that do not overlap a record of the same type in A, while `agat_sp_merge_annotations.pl` will also merge the records that overlap.
Overlap are checked only between same level2 feature type i.e. a ncRNA will not be merge with a tRNA even if they have overlaping exons.

**Comment by nimarafati** [comment]
Thanks for quick reply! I tried agat_sp_merge_annotations.pl it worked fine thanks!
