### ISSUE TITLE
Question on agat_sp_keep_longest_isoform.pl

### ISSUE THREAD

**Issue by sanyalab** [NBISweden/AGAT#148]
Hi Jacques,

This is a question about the agat_sp_keep_longest_isoform.pl script. 

This script keeps the longest mRNA that also codes for the longest CDS? OR just the longest mRNA, that may or may not code for the longest CDS. Is there a script to extract the mRNA coding for the longest CDS?

Thanks
Abhijit

**Comment by Juke34** [comment]
Hi, 
The answer is in the help ^^
```
The script aims to filter isoforms when present. For a locus:
- when all isoforms have CDS we keep the one with the longest CDS.
- when some isoforms have CDS some others not, we keep the one with the longest CDS.
- when none of the isoforms have CDS, we keep the one with the longest concatenated exons. 
```

**Comment by sanyalab** [comment]
Duh.... Sorry My bad
