### ISSUE TITLE
Question: Flipping genome annotation gff

### ISSUE THREAD

**Issue by sanyalab** [NBISweden/AGAT#149]
Hi Jacques,

I was wondering if you can suggest what to do in case I have to flip a chromosome that has annotation end to end. This is not the same as reverse-complementing the gff3. This will affect the order of genes and other elements. So basically if the chromosome has 100 genes, gene1 will become gene100 and vice-versa. Is there a solution in agat for this?

Further if this had to be performed for a segment within a chromosome how to do the same. I think in this case my option is reannotation. But I wanted to check if you had some other suggestions.

Best Regards
Abhijit

**Comment by Juke34** [comment]
Hi,
gene number or identifier does not matter in GFF3. The only thing to handle is the start and end coordinates of the feature on the chromosome. There is no tool do perform this type of thing within AGAT. It is something that might be implemented. Problematic cases can occur when trying to modify a region that do not span completely a feature...
Most of time when modifying the assembly people modify a lot of regions and prefer to run re-annotation/lift-over tools.
e.g. in your case a way would be to run MAKER and map annotation forwards to a new assembly (see Genome Annotation and Curation Using MAKER and MAKER-P doi: 10.1002/0471250953.bi0411s48)
