### ISSUE TITLE
FASTA files with very large unwrapped records generate exceptions in `agat_sp_extract_sequences.pl`

### ISSUE THREAD

**Issue by pmagwene** [NBISweden/AGAT#150]
I've encountered a bug in AGAT's `agat_sp_extract_sequences.pl` function (latest version from Conda as of 15 July 2021) where a Fasta input file that has a large entry with unwrapped lines generates the following error:
```
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Failed validation of sequence '[unidentified sequence]'. Invalid characters 
```

When I reformatted the Fasta file so that lines have a maximum of 70 chars the run completed without exception. 

I suspect this is hitting some character limit in Perl string size or something similar?

I can provide sample files that raise this exception, but I haven't had a chance to trim them down to a MWE, so they're somewhat large.

**Comment by pmagwene** [comment]
I'm guessing this is the same issue discussed in #56

**Comment by Juke34** [comment]
Difficult to say, I don't get why the bioperl message is not `MSG: Each line of the file must be less than 65,536 characters. Line 2 is 67824 chars.` then.
The problem may be something related.
Someone had a similar issue, see #37.

Happy to hear you found a way to solve this.

**Comment by pmagwene** [comment]
Would be useful to add a note to the documentation regarding wrapping of FASTA files as #37 and #56 seem to suggest that this isn't a rare hiccup folks encounter.

**Comment by Juke34** [comment]
Good point, something to add in the Troubleshooting section.

Thank you for your feedback
