### ISSUE TITLE
Installation failed using conda

### ISSUE THREAD

**Issue by bshrestha0** [NBISweden/AGAT#161]
Hi,

I am running into an issue while using conda to install AGAT.  It errors out with the following issue:

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libcxx conflicts for:
agat -> libdb -> libcxx[version='>=11.0.0|>=11.1.0']
python=3.9 -> libcxx[version='>=11.0.0.rc1|>=11.0.0|>=11.0.1']

So, I created new env using:
conda create --name envAGAT
conda activate envAGAT    
conda install -c bioconda agat

but still it errors out with:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                            

UnsatisfiableError: 

I couldn't figure out what's causing the error. I am using Miniforge3 by the way as Miniconda is problematic with ARM64. 

Any help is greatly appreciated!

**Comment by Juke34** [comment]
The way to go for now would be to do semi-manual-installation like that:

```
git clone https://github.com/NBISweden/AGAT.git # Clone AGAT
cd AGAT                                         # move into AGAT folder
conda env create -f conda_environment_AGAT.yml #install dependencies using conda
conda activate agat # activate the conda environement
perl Makefile.PL                                # Check all the dependencies*
make                                            # Compile
make test                                       # Test
make install                                    # Install
```
Let me know if it works

**Comment by bshrestha0** [comment]
Thank you for the suggestion. I tried like you have suggested but it failed while installing the dependencies using conda with the error:

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - perl-sort-naturally
  - perl-json
  - perl-lwp-simple
  - perl-file-share
  - perl-extutils-makemaker
  - perl-file-sharedir-install
  - perl-term-progressbar
  - perl-clone
  - perl-graph
  - perl-carp
  - perl-moose

I install couple of these perl module using cpan but still I am getting the same error while running "conda env create -f conda_environment_AGAT.yml".

**Comment by Juke34** [comment]
Oh wait it is because you have only conda forge and not bioconda...
type the following:
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

**Comment by Juke34** [comment]
Otherwise you should use the docker container. Do you have docker installed?
If yes you can do like that:

```
# get the tool
docker pull quay.io/biocontainers/agat:0.6.2--pl5262r35hdfd78af_0
# use an AGAT's tool
docker run quay.io/biocontainers/agat:0.6.2--pl5262r35hdfd78af_0 agat_convert_sp_gxf2gxf.pl --help
```

**Comment by bshrestha0** [comment]
Yes, I have docker installed. Let me try with that. I will send you the update. Thanks!

**Comment by bshrestha0** [comment]
It works with docker, thanks for your help!
