### ISSUE TITLE
UnsatisfiableError

### ISSUE THREAD

**Issue by emmannaemeka** [NBISweden/AGAT#166]
Hello,
While trying to use Conda to install AGAT, encountered this error

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package ncurses conflicts for:
python=3.9 -> ncurses[version='>=6.2,<7.0a0']
python=3.9 -> readline[version='>=8.0,<9.0a0'] -> ncurses[version='>=6.1,<7.0a0']

Package libcxx conflicts for:
python=3.9 -> libcxx[version='>=10.0.0']
python=3.9 -> libffi[version='>=3.3,<3.4.0a0'] -> libcxx[version='>=4.0.1']

Package readline conflicts for:
python=3.9 -> readline[version='>=8.0,<9.0a0']
agat -> r-base[version='>=3.5,<3.6.0a0'] -> readline[version='>=7.0,<8.0a0|>=8.0,<9.0a0']

**Comment by Juke34** [comment]
V0.8.0 is now available in conda. You can try if that version can be installed without problem
