### ISSUE TITLE
Error at exon-checking step

### ISSUE THREAD

**Issue by jpiggod** [NBISweden/AGAT#175]
Dear developer,

Thank you so much for creating this great tool to manipulate gtf/gff files. It has greatly helped me through my research recently as I'm doing a cross-species study but the genome annotation quality differs so vastly across different species (and that some of the downstream tools that I use indeed can only recognize some but not all annotation files). Here I would just like to share my own experience using AGAT and an error that I encountered (but solved after some effort searching through other pages in the documentation website).

For one species, I did not realize only CDS were annotated. I was using the`agat_sp_filter_feature_from_keep_list.pl` script (in the Docker package) to edit the annotation files. When I dealt with different species, I realized that AGAT could automatically detect the annotation format version (such as GTF or GFF3) and parse the file with the correct version parser. But for this species it kind of paused at the `Check8: check exons` step but no error message appeared, so I assumed the script is still doing some work. But a very long time (over 1 hr) passed and I still saw nothing, so I realized something wrong might have happened. 

I spent some time checking what the reason could be. I went back to check the genome annotation file and it looks like this:
```
1	Cufflinks	CDS	14618	15126	.	-	0	gene_id "Abc_G000001"; transcript_id "Trans_Abc_T000001"; exon_number "1";	
1	Cufflinks	CDS	14080	14185	.	-	1	gene_id "Abc_G000001"; transcript_id "Trans_Abc_T000001"; exon_number "2";	
1	Cufflinks	CDS	13389	13670	.	-	0	gene_id "Abc_G000001"; transcript_id "Trans_Abc_T000001"; exon_number "3";
```
 Apparently, this is GTF but somehow the parser recognized it, by default, as GFF version 3. Then I tried to use `agat_convert_sp_gxf2gxf.pl` to get the missing features (level 1 "gene", level 2 "mRNA", etc.), following the example in the "Omniscient - Standardisation for a full GFF3 compliant to any tool" part. Again, the program paused at the `Check8: check exons` step without any error message. Then I finally realized the script still parsed my annotation file as GFF3, and at last, I solved the problem by adding the `--gvi 2` option. 

As one of the aims of AGAT is to render GTF/GFF files from different upstream tools into a standardized form utilizable for most subsequent analyses, from my own example, I guess writing options such as `--gvi 2` in a more obvious location would be optimal. As this option is not supported in some other scripts such as the `agat_sp_filter_feature_from_keep_list.pl` that I was initially using, it indeed took me quite some time to realize what the solution could be. I hope my experience could better help the community in case some others encounter the same problem while editing GTF/GFF files.

**Comment by Juke34** [comment]
Hi @jpiggod, thank you for your feedback.
Could you tell me what AGAT version you have used?

I tried your example with recent version of AGAT and it used GFF2 parser as expected. Could you confirm that with this sample your AGAT version parse it with the GFF3 parser?

The GFF parser sensor has been improved in AGAT v0.6.2 (#119). The problem was similar as what you describe.

**Comment by jpiggod** [comment]
Dear @Juke34,

I was using the Docker version v0.8.0 (which I downloaded a few days ago), and I confirmed that my annotation file (gtf) was indeed parsed with gff3 while it should be recognized by the version 2 parser. 

The annotation file (gtf) I used was a version annotated by our lab ourselves, and so it may come with some unintentionally unrecognizable strings or attributes in some later entries (which I didn't go further deeper to look for the exact reason). I can send you the full original file in private in case that would be helpful for the development of the tool (simply because I'm not sure if the file is already available elsewhere as a downloadable file...). 

Both the `agat_convert_sp_gxf2gxf.pl` and the `agat_sp_filter_feature_from_keep_list.pl` scripts behaved similarly, parsing my file as a GFF3.
```
docker run --rm -it \
     -v PATH_EXTERNAL:PATH_INTERNAL \
     quay.io/biocontainers/agat:0.8.0--pl5262hdfd78af_0  \
     bash -c 'cd PATH_WHERE_THE_ANNOTATION_FILES_ARE \
      && /usr/local/bin/agat_convert_sp_gxf2gxf.pl \
      -g ANNOTATION.gtf \
      -o ANNOTATION.gff3'
```

- Jason.

**Comment by Juke34** [comment]
Yes please send me over the file, I will see if I can improve the sensor.

**Comment by Juke34** [comment]
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!                                   Doesn't look like a GFF file                                   !
!             Let's see what the Bioperl parser can do with that...(using gff3 parser)             !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

I will improve the sensor to be more precise in the information. Your file has 8 columns instead of 9 mandatory. That was the issue.
