### ISSUE TITLE
Parsing creates empty file

### ISSUE THREAD

**Issue by rsalz** [NBISweden/AGAT#179]
Hi,

I have 3 gff3 files created by [Transdecoder](https://github.com/TransDecoder/TransDecoder/blob/master/util/cdna_alignment_orf_to_genome_orf.pl). These files were all generated with the same script. Visually, I see no difference in format between the 3. For some reason, AGAT can only parse 2 out of the 3 gff files. The one that doesn't work actually _does_ run to completion (in 1 second). agat_convert_sp_gxf2gxf.pl produces an empty file. Pretty bizarre. What could be going on?

<img width="1011" alt="Screenshot 2021-09-21 at 4 44 11 PM" src="https://user-images.githubusercontent.com/6609784/134192892-be61fdc0-bcc9-4d90-8d7c-74befc925c7d.png">

TIA

**Comment by Juke34** [comment]
What version of AGAT are you using?

**Comment by rsalz** [comment]
Just updated my installation to the newest version and it doesn't seem to fix the problem. Here is what my GFF looks like:
<img width="1636" alt="Screenshot 2021-09-21 at 5 34 52 PM" src="https://user-images.githubusercontent.com/6609784/134201640-70092b0e-ba05-4b7c-86e3-63dd7455f610.png">
again, it seems to be identical in format to the other 2 GFF files where parsing did work properly.
What would you suggest I do?

**Comment by Juke34** [comment]
Check tabulation, you must have 9 columns separated by tabulations.
Check if you have windows carriage return (do a dos2unix to your file)

You can run agat_convert_sp_gxf2gxf.pl with verbosity to get more information: `-v 3`

**Comment by rsalz** [comment]
I work exclusively on Linux. To make 100% sure I had 9 columns with tabs, I imported my gff into a pandas DataFrame and simply printed out to a file again. That seemed to have fixed my problem. Weird.
Anyways, thanks for your quick responses! I'll close the issue.
