### ISSUE TITLE
looking in the wrong column for frame...?

### ISSUE THREAD

**Issue by goeckeritz** [NBISweden/AGAT#182]
Hi there, 

Thanks for making this excellent suite of tools! I had a question about an error I'm getting while trying to extract cds using 'agat_sp_extract_sequences.pl'

I run the script and get the following output:
Possible precedence issue with control flow operator at /mnt/ufs18/home-087/goeckeri/miniconda3/envs/agat/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
```
We will extract the cds sequences.
Reading file assembly.gff3
********************************************************************************
*                              - Start parsing -                               *
********************************************************************************
-------------------------- parse options and metadata --------------------------
=> Accessing the feature level json files
        Using standard /mnt/ufs18/home-087/goeckeri/miniconda3/envs/agat/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_level1.json file
        Using standard /mnt/ufs18/home-087/goeckeri/miniconda3/envs/agat/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_level2.json file
        Using standard /mnt/ufs18/home-087/goeckeri/miniconda3/envs/agat/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_level3.json file
        Using standard /mnt/ufs18/home-087/goeckeri/miniconda3/envs/agat/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_spread.json file
=> Attribute used to group features when no Parent/ID relationship exists:
        * locus_tag
        * gene_id
=> merge_loci option deactivated
=> Accessing Ontology
        No ontology accessible from the gff file header!
        We use the SOFA ontology distributed with AGAT:
                /mnt/ufs18/home-087/goeckeri/miniconda3/envs/agat/lib/site_perl/5.26.2/auto/share/dist/AGAT/so.obo
        Read ontology /mnt/ufs18/home-087/goeckeri/miniconda3/envs/agat/lib/site_perl/5.26.2/auto/share/dist/AGAT/so.obo:
                4 root terms, and 2472 total terms, and 1436 leaf terms
        Filtering ontology:
                We found 1757 terms that are sequence_feature or is_a child of it.
-------------------------------- parse features --------------------------------
=> GFF version parser used: 3
Parsing:  10% [=====                        *                        ]2m19s Left
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: 'ID=Pcer_009796-RA:exon:1183;Parent=Pcer_009796-RA;' is not a valid frame
STACK: Error::throw
STACK: Bio::Root::Root::throw /mnt/ufs18/home-087/goeckeri/miniconda3/envs/agat/lib/site_perl/5.26.2/Bio/Root/Root.pm:447
STACK: Bio::SeqFeature::Generic::frame /mnt/ufs18/home-087/goeckeri/miniconda3/envs/agat/lib/site_perl/5.26.2/Bio/SeqFeature/Generic.pm:503
STACK: Bio::Tools::GFF::_from_gff3_string /mnt/ufs18/home-087/goeckeri/miniconda3/envs/agat/lib/site_perl/5.26.2/Bio/Tools/GFF.pm:624
STACK: Bio::Tools::GFF::from_gff_string /mnt/ufs18/home-087/goeckeri/miniconda3/envs/agat/lib/site_perl/5.26.2/Bio/Tools/GFF.pm:437
STACK: Bio::Tools::GFF::next_feature /mnt/ufs18/home-087/goeckeri/miniconda3/envs/agat/lib/site_perl/5.26.2/Bio/Tools/GFF.pm:395
STACK: AGAT::OmniscientI::slurp_gff3_file_JD /mnt/ufs18/home-087/goeckeri/miniconda3/envs/agat/lib/site_perl/5.26.2/AGAT/OmniscientI.pm:317
STACK: /mnt/home/goeckeri/miniconda3/envs/agat/bin/agat_sp_extract_sequences.pl:130
-----------------------------------------------------------
```

That one gene it is throwing an error at is one I had to manually add to the .gff file. It sounds like the error is trying to tell me that column 9 is being read in as column 8 (where frame should be), but this doesn't make much sense to me. I'm not sure how this script parses the file, but it throws the error on this line in particular, when there is a similar exon line just above it. Attached is a screenshot of what the file looks like in this area. 

Any idea what might be causing it? I've been triple-checking the spacing of the added lines, but can't seem to find an issue. And it is strange to me that the exon:1182 line just above did not throw the error first. In other words, I can't figure out why exon:1182 is parsed fine but exon:1183 throws this error.

Any advice on how to fix the issue is greatly appreciated! Thanks for your time.
Kindly,
Charity 

![agat_error_009796](https://user-images.githubusercontent.com/46759938/135697541-5f63bdec-15c7-42bd-87a3-31b9e19592c5.JPG)

**Comment by Juke34** [comment]
Hi, 
the error is thrown by BioPerl which parse the file for AGAT.

This is a typical error related to the field separator which is not respected. You must check again, you probably have something else than a tabulation between the columns. It might also be 2 tabulations in a row instaed of one for separating  2 columns.

**Comment by goeckeritz** [comment]
You were right! I had secret double tabs after the chromosome name for these lines... Thank you so much!!
