### ISSUE TITLE
agat_sp_manage_functional_annotation.pl exons missing

### ISSUE THREAD

**Issue by ctxchris** [NBISweden/AGAT#184]
Hi,

I used Uniprot and Interpro mappings to update my annotation file as described in the manual.
The log file shows a couple of these error messages:
`Use of uninitialized value within %finalID in concatenation (.) or string at anaconda3/envs/agat/bin/agat_sp_manage_functional_annotation.pl line 493, <GEN1> line 496463.`
The number of genes is almost the same, but oddly, the output gff has only 1/3 of the exons.

Best,
Chris

**Comment by Juke34** [comment]
First let's have a look at the exon problem. Could you run agat_convert_sp_gxf2gxf.pl to check the sanity of the file and see if AGAT throws the exons?
