### ISSUE TITLE
Getting output of agat_sp_filter_record_by_coordinates.pl in seperate gff3 files

### ISSUE THREAD

**Issue by sanyalab** [NBISweden/AGAT#193]
Hi Jacques,

I was working with the agat_sp_filter_record_by_coordinates.pl script and noticed that when multiple ranges are given, the results are clubbed together into a single file. It then becomes difficult to tease apart the records pertaining to each range. Below is an hypothetical example of what I mean.

Command:
agat_sp_filter_record_by_coordinates.pl --gff infile.gff --tsv coordinates.tsv --output outfile.gff3

Contents of coordinates.tsv
`Chr01     Start1     End1`
`Chr01     Start2     End2`
`Chr02     Start3     End3`

When you run the above command, the output of all the ranges get appended to a single gff3 file outfile.gff3. This then becomes difficult to tease apart in order to get the output for each range. 

I therefore propose that the output be directed to seperate files named as `Chr01_Start1_End1.gff3, Chr01_Start2_End2.gff3, Chr02_Start3_End3.gff3 and so on` and all files be stored in a single OUTPUT folder. 

Thanks
Abhijit

**Comment by Juke34** [comment]
Hi,
Yes it sounds a good request. We can implement this.

**Comment by sanyalab** [comment]
Hi Jacques,

I was able to download the updated code of "agat_sp_filter_record_by_coordinates.pl" and test out the same. There happens to be a small error that I would like to point out. While the code works for non-overlapping ranges, for overlapping ranges it misses records. Here is an example and I am attaching my test files as well.

**Coordinates:** `te1.tsv` - **If you notice the coordinates are overlapping**
`Chr00   5324888 5327675`
`Chr00   5325338 5332773`

Input GFF: `fabales_test.gff3` - **Test Gff3** contains 6 gene records

Output GFF:
`Chr00_5324888_5327675.gff3`
`Chr00_5325338_5332773.gff3`

Files: `te1.stdout`, `te1.stderr` - Verbose output

`Chr00_5324888_5327675.gff3` has 5 records from input GFF `fabales_test.gff3` - This is correct!
`Chr00_5325338_5332773.gff3` should have 5 records as well but instead has 1 since the other 4 have coordinates overlapping with `Chr00_5324888_5327675.gff3`. 

I think each range provided should have its own output in a separate file (implemented) irrespective of whether it overlaps with any other given range. I'll be happy to test if you choose to look into the same.
[TestData.zip](https://github.com/NBISweden/AGAT/files/7560917/TestData.zip)

**Comment by Juke34** [comment]
Thank you for the feedback.
Right I didn't think about this case. We should fix it.

**Comment by sanyalab** [comment]
Hi Jacques,

Should I use the code from master? I am getting the following error. Printing the last few lines of a verbose output

Command: `perl agat_sp_filter_record_by_coordinates.pl --gff fabales_test.gff3 --coordinates te1.tsv --output OUT2 --verbose`

Output: Last few lines
`feature [gene 5326802,5327092] is included or overlap the range [5325338 5332773]`
`feature [gene 5327125,5327663] is included or overlap the range [5324888 5327675]`
`feature [gene 5327125,5327663] is included or overlap the range [5325338 5332773]`
`feature [gene 5327366,5327675] is included or overlap the range [5324888 5327675]`
`feature [gene 5327366,5327675] is included or overlap the range [5325338 5332773]`
`feature [gene 5332346,5332773] is included or overlap the range [5325338 5332773]`
`Undefined subroutine &main::subsample_omniscient_from_level1_id_list_intact called at /AGAT_EARLY/agat_sp_filter_record_by_coordinates_early.pl line 157.`

**Comment by Juke34** [comment]
You must run `make install` first to update the AGAT library

**Comment by sanyalab** [comment]
I see..... I am using the latest version of AGAT via conda. I did `conda update AGAT`. That updated the ncurses library and `pip`. Where do I run `make install` from?

Thanks

**Comment by sanyalab** [comment]
Figured it out. Sorry for the false alarm. It works!!! Thank you so much
