### ISSUE TITLE
Fail to read gff

### ISSUE THREAD

**Issue by emilhaegglund** [NBISweden/AGAT#2]
Hi!
I tried to run agat_sp_merge_annotations.pl on gffs from prokka and PGAP, but it fails. The gffs from these annotation tools contains multiple lines of comments in the beginning of the file, removing all commented lines but the first solved the issue.
```
Can't use string ("#!gff-spec-version 1.21
#!proces"...) as a HASH ref while "strict refs" in use at /home/emil/miniconda3/envs/agat/lib/site_perl/5.26.2/AGAT/OmniscientTool.pm line 1104.
```
Cheers,
Emil

**Comment by Juke34** [comment]
Thank for the feedback
Could you run `agat_gxf_to_gff3.pl --gff annotation` to each of them independently to see which file is failing. 
Could you then provide me a link to the failing file?

**Comment by Juke34** [comment]
Are, I see a stupid modification I did before to release the tool that I didn't test extensively, I didn't think it would affect other part of the code...
I will fix that
