### ISSUE TITLE
"unknown_id" for all entries when converting embl to gff 

### ISSUE THREAD

**Issue by webbchen** [NBISweden/AGAT#201]
Dear developers
I ran ` agat_convert_embl2gff.pl --embl pbs3_v1.embl -t source -d -o pbs3_v1.gff3` and it finished without complaint. In the resulting file however the IDs got lost somehow, causing trouble with downstream processing:
```
##gff-version 3
unknown_id      EMBL/GenBank/SwissProt  gene    38269   38592   .       +       1       locus_tag=PBS003_LOCUS1;note=ID:g1130,source:AUGUSTUS
unknown_id      EMBL/GenBank/SwissProt  mRNA    38269   38592   .       +       1       locus_tag=PBS003_LOCUS1;note=ID:g1130.t1,source:AUGUSTUS
unknown_id      EMBL/GenBank/SwissProt  CDS     38269   38592   .       +       1       codon_start=1;locus_tag=PBS003_LOCUS1;note=ID:g1130.t1.CDS1,source:AUGUSTUS;transl_table=1;translation=MM(...)>
unknown_id      EMBL/GenBank/SwissProt  gene    44903   48115   .       +       1       locus_tag=PBS003_LOCUS2;note=ID:g1131,source:AUGUSTUS
unknown_id      EMBL/GenBank/SwissProt  mRNA    44903   48115   .       +       1       locus_tag=PBS003_LOCUS2;note=ID:g1131.t1,source:AUGUSTUS
unknown_id      EMBL/GenBank/SwissProt  CDS     44903   48115   .       +       1       codon_start=1;locus_tag=PBS003_LOCUS2;note=ID:g1131.t1.CDS1,source:AUGUSTUS;transl_table=1;translation=MA(...)>
unknown_id      EMBL/GenBank/SwissProt  gene    48895   50964   .       -       1       locus_tag=PBS003_LOCUS3;note=ID:g1132,source:AUGUSTUS
unknown_id      EMBL/GenBank/SwissProt  mRNA    48895   50964   .       -       1       locus_tag=PBS003_LOCUS3;note=ID:g1132.t1,source:AUGUSTUS
unknown_id      EMBL/GenBank/SwissProt  CDS     48895   50964   .       -       1       codon_start=1;locus_tag=PBS003_LOCUS3;note=ID:g1132.t1.CDS1,source
(...)
```
The embl file was generated with [EMBLmyGFF](https://github.com/NBISweden/EMBLmyGFF3#gff3-attribute-to-embl-qualifier) and has been validated  successfully by webin-cli 4.2.3 for submission, so I assume that one is a good file.
Both are attached. 
I tried to retrieve various sequences with `agat_sp_extract_sequences.pl` which worked perfectly with the original gff3 and the assembly. Reason for trying to use the gff extracted from the ensembl file rather than the originals: the locus tags for the genes.
[pbs3_v1.embl.gz](https://github.com/NBISweden/AGAT/files/7588049/pbs3_v1.embl.gz)
[pbs3_v1.gff3.gz](https://github.com/NBISweden/AGAT/files/7588051/pbs3_v1.gff3.gz)

**Comment by Juke34** [comment]
For submission `AC` line differs slightly.
You have a file for submission `AC * _contig_100_0`, once accepted by ENA this line would become so;ething like `AC contig_100_0`. `agat_convert_embl2gff.pl` is just a wrap around the bioperl converting method. I guess when trying to catch the sequence id it catches `*` and translate it into "unknown_id". 
To use the .embl file from `EMBLmyGFF3` you must clean the AC line properly using e.g. a `sed` command.

**Comment by Juke34** [comment]
Please, feel free to re-open the thread if needed

**Comment by webbchen** [comment]
Apologies. After repairing the head, removing the offending "*" as well as the leading "_" the problem remains the same.

**Comment by Juke34** [comment]
Ok I checked the code dealing with the AC line in bioperl (https://github.com/bioperl/bioperl-live/blob/ce6da0217007ddf444399bc33a5455dbb32a66a0/lib/Bio/SeqIO/embl.pm#L289)
You need a AC line in this form: 
`AC    info1; info2`
In this case `info1` becomes your accession ID and is set as  sequence id in the GFF, and info2 as secondary accession is not used.

With AC line with that shape:  
`AC    info1`  or  `AC   *  info1`  ,  `info1` or `*  info1`  becomes the secondary accession and the primary accession is set to 'unknown'.

**Comment by Juke34** [comment]
Sorry I double checked actually the sequence ID is not extracted from the `AC` but the `ID` line... see here https://github.com/bioperl/bioperl-live/blob/ce6da0217007ddf444399bc33a5455dbb32a66a0/lib/Bio/SeqIO/embl.pm#L222

The header for submission with EMBLmyGFF3 has this shape:  
```
ID   XXX; XXX; linear; genomic DNA; XXX; INV; 1351857 BP.
```
You must replace the second XXX by e.g. `SV 1` to make it looks like EMBL accepted flat file. And replace the first XXX by the sequence ID which is hold by the AC line...:  
```
ID   sequenceID; SV 1; linear; genomic DNA; XXX; INV; 1351857 BP.
```

I will see if I can make a patch from the AGAT side to deal with specific case of EMBL flat file shaped for submission purpose

**Comment by webbchen** [comment]
Thanks for looking into this, much appreciated.
As predicted in your last post, editing the two ACs didn't repair it.
