### ISSUE TITLE
Increase the usage of combined assignment operators

### ISSUE THREAD

**Issue by elfring** [NBISweden/AGAT#202]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of combined operators](https://perldoc.perl.org/perlop#Assignment-Operators "Description for assignment operators") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's/(?<target>\$\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+%^.x]|-(?!>)|&(?:&|.)?|\|(?:\||.)?|\*\*?|\/\/?|<<|>>|^.)/$+{target} $+{operator}=/gm' $(find ~/Projekte/AGAT/lokal -name '*.pl')
```

:crystal_ball: How will development interests evolve further also according to update candidates in 40 lines of this software?

**Comment by elfring** [comment]
:thought_balloon: I would appreciate a more constructive feedback.

**Comment by Juke34** [comment]
In what way this kind of transformation would be helpful for the tool?

**Comment by elfring** [comment]
I suggest to benefit more from a bit nicer run time characteristics also for this software.

Would you dare to take another look at data processing results from the mentioned Perl command example? :thinking:
