### ISSUE TITLE
retain only protein coding genes

### ISSUE THREAD

**Issue by colin986** [NBISweden/AGAT#218]
Hi - great tool, 

Just wondering if there is a method to filter a GTF by biotype in AGAT? In my GTF I want to only keep features relating to protein coding genes. Thanks!
Colin

**Comment by Juke34** [comment]
You can use agat_sp_filter_feature_by_attribute_value.pl or agat_sp_separate_by_record_type.pl for this task.

**Comment by colin986** [comment]
Thanks a million for replying, it worked perfectly!
Colin
