### ISSUE TITLE
Parsings stops & outputs empty file

### ISSUE THREAD

**Issue by maese005** [NBISweden/AGAT#226]
Hello,

I am trying to apply AGAT to merge and compare several GTF files. I am using the commands here: 
**agat_sp_merge_annotations.pl --gff file1.gtf --gff file2.gtf --out merge** and also **agat_sp_compare_two_annotations.pl -gff1 file1q.gtf -gff2 file2.gtf --out compare**

I've installed AGAT via docker and via conda, both with success. Here are my observations:

- Often, the parsing will stop around 14% through docker. The merged file will be blank.
- The parsing will stop around 20% through conda. I'm unsure of why there is a difference. The merged file will also be blank. 

Any idea as to why the parsing stops and why the outputs are blank?

Thank you.

**Comment by Juke34** [comment]
Hi, sounds like a memory limit exceeded. The AGAT script with _sp_ prefix put file into memory. So if your files are big and the memory available low, it can crash. You should check what is going on when the script is running using a top or htop command on your machine.
