### ISSUE TITLE
Plot output from agat_sp_manage_introns.pl ?

### ISSUE THREAD

**Issue by eggrandio** [NBISweden/AGAT#227]
I am trying to plot intron length distribution using 
```
agat_sp_manage_introns.pl --gff Arabidopsis_thaliana.TAIR10.52.gff3 --plot --break 500
```
But I cannot find any plot being generated. I have tried including a file-name ( `--plot test.pdf` ), or `> test.pdf` at the end of the command but it is still not working.

Any help would be appreciated, and I suggest updating the `agat_sp_manage_introns.pl --help` output.

**Comment by Juke34** [comment]
If you look at the lines before
```
********************************************************************************
*                              - Start parsing -                               *
********************************************************************************
```
In the log you should have your answer.
Eihter R or the perl library Statistics::R is not installed

**Comment by eggrandio** [comment]
Thanks for your quick answer, indeed I did not have Statistics::R installed. I was looking at the end of the output instead of the beginning, my bad...
