### ISSUE TITLE
problems about the agat_sp_fix_fusion.pl

### ISSUE THREAD

**Issue by Huangyizhong** [NBISweden/AGAT#228]
Hi, there
  Good AGAT for the analysis for the gtf or gff3 files.  I have used the agat_convert_sp_gxf2gxf.pl to add the gene name into the final gffs files ,it works well. After I check the results in the IGV, I found that some gene covers too long region.  As shown in the followed picture.  The ANO9 gene also covered the SIGIRR gene ,so the final gene region was too large.  This long transcripts were assemblied by the stringtie2 with the illumina data. I wonder how can I deal with it ? So I used the  agat_sp_fix_fusion.pl to label the fusion gene (maybe can deal with the problems). But there was a problems. 

=> OmniscientI total time: 76 seconds
GFF3 file parsed
Fasta file parsed
Progress : 1 %Can't call method "start" on an undefined value at /home/softwares/miniconda3/bin/agat_sp_fix_fusion.pl line 1019.

How to deal with it ?
Thanks so much!
Yizhong Huang 
![image](https://user-images.githubusercontent.com/31943359/156696648-b8408513-1dd6-43e7-95a6-9e5f6c02ff39.png)

**Comment by Juke34** [comment]
Hi,
you were right, the use of  agat_sp_fix_fusion.pl was the one to use to fix those problems. But I don't know what is the problem. Could you give me a sample file?
Could you tell me the AGAT version you use?

**Comment by Huangyizhong** [comment]
> Hi, you were right, the use of agat_sp_fix_fusion.pl was the one to use to fix those problems. But I don't know what is the problem. Could you give me a sample file? Could you tell me the AGAT version you use?

Thanks for your quick reply. I am reading the usage of the AGAT tools carefully. The AGAT version is  Version: v0.8.0. What I want to use the agat_sp_fix_fusion.pl is to deal with the fusion transcripts from the illumina assembly. As shown clearly in the followed pictures. Because of the longest UTR of the labeled transcripts (two of the RIC8A gene), which covered two other genes. I want to filter them, or split the UTR and make it become two genes. I am wonder how to deal with this problems. Any suggestions?
Thanks so much

![image](https://user-images.githubusercontent.com/31943359/156727717-1b773887-59d9-4fae-bd8c-c895723b9489.png)

**Comment by Juke34** [comment]
` agat_sp_fix_fusion.pl` will split the UTR and make it become two genes. But I don't know why the script crashes and I cannot fix it without any test/exmaple file.

**Comment by Huangyizhong** [comment]
> ` agat_sp_fix_fusion.pl` will split the UTR and make it become two genes. But I don't know why the script crashes and I cannot fix it without any test/exmaple file.

Ok, I will attach some need files and thanks advance for your kind help! I will do it as soon as possible!
Thanks

**Comment by Huangyizhong** [comment]
Hi ,there.
 I have uploaded the test files. Thanks for you help~ Hoe deal with the labeled transcripts?
Thanks so much !
Yizhong Huang 
![image](https://user-images.githubusercontent.com/31943359/156735791-195606c4-569e-41b6-8bb9-2d734ac83cb5.png)
[test.zip](https://github.com/NBISweden/AGAT/files/8184580/test.zip)

**Comment by Juke34** [comment]
Could you try with AGAT v0.8.1 ?

**Comment by Huangyizhong** [comment]
OK, I will try it later! Thanks so much for your kind help. I have another question about the AGAT, if there are two copies in the same chromosome. As I see in the IGV, the agat_convert_sp_gxf2gxf.pl  will combine them together and the range of this gene maybe too long! Is there some suggestion to deal with it?

Thanks

**Comment by Juke34** [comment]
You do not have gene feature so when reading a mRNA e.g.
```
chr2_MotherHap  transdecoder    mRNA    13624   36601   .       +       .       ID=transcript:MSTRG.17645.2.p19013781;Parent=gene:ADAMTS10;Name=ADAMTS10;biotype=protein_coding;transcript_id=MSTRG.17645.2.p19013781
```
AGAT will create the gene feature with ID `gene:ADAMTS10` as it mentioned in the mRNA feature. If two mRNAs have the same gene parent, AGAT create only one gene feature and will adpat the start and stop location to agree with the underlying mRNAs. The two mRNA are isoforms. If the `Parent` attribute is wrong then it is problematic.

**Comment by Juke34** [comment]
The script does not crash for me.

**Comment by Juke34** [comment]
The script does not crash for me.

**Comment by Huangyizhong** [comment]
> The script does not crash for me with your data test.

Thanks ,I will update the agat to v0.8.1 and try it again!
Thanks so much !

**Comment by Huangyizhong** [comment]
> You do not have gene feature so when reading a mRNA e.g.
> 
> ```
> chr2_MotherHap  transdecoder    mRNA    13624   36601   .       +       .       ID=transcript:MSTRG.17645.2.p19013781;Parent=gene:ADAMTS10;Name=ADAMTS10;biotype=protein_coding;transcript_id=MSTRG.17645.2.p19013781
> ```
> 
> AGAT will create the gene feature with ID `gene:ADAMTS10` as it mentioned in the mRNA feature. If two mRNAs have the same gene parent, AGAT create only one gene feature and will adpat the start and stop location to agree with the underlying mRNAs. The two mRNA are isoforms. If the `Parent` attribute is wrong then it is problematic.

Yes, I know that. If the two mRNAs with the same name at same chromosome, but they are the two copies of this gene, not the two isoforms for the same gene. So I just want to add the gene name for them seperately. How to do it ? Sorry to disturb again!

**Comment by Huangyizhong** [comment]
> Could you try with AGAT v0.8.1 ?

So sorry for that, I try to update or re-download the AGAT, but all are still the v0.8.0? I wonder if there is something wrong about it ?
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/31943359/156793972-2a089d41-6d8f-48ed-b7c7-57b9ddfca49c.png">

Thanks

**Comment by Juke34** [comment]
Yes sorry, the header is misleading, I forgot to increment to 0.8.1 when I made the release. Better to check with `conda list`
What about the script? Did it works for you?

**Comment by Juke34** [comment]
Please feel free to re-open the issue if it is still not working for you.
