### ISSUE TITLE
Can't locate Sort/Naturally.pm in @INC while running agat_convert_sp_gff2bed.pl

### ISSUE THREAD

**Issue by Rohit-Satyam** [NBISweden/AGAT#231]
I tried installing AGAT and I am getting the following error.

```
Can't locate Sort/Naturally.pm in @INC (you may need to install the Sort::Naturally module) (@INC contains: /home/rohit/miniconda3/envs/agat/lib/perl5/5.32/site_perl /home/rohit/miniconda3/envs/agat/lib/perl5/site_perl /home/rohit/miniconda3/envs/agat/lib/perl5/5.32/vendor_perl /home/rohit/miniconda3/envs/agat/lib/perl5/vendor_perl /home/rohit/miniconda3/envs/agat/lib/perl5/5.32/core_perl /home/rohit/miniconda3/envs/agat/lib/perl5/core_perl .) at /home/rohit/miniconda3/envs/agat/lib/perl5/site_perl/AGAT/OmniscientI.pm line 12.
BEGIN failed--compilation aborted at /home/rohit/miniconda3/envs/agat/lib/perl5/site_perl/AGAT/OmniscientI.pm line 12.
Compilation failed in require at /home/rohit/miniconda3/envs/agat/lib/perl5/site_perl/AGAT/Omniscient.pm line 9.
BEGIN failed--compilation aborted at /home/rohit/miniconda3/envs/agat/lib/perl5/site_perl/AGAT/Omniscient.pm line 9.
Compilation failed in require at /home/rohit/miniconda3/envs/agat/bin/agat_convert_sp_gff2bed.pl line 8.
BEGIN failed--compilation aborted at /home/rohit/miniconda3/envs/agat/bin/agat_convert_sp_gff2bed.pl line 8
```
The `libsort-naturally-perl ` is already installed as can be seen below.
![image](https://user-images.githubusercontent.com/55479480/158078241-0eff98db-bf83-465b-a244-3a93019d9c47.png)

What could be the issue? Note I used `mamba` to install AGAT if that matters.

**Comment by Juke34** [comment]
CONDA or MAMBA should not make any difference. Do you see  Sort::Naturally installed in your env:
`conda list`

What version of AGAT did you install?

**Comment by Juke34** [comment]
I hope you found your way, don't hesitate to reopen the issue if you are still in trouble.

**Comment by Rohit-Satyam** [comment]
Thanks for addressing my issue. You answered quickly but I failed to respond in time.  The `conda update agat`  fixed the issue.
Thanks for quickly responding to our grievances always.

**Comment by bwbai** [comment]
delete /anaconda3/bin/perl,  will fix the issue.

**Comment by loukesio** [comment]
Dear all, thank you for AGAT
I am still getting the same even after updating agat: 
I am installing agat using conda:
```
conda install -c bioconda agat
```

And when I use the following function: 

```
agat_convert_sp_gff2bed.pl -gff Arabidopsis_thaliana_TAIR10.gff3 -o ucscTrack/Arabidopsis_thaliana_TAIR10.bed 
```
 I am getting the following error. 

```
Can't locate Sort/Naturally.pm in @INC (you may need to install the Sort::Naturally module) (@INC contains: /Software/Anaconda3/lib/perl5/site_perl/AGAT/OmniscientI.pm line 12.
BEGIN failed--compilation aborted at /Software/Anaconda3/lib/perl5/site_perl/AGAT/OmniscientI.pm line 12.
Compilation failed in require at /Software/Anaconda3/lib/perl5/site_perl/AGAT/Omniscient.pm line 9.
BEGIN failed--compilation aborted at /Software/Anaconda3/lib/perl5/site_perl/AGAT/Omniscient.pm line 9.
Compilation failed in require at /Software/Anaconda3/bin/agat_convert_sp_gff2bed.pl line 8.
BEGIN failed--compilation aborted at /Software/Anaconda3/bin/agat_convert_sp_gff2bed.pl line 8.
```

any help is appreciated :)

**Comment by Juke34** [comment]
What version of agat? 
`conda list`

**Comment by loukesio** [comment]
thank you @Juke34, for the prompt reply. It is 
``
agat                     version--0.9.2           pl5321hdfd78af_1    bioconda
```

**Comment by loukesio** [comment]
Yes yes I have it 

```
perl-sort-naturally       version--1.03                  
```

**Comment by Juke34** [comment]
Then I guess the perl called is not the one from the environment. Could you check `which perl`

**Comment by loukesio** [comment]
Yes, yes of course. 
```
which perl

/Software/Anaconda3/envs/agat/bin/perl
```

**Comment by Juke34** [comment]
Then this is odd.
You can try to update the env: conda update agat
Or create a fresh new env: 
```
conda deativate
conda create -n agat_again agat 
activate agat_again
```

**Comment by loukesio** [comment]
Thank you so much @Juke34 it worked!!!  :)
Why it worked now? What did you change?
Thank you for your time, I really appreciate your prompt replies!!!

**Comment by Juke34** [comment]
> Why it worked now? What did you change?

Computer secrets... I didn't change anything but sounds like one the path was not properly resolve by your machine.

**Comment by GiammaFer75** [comment]
Hi Juke, I got the same issue.

I think that my `which perl` is wrong: `/opt/software/eb/software/Perl/5.36.1-GCCcore-12.3.0/bin/perl` right?

**Comment by Juke34** [comment]
If you were trying to use conda, yes this shows that you are not using the Perl from the conda env
