### ISSUE TITLE
Version number mismatch

### ISSUE THREAD

**Issue by sanyalab** [NBISweden/AGAT#235]
HI Jacques,

This is just a query not a bug. I installed AGAT a bit unconventionally using conda since installation directly from Anaconda repo gave errors. My steps are as follows

`git clone https://github.com/NBISweden/AGAT.git`
`cd AGAT/`
`conda env create -f conda_environment_AGAT.yml`
`conda activate agat`
`perl Makefile.PL`       ## Gave List::MoreUtils not found warning Therefore below step
`cpanm List::MoreUtils`
`perl Makefile.PL`       ## Works OK!
`make`                        ## Works OK!
`make test`                 ## PASS
`make install`              ## SUCCESS

However, when I do `agat_sp_functional_statistics.pl --help` after this, I see the version as v0.8.0. Is this a typo? I see the same for `agat_sp_sensitivity_specificity.pl --help`. Please let me know.

Thanks
Abhijit

**Comment by Juke34** [comment]
Hi, yes this is a typo this is well v0.8.1. The next version will be 0.8.2
