### ISSUE TITLE
How to change the name of the copy genes in the same or other chromosomes?

### ISSUE THREAD

**Issue by Huangyizhong** [NBISweden/AGAT#241]
Hi, there
  The agat is a good software to deal with the gff or gtf file.  During the process to modify the gff files , I have a problem in the name of the copy genes in the same or other chromosomes. It sees that I have not found some scripts to deal with it . Can you give me some help? By the way, I also use the agat_sp_statistics.pl to summary the mouse gff3 file ,but it take long time and the results just contains the information about the c_gene_segment (Mus_musculus.GRCm39.105.gff3  and Mus_musculus.GRCm39.dna.toplevel.fa), need your help! 
Thanks so much!

**Comment by Juke34** [comment]
If you want to modify the gene identifier you play with `agat_sp_manage_IDs.pl`.
If you problem is about gene name then AGAT cannot do so much about it. You better need a functionnal annotation tool.
Please provide example to better explain what you have and what you would like.

About Mus_musculus.GRCm39.105.gff please open new issue and provide a link to access the file you are talking about.
