### ISSUE TITLE
No results about the agat_sp_statistics.pl  scripts

### ISSUE THREAD

**Issue by Huangyizhong** [NBISweden/AGAT#242]
Hi,
  I want to use the agat_sp_statistics.pl to summary the mouse gff3 file ,but it take long time and the results just contains the information about the c_gene_segment (Mus_musculus.GRCm39.105.gff3 and Mus_musculus.GRCm39.dna.toplevel.fa  are all from the ensembl， http://ftp.ensembl.org/pub/release-105/gff3/mus_musculus/), should do something before add the files into the agat_sp_statistics.pl ?
Thanks advance!
Yizhong Huang

**Comment by Juke34** [comment]
What version did  you use?
I tried Mus_musculus.GRCm39.105.gff3 with AGAT v0.9.0, it tooks some times (935 seconds)  but it worked fine.

**Comment by Juke34** [comment]
Sorry I was talking about agat_convert_sp_gxf2gxf.pl, it will give a shot to agat_sp_statistics.pl

**Comment by Huangyizhong** [comment]
Thanks for your quick reply! Would you minding trying the agat_sp_statistics.pl ?
Thanks!

**Comment by Juke34** [comment]
Right There is an issue with a loop no well design that check overlap between features. The problem arise when there is a lot of `topfeature` or `standalone` features (e.g. biological_region in your case).
I will push a fix.

**Comment by Juke34** [comment]
To install the lastest version from the `master branch`:
https://agat.readthedocs.io/en/latest/troubleshooting.html#how-to-use-a-version-of-agat-from-a-specific-branch
