### ISSUE TITLE
Could we maintain the functional annotation when use agat_sp_extract_sequences.pl

### ISSUE THREAD

**Issue by zmz1988** [NBISweden/AGAT#246]
Hello, thanks for the very nice tool of agat! It's very helpful!

I'm now at the last step to generate the protein sequence fasta file with the annotations in the headline. What I have in hand is the gff file with functional annotation information, which was generated by `agat_sp_manage_functional_annotation.pl` with interproscan results. Now I would like to generate the protein fasta file with annotation info for my college to do protein search. I had tried `agat_sp_extract_sequences.pl` but the resulted fasta file has no functional annotation info. Do you know whether we could do this with agat? Thanks a lot!

**Comment by Juke34** [comment]
Hi, sorry  it is not currently possible.
We could add a parameter to keep all gff attributes from mRNA within the header of the generated fasta file.

**Comment by zmz1988** [comment]
If the optional could be added, that would be great!! Thanks!!

**Comment by Juke34** [comment]
I made an update. Could you try it using the branch `246` (https://agat.readthedocs.io/en/latest/troubleshooting.html#how-to-use-a-version-of-agat-from-a-specific-branch)

you will have to use the option `--keep_parent_attributes`.
I wanted to make it simple, so all attributes from GFF are stored within the fasta header.

**Comment by zmz1988** [comment]
Thank you! It seems work fine! Really appreciated!
