### ISSUE TITLE
agat_convert_sp_gff2gtf: Is there a way to retain identical isoforms?

### ISSUE THREAD

**Issue by venuraherath** [NBISweden/AGAT#247]
Hi Jacques,

I have a quick question. Is there a way to maintain identical isoforms when we convert? 
It interferes with my Kallisto/IsoformSwitchAnalyzeR pipeline given that it requires 27 identical isoforms removed during the conversion.
Thank you in advance.

**Comment by Juke34** [comment]
Currently it is possible to skip some tests as the identical isoform one but only from the agat_sp_kraken_assess_liftover.pl script. The easiest for you would be to remove 
```
	if(! $no_check or	grep( /check_identical_isoforms/, @$no_check_skip ) ) {
		#check identical isoforms
		dual_print ($log, file_text_line({ string => "Check$check_cpt: remove identical isoforms", char => "-", prefix => "\n"}), $verbose );
		_check_identical_isoforms($log, \%omniscient, \%mRNAGeneLink, $verbose);
		dual_print ($log, file_text_line({ string => "	 done in ".(time() - $previous_time)." seconds", char => "-" }), $verbose );
		$check_cpt++; $previous_time = time();
	}
```
from the OmniscientI.pm code .

We might try to find an easy way to avoid some tests like that but it will not be in a near future.

**Comment by venuraherath** [comment]
> Currently it is possible to skip some tests as the identical isoform one but only from the agat_sp_kraken_assess_liftover.pl script. The easiest for you would be to remove
> 
> ```
> 	if(! $no_check or	grep( /check_identical_isoforms/, @$no_check_skip ) ) {
> 		#check identical isoforms
> 		dual_print ($log, file_text_line({ string => "Check$check_cpt: remove identical isoforms", char => "-", prefix => "\n"}), $verbose );
> 		_check_identical_isoforms($log, \%omniscient, \%mRNAGeneLink, $verbose);
> 		dual_print ($log, file_text_line({ string => "	 done in ".(time() - $previous_time)." seconds", char => "-" }), $verbose );
> 		$check_cpt++; $previous_time = time();
> 	}
> ```
> 
> from the OmniscientI.pm code .
> 
> Or just comment
> 
> ```
> _check_identical_isoforms($log, \%omniscient, \%mRNAGeneLink, $verbose);
> ```
> 
> and recompile the code. We might try to find an easy way to avoid some tests like that but it will not be in a near future.

Thank you, Jaques! I will do that! 
Looking forward to seeing it as an option in the future!
