### ISSUE TITLE
Help file

### ISSUE THREAD

**Issue by PacoZm** [NBISweden/AGAT#255]
**Describe the bug**
When I use this tool, or any other from AGAT, agat_convert_sp_gxf2gxf.pl -g in.gff [ -o outfile ], instead of creating the outfile, it opens the hellp file.

**General (please complete the following information):**
- AGAT version v0.9.1
- AGAT installation/use Manual, windows powerShell

**Comment by Juke34** [comment]
In tool description the  element within square brackets `[ ]` means this is optional.
So you should run either: 

`agat_convert_sp_gxf2gxf.pl -g in.gff `

or 
`agat_convert_sp_gxf2gxf.pl -g in.gff -o result.gtf`

**Comment by PacoZm** [comment]
Yes, I did that, but it keeps opening the help file, instead of running the tool.

**Comment by Juke34** [comment]
Then try with long flag:
`agat_convert_sp_gxf2gxf.pl --gff in.gff -o result.gtf`

**Comment by PacoZm** [comment]
I copied exactly what you sent me, and it continues to open the Help file in the note pad.
Missing any authorization or prerequisite.
I also tried agat_convert_sp_gxf2gxf.pl --gff in.gff --output result.gff

**Comment by Juke34** [comment]
Could you copy past you command and copy past the output please?

**Comment by PacoZm** [comment]
I tried gmake test /gmake install and you're right, looks like it didn't work right.
I have been trying to understand why this happened, I really appreciate your help
[error.txt](https://github.com/NBISweden/AGAT/files/8763259/error.txt)
.

**Comment by Juke34** [comment]
gmake test does not work on windows apprently because I use a bash command "diff" that does not exist. It does not mean that the installation does not work, but I'm not certain AGAT will work properly. Either use a unix VM and install AGAT on it, or simplest use directly the AGAT docker container.

**Comment by Juke34** [comment]
Please feel free to re-open the issue if you still need help for this issue.
