### ISSUE TITLE
SO Ontologies and term specifications

### ISSUE THREAD

**Issue by sanyalab** [NBISweden/AGAT#259]
Hi Jacques,

I wanted to know whether AGAT ships with the latest SO-Ontology which is SO-Ontologies release 3.1. Reason I ask is because I am trying to use the agat merge annotations script and I keep getting errors for features that I mentioned as standalone. OR that are related to items in feature1.jsonHere is an example

In features_level1.json file I mention the following
  `"pif_harbinger_tir_transposon":"standalone",`
  `"hAT_tir_transposon":"standalone",`
  `"mutator_tir_transposon":"standalone",`
  `"cacta_tir_transposon":"standalone",`
  `"Tc1_mariner_tir_transposon":"standalone",`

In features_level2.json file I mention the following
`        "ltr/copia":"repeat_region",`
`        "Copia_LTR_retrotransposon":"repeat_region",`
`        "Gypsy_LTR_retrotransposon":"repeat_region",`
`        "LTR_retrotransposon":"repeat_region",`
`        "target_site_duplication":"repeat_region",`
`        "long_terminal_repeat":"repeat_region",`

But I am still getting the error

`INFO - Feature types not expected by the GFF3 specification:`
`* cacta_tir_transposon`
`* copia_ltr_retrotransposon`
`* gypsy_ltr_retrotransposon`
`* hat_tir_transposon`
`* mutator_tir_transposon`
`* pif_harbinger_tir_transposon`
`* tc1_mariner_tir_transposon`

What is the correct method to specify these identifiers?

Thanks
Abhijit

**Comment by Juke34** [comment]
It is not an error ot is just information to tell you that these terms are not among the SO specified but AGAT will deal with them if specified in the json files.
The SO shipped with AGAT is a bit olf: https://github.com/NBISweden/AGAT/blob/master/share/so.obo
You can specify the URL to another SO version using the header `##feature-ontology URL`  in the header of your file

**Comment by Juke34** [comment]
This warning is just to inform if we follow strictly the GFF3 specification of not.
Few line below AGAT tell you about the features it cannot deal with, If all feature types are handled by AGAT and you do not get the expected result then, i) The features json file are not set properly (what you are thinking currenlty, but sounds good to me); ii) the command you use is not adapted.

Could you tell me which AGAT script you use and the exact command, as well as the AGAT version. If you can provide samples of the 3 GFFs you want to merge and the result you would expect compare to what you actually have, it would be great.

**Comment by anfarr** [comment]
> It is not an error it is just information to tell you that these terms are not among the SO specified, but AGAT will deal with them if delared properly in the json files. The SO shipped with AGAT is a bit olf: https://github.com/NBISweden/AGAT/blob/master/share/so.obo You can specify the URL to another SO version using the header `##feature-ontology URL` in the header of your file

Not sure whether to open a new issue but since it was mentioned here.
I am using the latest singularity image file `agat_0.9.1--pl5321hdfd78af_0.sif`
When specifying the feature-ontology URL in the gff3 file `agat_convert_sp_gff2gtf.pl` shows an error:
```
 24 => Machine information:
 25     This script is being run by perl v5.32.1
 26     Bioperl location being used: /usr/local/lib/perl5/site_perl/Bio/
 27     Operating system being used: linux
 28 => Accessing Ontology
 29     feature-ontology URI defined within the file: https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/Ontology_Files/so.obo
 30 501 Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)   No ontology accessible from the gff file header!
 31     We use the SOFA ontology distributed with AGAT:
 32         /usr/local/lib/perl5/site_perl/auto/share/dist/AGAT/so.obo
 33     Read ontology /usr/local/lib/perl5/site_perl/auto/share/dist/AGAT/so.obo:
 34         4 root terms, and 2472 total terms, and 1436 leaf terms
  ```
 I guess LWP::Protocol::https is missing in the sif.

**Comment by oushujun** [comment]
I found my recent issue (#263) is a duplication of this one. I added following the ontology line in the gff3 file:
`##feature-ontology https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/Ontology_Files/so.obo`

And run:
`agat_convert_sp_gff2gtf.pl --gff test2.gff3 -o test2.gtf --relax`

[test2.gff3.zip](https://github.com/NBISweden/AGAT/files/8969954/test2.gff3.zip)


Then have this error:
```
converting to GTF3
********************************************************************************
*                              - Start parsing -                               *
********************************************************************************
-------------------------- parse options and metadata --------------------------
=> Accessing the feature level json files
	Using standard /home/sou6/bin/miniconda3/envs/modbamtools/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_level1.json file
	Using standard /home/sou6/bin/miniconda3/envs/modbamtools/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_level2.json file
	Using standard /home/sou6/bin/miniconda3/envs/modbamtools/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_level3.json file
	Using standard /home/sou6/bin/miniconda3/envs/modbamtools/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_spread.json file
=> Attribute used to group features when no Parent/ID relationship exists:
	* locus_tag
	* gene_id
=> merge_loci option deactivated
=> Accessing Ontology
	feature-ontology URI defined within the file: https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/Ontology_Files/so.obo
Strings with code points over 0xFF may not be mapped into in-memory file handles
Cannot read the string: Invalid argument :: 0	feature-ontology parsed correctly
	Filtering ontology:
Can't call method "isa" on an undefined value at /home/sou6/bin/miniconda3/envs/modbamtools/lib/site_perl/5.26.2/Bio/Ontology/OBOEngine.pm line 989.
```

Is this the right way to do it?

Thanks,
Shujun

**Comment by Juke34** [comment]
This is fixed in last version of AGAT. But it will not change anything to the parsing. The ontology is just to check if the feature type you use are in line with specification. The fact that AGAT handles the features is set up via the feature level json files.
