### ISSUE TITLE
Convert Rfam cmscan result to gtf?

### ISSUE THREAD

**Issue by ld9866** [NBISweden/AGAT#262]
Thank you for developing such good software!
We now want to convert our Rfam results into a gtf format as part of the annotation, and combine gtf results.
I would like to ask if there is any way to use software conversion?
Thank you very much for your reply!

**Comment by Juke34** [comment]
Hi, no such converter within AGAT. We might implement one. When using Rfam I use https://github.com/NBISweden/GAAS/blob/master/bin/gaas_rfam2grid.pl from GAAS repository. You might have a look how the conversion is done there. You can probably find a rfam converter looking around on the net.

**Comment by ld9866** [comment]
Thank you!
Thank you for your prompt reply, I will test it next.
Best yours,
