### ISSUE TITLE
Remove redundancy from gtf file (agat_sp_keep_longest_isoform.pl)

### ISSUE THREAD

**Issue by marco91sol** [NBISweden/AGAT#265]
**Is your feature request related to a problem? Please describe.**
I have an annotation file. I'd like to remove redundancy as shown in the image below. In this case, I am sending you partial file, where 2 genes have several common exons (same location), and some other with different location. I tried the tool "keep_longest_isoform.pl", with no result. 

![image](https://user-images.githubusercontent.com/42739946/174303010-a209a5da-5e84-4255-a24f-b7f01228038b.png)

An idea, could be to keep only the longest isoform. Hence, in this case keeping only the file_1_file_1_jg18738.t1 gene.

How can I solve it?

Thanks for the support!

**Comment by Juke34** [comment]
Your file describe 2 different genes: `file_1_file_1_jg18738` and `file_1_file_2_42380_g`.
Isoform is when you have only one gene and several isoforms (transcript or mRNA).
What you can do is to run the `gxf2gxf` script with --merge_loci to merge this 2 genes in only one with isoforms. This will only merge gene that have overlapping CDS in the same direction.

**Comment by Juke34** [comment]
Please feel free to re-open the issue if you still need help for this issue.
