### ISSUE TITLE
agat_sp_keep_longest_isoform.pl --gff not keeping the longest transcript isoform

### ISSUE THREAD

**Issue by luciazifcakova** [NBISweden/AGAT#266]
I have used agat_sp_keep_longest_isoform.pl --gff hg19.refGene.gff (created by agat_convert_sp_gxf2gxf.pl -g hg19.refGene.gtf -o hg19.refGene.gff) to find the longest transcript isoforms on hg19 chr10.

Sadly, this script does not find the longest isoforms all the time.

Here is the short list of isoforms I got with your script:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/lucia/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/lucia/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

chr10 | 92828 | 95178 | -2350 | 2350 | - | ID=NM_177987;Parent=TUBB8;gene_id=TUBB8;gene_name=TUBB8;transcript_id=NM_177987
-- | -- | -- | -- | -- | -- | --
chr10 | 180424 | 300411 | 119987 | 119987 | + | ID=NM_006624;Parent=ZMYND11;gene_id=ZMYND11;gene_name=ZMYND11;transcript_id=NM_006624

</body>

</html>

 vs R Bioconductor reduce function:
txdb2 <- makeTxDbFromGFF("/UCSC2020/hg19.refGene.gtf", format="gtf")
seqlevels(txdb2) <- "chr10"
GR <- transcripts(txdb2)
reducedGR_chr10 <- reduce(GR, ignore.strand = T)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/lucia/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/lucia/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

  | seqnames | start | end | width | strand
-- | -- | -- | -- | -- | --
1 | chr10 | 92828 | 95178 | 2351 | *
2 | chr10 | 176028 | 300411 | 124384 | *

</body>

</html>

As you can see the isoform found by R is longer and it is legit one - check the original hg19.refGene.gtf file here:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/lucia/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/lucia/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

chr10 | refGene | transcript | 176028 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id   "NM_001370103";  gene_name   "ZMYND11";
-- | -- | -- | -- | -- | -- | -- | -- | --
chr10 | refGene | transcript | 180233 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370104";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180233 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NR_163254";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180424 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_006624";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180424 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370105";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180424 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370118";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180424 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370119";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180740 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001330057";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180740 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370106";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180740 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001202465";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180740 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370097";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180740 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001202466";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180740 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370124";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180740 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370098";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180740 | 295729 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_212479";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180740 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370107";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180740 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370113";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180740 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370115";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180740 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370116";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180740 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370120";  gene_name "ZMYND11";
chr10 | refGene | transcript | 180740 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370122";  gene_name "ZMYND11";
chr10 | refGene | transcript | 181205 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370108";  gene_name "ZMYND11";
chr10 | refGene | transcript | 181205 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370111";  gene_name "ZMYND11";
chr10 | refGene | transcript | 181205 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370110";  gene_name "ZMYND11";
chr10 | refGene | transcript | 181205 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370114";  gene_name "ZMYND11";
chr10 | refGene | transcript | 181205 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370099";  gene_name "ZMYND11";
chr10 | refGene | transcript | 181395 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001202464";  gene_name "ZMYND11";
chr10 | refGene | transcript | 181395 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370100";  gene_name "ZMYND11";
chr10 | refGene | transcript | 181395 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370112";  gene_name "ZMYND11";
chr10 | refGene | transcript | 181395 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370117";  gene_name "ZMYND11";
chr10 | refGene | transcript | 181395 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370121";  gene_name "ZMYND11";
chr10 | refGene | transcript | 181395 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370123";  gene_name "ZMYND11";
chr10 | refGene | transcript | 181538 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370101";  gene_name "ZMYND11";
chr10 | refGene | transcript | 181749 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370102";  gene_name "ZMYND11";
chr10 | refGene | transcript | 181749 | 300411 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001370109";  gene_name "ZMYND11";
chr10 | refGene | transcript | 225934 | 295729 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001202468";  gene_name "ZMYND11";
chr10 | refGene | transcript | 225934 | 295729 | . | + | . | gene_id "ZMYND11"; transcript_id "NM_001202467";  gene_name "ZMYND11";

</body>

</html>

I have used singularity run agat_0.8.0--pl5262hdfd78af_0.sif.

**Comment by Juke34** [comment]
Hi,
I'm not sure to understand, you say you would expect several longest isoforms for ZMYND11 because they are several to be the same size? did you check the CDS size? it cannot be seen from the data you provide.
Did you read the help carrefully?
```
The script aims to filter isoforms when present. For a locus:
- when all isoforms have CDS we keep the one with the longest CDS.
- when some isoforms have CDS some others not, we keep the one with the longest CDS.
- when none of the isoforms have CDS, we keep the one with the longest concatenated exons. 
```

I could add for extreme case that when several isoforms are the longest we kept only one randomly (but I do not think this is you case).

**Comment by luciazifcakova** [comment]
I am sorry, I have misunderstood how is-forms are selected. I thought that longest one is selected by the length in bp. In that case, your script is working as it is supposed to.
