### ISSUE TITLE
gff2gtf has the first line merged into the last annotation line 

### ISSUE THREAD

**Issue by oushujun** [NBISweden/AGAT#267]
Hello,

I am converting a gff3 file to gtf format and found the first annotation line of the converted file is merged into the last annotation line (started with `#`). Can you please check? 

This is the command I used (Version: v0.8.0 installed via conda):
`agat_convert_sp_gff2gtf.pl --gff test.gff3 -o test.gtf --relax`

This is a sample file to reproduce the issue.
[test.gff3.zip](https://github.com/NBISweden/AGAT/files/8969648/test.gff3.zip)

Thank you,
Shujun

**Comment by Juke34** [comment]
Thank you for your feedback, indeed a new line is missing.
