### ISSUE TITLE
bed2gff: add cds with thickStart/thickEnd

### ISSUE THREAD

**Issue by rsalz** [NBISweden/AGAT#268]
I have a bed12 file that contains all transcripts, with thickStart and thickEnd denoting positions where CDS starts and ends. Right now you have to specify your biotype (in my case it would be mRNA) and then you get a gff file with just those mRNA and exons defined, without CDS info. 

I would like to be able to also have the CDS in the output gff file if thickStart and thickEnd are specified. 
Bonus: it would be extra great if you could add genes to the gff file too. they can be not real and have arbitrary IDs, but just for completeness/compatibility with other tools. I'm also happy to supply another (gff/gtf) file that contains gene information as a sort of complement.

Right now the status quo is using UCSC bedToGenePred and then UCSC genePredToGtf. Then the resulting GTF doesn't include gene attributes. Would be nice if i could do this conversion directly with your tool, since you already offer a bed to gff conversion function...

**Comment by Juke34** [comment]
I don't get your problem, by default:
```
scaffold625	337817	343277	CLUHART00000008717	0	+	337914	343033	255,0,0	4	154,109,111,1314	0,2915,3700,4146
```
gives
```
##gff-version 3
scaffold625	data	gene	337818	343277	.	+	.	ID=1;Name=CLUHART00000008717;blockCount=4;blockSizes=154%2C109%2C111%2C1314;blockStarts=0%2C2915%2C3700%2C4146;itemRgb=255%2C0%2C0;thickEnd=343033;thickStart=337914
scaffold625	data	exon	337818	337971	.	+	.	ID=exon1;Parent=1
scaffold625	data	exon	340733	340841	.	+	.	ID=exon2;Parent=1
scaffold625	data	exon	341518	341628	.	+	.	ID=exon3;Parent=1
scaffold625	data	exon	341964	343277	.	+	.	ID=exon4;Parent=1
scaffold625	data	CDS	337915	337971	.	+	0	ID=CDS1;Parent=1
scaffold625	data	CDS	340733	340841	.	+	0	ID=CDS2;Parent=1
scaffold625	data	CDS	341518	341628	.	+	2	ID=CDS3;Parent=1
scaffold625	data	CDS	341964	343033	.	+	2	ID=CDS4;Parent=1
scaffold625	data	five_prime_UTR	337818	337914	.	+	.	ID=five_prime_UTR1;Parent=1
scaffold625	data	three_prime_UTR	343034	343277	.	+	.	ID=three_prime_UTR1;Parent=1
```
CDS are drawn from  thickStart and thickEnd information.

I guess if the CDS is missing either the problem is the command line, or something in the file (missing thickStart thickEnd values?)
