### ISSUE TITLE
Issues with agat_sp_keep_longest_isoform.pl

### ISSUE THREAD

**Issue by filonico** [NBISweden/AGAT#269]
Dear Jacques,

I'm using the script `agat_sp_keep_longest_isoform.pl` (v.0.8.0 from a conda installation in Ubuntu) on the genome annotation of the mussel _Mytilus galloprovincialis_ from NCBI (you can download the gff file from [here](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/900/618/805/GCA_900618805.1_MGAL_10/)). However, I'm facing some issues, since it seems that agat succeeds in **removing some isoforms** (the raw count of predicted proteins drops from 78,735 to 74,575 after the filtering) **but not all of them** (busco score of duplicated genes is 32.8% before the filtering and 30.1% after).

For example, if you look at the gene `MGAL_10B075785` in the gff file, you will find that it should encode for 6 different isoforms (from `VDI47525.1` to `VDI47530.1`), since they share both the `Parent` and the `locus_tag`. However, after running the aforementioned script, all the six isoforms (or at least some exons of them) are retained. Clearly, I suspect that similar situations are occurring also in other genes for this specific genome assembly (in other genomes AGAT is working greatly).

Can this be a problem of the annotation file itself? Maybe some mistakes or a wrong format?

Thank a lot!

**Comment by filonico** [comment]
Thank you very much for your quick response.

So now I'm wondering if I actually understood well how `agat_sp_keep_longest_isoform.pl` actually works. Say we have the mRNA in the picture below and the corresponding 3 encoded isoforms, according to the gff file.

Now, AGAT would retain "isoform 1" (which is actually the longest) or would create a "new longest-isoform" composed of CDS1, 2, 3 and 4? 
![image](https://user-images.githubusercontent.com/72141380/177552708-9d18b7be-141a-4697-8b98-3d6d68bf45cf.png)

**Comment by filonico** [comment]
Yeah sure, you are right! Clearly the mRNA should be a gene (or even better the pre-mRNA, as you said)... I should go back to basics of molecular biology, I guess 🥲

Thanks a lot!!

**Comment by Juke34** [comment]
Could you modify the drawing and remove the "new longest isoform by agat", I'm afraid it can be confusing for other users. They often don't read and just look at the pictures
