### ISSUE TITLE
GenScan converter

### ISSUE THREAD

**Issue by nimarafati** [NBISweden/AGAT#27]
Hi,

This is to request for developing/adding script to AGAT to conver GenScan prediction to gff/gtf.

Thanks!
Nima

**Comment by Juke34** [comment]
Could you provide a sample/test file?

**Comment by nimarafati** [comment]
Sure!
I am attaching two files:
- GenScan_rc_213196-225412.txt; Annotation sample
- A perl script that I had written three years ago which converts GenScan output to bed. 
Cheers,
Nima
[GenScan_rc_213196-225412.txt](https://github.com/NBISweden/AGAT/files/4283755/GenScan_rc_213196-225412.txt)

[Genscan2-bed-V1.pl.txt](https://github.com/NBISweden/AGAT/files/4283759/Genscan2-bed-V1.pl.txt)
