### ISSUE TITLE
agat_sp_complement_annotations.pl resulted annotation with missing genes from file1?

### ISSUE THREAD

**Issue by zmz1988** [NBISweden/AGAT#274]
**Describe the bug**
Hello, I ran into something that I don't really understand with the results of `agat_sp_complement_annotations.pl` and `agat_sp_compare_two_annotations.pl`, and hope you could help me figure it out.

I have two annotations, one is the PASA pipeline gff3 output, and one is the liftoff output from lifting a reference annotation. I used `agat_sp_complement_annotations.pl` to add genes from liftoff output to PASA pipeline gff3 output, hoping to keep all the genes from PASA output and meanwhile also adding missing genes from the reference. After the complement function, I used `agat_sp_compare_two_annotations.pl` to compare the complemented annotation with the PASA gff3 output. 

From what I understand on the two agat functions, I was hoping to see that all the genes from PASA gff3 output will be in the complemented output. But actually I found around 3000 genes are not in the complemented output. 

So may I ask in what situation `agat_sp_complement_annotations.pl` does not include the genes to the output file? In the whole report, I only see that agat filter out some identical isoforms.

Also, there are many genes that are fused in the complemented output (those many==>1, I guess? ). May I ask how does agat decide to fuse the genes?

So I'm very confused here. Could you please help me out? Code and the table are below. Thanks a lot!

```
agat_sp_complement_annotations.pl --ref mydb_sqlite.gene_structures_post_PASA_updates.121933.gff3 --add liftoff/liftoff.gff3_polished --out pasa_liftoff.gff3

agat_sp_compare_two_annotations.pl -gff1 mydb_sqlite.gene_structures_post_PASA_updates.121933.gff3 -gff2 pasa_liftoff.gff3 -o pasaRound2_vs_pasaLiftoff &> agat_compare.log

#result of the compare
----------------------------------------------------------------------------------------------
|                                       gene with mrna                                       |
----------------------------------------------------------------------------------------------
| mydb_sqlite.gene_structure |    pasa_liftoff   |        Number of cases       |
----------------------------------------------------------------------------------------------
|              0               |              1               |            10244             |
|              1               |              0               |             3007             |
|              1               |              1               |            20359             |
|              1               |              2               |              18              |
|              2               |              0               |              280             |
|              2               |              1               |              496             |
|              2               |              2               |              245             |
|              3               |              0               |              14              |
#(omit other lines from here)
```

**Comment by Juke34** [comment]
1) `agat_sp_complement_annotations.pl --ref mydb_sqlite.gene_structures_post_PASA_updates.121933.gff3 --add liftoff/liftoff.gff3_polished --out pasa_liftoff.gff3` should indeed keep all genes from the PASA output. If it is not the case the result from `agat_convert_sp_gxf2gxf.pl` will show you how the PASA file is processed before to be complemented with the liftoff output.

2) Unfortunalty the `agat_sp_compare_two_annotations.pl` is not reliable see #216 . I must rewrite it. Please do not take in consideration its result.

3) Fuse the gene is currently possible only with  `agat_convert_sp_gxf2gxf.pl` using the option `--merge_loci`. It will fuse genes with same level2  feature type (e.g. tRNA with tRNA but not tRNA with mRNA) i) when they have CDS, only if CDS overlap, ii) when they do not have CDS when exons overlap. In a future release it would be possible to activate deactivate this option for almost all scripts.

**Comment by zmz1988** [comment]
Thanks! That's helpful to know!
