### ISSUE TITLE
Retain all isoforms, skip isoform duplicates from agat_sp_merge tool

### ISSUE THREAD

**Issue by callumparr** [NBISweden/AGAT#275]
Is there a way to turn off the check to remove identical isoforms when running the merge two annotations? 

Currently, it removing a few isoform from gencode which I believe to be not the same juding by cooridnates being different. They tend to be simpolistic mono exonic non coding genes that differ in start and/or end or transcription but I would like to retain them. 

```
---------------------- Check12: remove identical isoforms ----------------------
Lets remove isoform ENST00000692538.1
Lets remove isoform ENST00000688558.1
Lets remove isoform ENST00000688925.1
Lets remove isoform ENST00000693217.1
Lets remove isoform ENST00000693036.1
Lets remove isoform ENST00000690852.1
Lets remove isoform ENST00000690185.1
Lets remove isoform ENST00000689303.1
```
some exampe from top three 
```
chr1    HAVANA  transcript      116417359       116418622       .       -       .       gene_id "ENSG00000203865.12"; transcript_id "ENST00000688925.1"; gene_type "lncRNA"; gene_name "ATP1A1-AS1"; transcript>
chr1    HAVANA  exon    116417359       116418622       .       -       .       gene_id "ENSG00000203865.12"; transcript_id "ENST00000688925.1"; gene_type "lncRNA"; gene_name "ATP1A1-AS1"; transcript_type "l>
chr12   HAVANA  transcript      123364924       123365808       .       +       .       gene_id "ENSG00000256092.3"; transcript_id "ENST00000692538.1"; gene_type "lncRNA"; gene_name "SBNO1-AS1"; transcript_t>
chr12   HAVANA  exon    123364924       123365808       .       +       .       gene_id "ENSG00000256092.3"; transcript_id "ENST00000692538.1"; gene_type "lncRNA"; gene_name "SBNO1-AS1"; transcript_type "lnc>
chr12   HAVANA  transcript      123364948       123365789       .       +       .       gene_id "ENSG00000256092.3"; transcript_id "ENST00000688558.1"; gene_type "lncRNA"; gene_name "SBNO1-AS1"; transcript_t>
chr12   HAVANA  exon    123364948       123365789       .       +       .       gene_id "ENSG00000256092.3"; transcript_id "ENST00000688558.1"; gene_type "lncRNA"; gene_name "SBNO1-AS1"; transcript_type "ln
```

**Comment by Juke34** [comment]
In a future release it will be possible to deactivate the "remove identical isoform" step.

> Currently, it removing a few isoform from gencode which I believe to be not the same juding by cooridnates being different. They tend to be simpolistic mono exonic non coding genes that differ in start and/or end or transcription but I would like to retain them.

To be identical the isoforms must have the same level1 feature (e.g. the same gene), the same level2 feature type (e.g. both must be mRNA in the 3rd column) and have the same coordinate, if they have exons the exons must have the same coordinates, and if there are CDS the CDS must have the same coordinates.
When you have the message `Lets remove isoform ENST00000688925.1` it means the gene `ENSG00000203865.12` has another `transcript` with coordinates `116417359       116418622`. You may check within the file. I don' remember but maybe the information of the isoform kept is hold in the log file.

**Comment by callumparr** [comment]
Ah cool thank you it wasn't so many so perhaps can merge them back in manually.

**Comment by plattsad** [comment]
Maybe I can extend this request to agat_convert_sp_gxf2gxf.pl where an option not to remove identical isoforms would be helpful.  When fixing minor issues in Maker annotation output, removing isoforms makes the gff inconsistent with various other output files such as the protein and mRNA output files.

**Comment by Juke34** [comment]
AGAT removes the isoforms only if they are 100% identical. Anyway if you want to avoid that, you can deactivate the appropriate parameter in the AGAT conf file available since AGAT v1.0.0

**Comment by plattsad** [comment]
> AGAT removes the isoforms only if they are 100% identical. 

Thanks for the pointer wrt the conf file - I'll see where conda has put these.   But yeh - Maker will create isoforms that are 100% identical but give them different eAED scores.  Deleting them seems sensible until you get feedback from collaborators that some transcripts in the transcript file aren't in the gff.

**Comment by Juke34** [comment]
Oh right, thank you for pointing it, I didn't think about the eAED score. But they shouldn't be of similar score as they are covering exactly the same locations?

**Comment by pclavell** [comment]
Is the removal of identical isoforms disabling option already implemented?
I am working with a gtf where redundancy has been removed by collapsing all isoforms with the same intron chain but AGAT is removing 49 identical isoforms. Then I went to IGV and it is actually removing stuff that is not identical.
eg:
AGAT is finding the top isoform to be identical to some other (the only other model in the region is the one at the bottom) and they are clearly different. 
![image](https://github.com/user-attachments/assets/196eb17a-4bad-4adb-82c6-48d1e7a299bc)

**Comment by Juke34** [comment]
If it is the it would be a bug. What tool did you use? Could you share the sample containing these genes ?  
If you wish to deactivate the step of isoforms removing run: agat config —expose and modify the Boolean of the corresponding line to false.

**Comment by pclavell** [comment]
Is it a merge made by Cerberus of the results of FLAIR, IsoQuant, Lyric and ESPRESSO, but both of these models are generated by IsoQuant v3.4.1
Sadly I can not share the sample.

> chrY	cerberus transcript  	1190492 1212723 .   	-   	.   	gene_id "ENSG00000292363"; transcript_id "transcript_380661"; ID "transcript_380661"; Parent "ENSG00000292363"; gene_name "ENSG00000292363"; 
> chrY	cerberus exon	1190492 1191160 .   	-   	.   	gene_id "ENSG00000292363"; transcript_id "transcript_380661"; ID "agat-exon-1963698"; Parent "transcript_380661"; exon_number "8.0"; gene_name "ENSG00000292363"; 
> chrY	cerberus exon	1193218 1193302 .   	-   	.   	gene_id "ENSG00000292363"; transcript_id "transcript_380661"; ID "agat-exon-1963697"; Parent "transcript_380661"; exon_number "7.0"; gene_name "ENSG00000292363"; 
> chrY	cerberus exon	1196780 1196900 .   	-   	.   	gene_id "ENSG00000292363"; transcript_id "transcript_380661"; ID "agat-exon-1963696"; Parent "transcript_380661"; exon_number "6.0"; gene_name "ENSG00000292363"; 
> chrY	cerberus exon	1198801 1199145 .   	-   	.   	gene_id "ENSG00000292363"; transcript_id "transcript_380661"; ID "agat-exon-1963695"; Parent "transcript_380661"; exon_number "5.0"; gene_name "ENSG00000292363"; 
> chrY	cerberus exon	1202402 1202535 .   	-   	.   	gene_id "ENSG00000292363"; transcript_id "transcript_380661"; ID "agat-exon-1963694"; Parent "transcript_380661"; exon_number "4.0"; gene_name "ENSG00000292363"; 
> chrY	cerberus exon	1206433 1206599 .   	-   	.   	gene_id "ENSG00000292363"; transcript_id "transcript_380661"; ID "agat-exon-1963693"; Parent "transcript_380661"; exon_number "3.0"; gene_name "ENSG00000292363";
> chrY	cerberus exon	1208806 1208905 .   	-   	.   	gene_id "ENSG00000292363"; transcript_id "transcript_380661"; ID "agat-exon-1963692"; Parent "transcript_380661"; exon_number "2.0"; gene_name "ENSG00000292363"; 
> chrY	cerberus exon	1212556 1212723 .   	-   	.   	gene_id "ENSG00000292363"; transcript_id "transcript_380661"; ID "agat-exon-1963691"; Parent "transcript_380661"; exon_number "1.0"; gene_name "ENSG00000292363"; 
> 
> 
> chrY	cerberus transcript  	1190490 1212649 .   	-   	.   	transcript_id "transcript_380662"; gene_id "ENSG00000292363"; gene_name "ENSG00000292363";
> chrY	cerberus exon	1212556 1212649 .   	-   	.   	transcript_id "transcript_380662"; exon_number "1.0"; gene_id "ENSG00000292363"; gene_name "ENSG00000292363";
> chrY	cerberus exon	1208806 1208908 .   	-   	.   	transcript_id "transcript_380662"; exon_number "2.0"; gene_id "ENSG00000292363"; gene_name "ENSG00000292363";
> chrY	cerberus exon	1206433 1206599 .   	-   	.   	transcript_id "transcript_380662"; exon_number "3.0"; gene_id "ENSG00000292363"; gene_name "ENSG00000292363";
> chrY	cerberus exon	1202402 1202535 .   	-   	.   	transcript_id "transcript_380662"; exon_number "4.0"; gene_id "ENSG00000292363"; gene_name "ENSG00000292363";
> chrY	cerberus exon	1198562 1198724 .   	-   	.   	transcript_id "transcript_380662"; exon_number "5.0"; gene_id "ENSG00000292363"; gene_name "ENSG00000292363";
> chrY	cerberus exon	1196780 1196900 .   	-   	.   	transcript_id "transcript_380662"; exon_number "6.0"; gene_id "ENSG00000292363"; gene_name "ENSG00000292363";
> chrY	cerberus exon	1193218 1193302 .   	-   	.   	transcript_id "transcript_380662"; exon_number "7.0"; gene_id "ENSG00000292363"; gene_name "ENSG00000292363";
> chrY	cerberus exon	1190490 1191160 .   	-   	.   	transcript_id "transcript_380662"; exon_number "8.0"; gene_id "ENSG00000292363"; gene_name "ENSG00000292363";

**Comment by Juke34** [comment]
Using these two transcript as input for  agat_convert_sp_gxf2gxf.pl in AGAT v1.4 I get:
```
 chrY   AGAT    gene    1190490 1212723 .       -       .       ID=ENSG00000292363;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380661
 chrY   cerberus        transcript      1190490 1212649 .       -       .       ID=transcript_380662;Parent=ENSG00000292363;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380662
 chrY   cerberus        exon    1190490 1191160 .       -       .       ID=agat-exon-8;Parent=transcript_380662;exon_number=8.0;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380662
 chrY   cerberus        exon    1193218 1193302 .       -       .       ID=agat-exon-7;Parent=transcript_380662;exon_number=7.0;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380662
 chrY   cerberus        exon    1196780 1196900 .       -       .       ID=agat-exon-6;Parent=transcript_380662;exon_number=6.0;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380662
 chrY   cerberus        exon    1198562 1198724 .       -       .       ID=agat-exon-5;Parent=transcript_380662;exon_number=5.0;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380662
 chrY   cerberus        exon    1202402 1202535 .       -       .       ID=agat-exon-4;Parent=transcript_380662;exon_number=4.0;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380662
 chrY   cerberus        exon    1206433 1206599 .       -       .       ID=agat-exon-3;Parent=transcript_380662;exon_number=3.0;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380662
 chrY   cerberus        exon    1208806 1208908 .       -       .       ID=agat-exon-2;Parent=transcript_380662;exon_number=2.0;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380662
 chrY   cerberus        exon    1212556 1212649 .       -       .       ID=agat-exon-1;Parent=transcript_380662;exon_number=1.0;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380662
 chrY   cerberus        transcript      1190492 1212723 .       -       .       ID=transcript_380661, ;Parent=ENSG00000292363;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380661
 chrY   cerberus        exon    1190492 1191160 .       -       .       ID=agat-exon-1963698, ;Parent=transcript_380661;exon_number=8.0;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380661
 chrY   cerberus        exon    1193218 1193302 .       -       .       ID=agat-exon-1963697, ;Parent=transcript_380661;exon_number=7.0;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380661
 chrY   cerberus        exon    1196780 1196900 .       -       .       ID=agat-exon-1963696, ;Parent=transcript_380661;exon_number=6.0;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380661
 chrY   cerberus        exon    1198801 1199145 .       -       .       ID=agat-exon-1963695, ;Parent=transcript_380661;exon_number=5.0;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380661
 chrY   cerberus        exon    1202402 1202535 .       -       .       ID=agat-exon-1963694, ;Parent=transcript_380661;exon_number=4.0;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380661
 chrY   cerberus        exon    1206433 1206599 .       -       .       ID=agat-exon-1963693;Parent=transcript_380661;exon_number=3.0;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380661
 chrY   cerberus        exon    1208806 1208905 .       -       .       ID=agat-exon-1963692, ;Parent=transcript_380661;exon_number=2.0;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380661
 chrY   cerberus        exon    1212556 1212723 .       -       .       ID=agat-exon-1963691, ;Parent=transcript_380661;exon_number=1.0;gene_id=ENSG00000292363;gene_name=ENSG00000292363;transcript_id=transcript_380661
```
So I do not see any error

**Comment by pclavell** [comment]
I have no idea what is happening. Anyway in the end we had to do some tweaks due to other issues we were having unrelated to this.
Just out of curiosity, is the gene entry expected to include the transcript_id of one of the genes' transcripts?
Thanks!

**Comment by Juke34** [comment]
> Just out of curiosity, is the gene entry expected to include the transcript_id of one of the genes' transcripts?

In certain cases yes. When the gene is missing in the input file and is created by AGAT (you can see this case because the 2nd column contains the tool that created the feature and it will be written AGAT i.e the case above) because it use the transcript feature as template to create the gene feature. But this is a good catch. I would remove the transcript_id in such case!

**Comment by Juke34** [comment]
I have updated the code to avoid the transcript_id in the gene feature see https://github.com/NBISweden/AGAT/commit/64702ffc997b6692e21ce4bdb02e602c92dff55b
