### ISSUE TITLE
Problem with editing json files

### ISSUE THREAD

**Issue by EthanKhew** [NBISweden/AGAT#276]
Hi, I am a beginner in bioinformatics. 
I am analyzing a set of RNA-Seq data focusing on small open reading frames (sORF) expression. To look for unannotated ones, I used READemption and ANNOgesic to produce a list of predicted sORF [file = annogesic.bpd286_nutrientbhibrept1_sORF.txt]. Then, I would like to map my RNA-Seq data to the predicted sORF file which requires me to feed a .gtf file during STAR genome-indexing step. Here, I am faced with a few issues: 

1. The feature (third column) for this file are all "sORF" and I have failed numerous times in troubleshooting the json files. I followed the troubleshoot instruction as guided by the documentation but I guess there's something that I am not doing right. What I have tried so far is merging (by cat in terminal) bpd286.genomic.ncbi.gff with annogesic.bpd286_nutrientbhibrept1_sORF.gff and then using (agat_convert_sp_gxf2gxf.pl) to fix any issues. But only the contents of the bpd286.genomic.ncbi.gff are present, and in duplicates of other levels, whereas contents of the latter file are absent/discarded.  I have also tried playing around with sed to change the feature column from "sORF" to "gene", but to no avail as well. 

2. The ID_attribute (9th column) of annogesic.bpd286_nutrientbhibrept1_sORF.gff lacks "parent_id", "gene_id", and "locus_tag". Trials with (agat_sq_add_locus_tag.pl) resulted in an empty file even after efforts in editing the json files. 

3. Is there a way where I could add "parent_id" and/or "gene_id" to my annogesic.bpd286_nutrientbhibrept1_sORF.gff file so that I could make it convert-compatible from gff-to-gtf??

4. A side issue is that I have downloaded and followed the steps in updating to the latest agat version, changing into a specific version of agat (v0.9.2) but no matter what I tried, the version output is still v0.8.0

A detailed guide in how to edit the json files would be very much appreciated by a newbie in bioinformatics. Thanks in advance

- AGAT version [v0.8.0]
- AGAT installation/use [bioconda/conda activate agatenv]
- OS: [Linux 22.04]

[bpd286.genomic.ncbi.txt](https://github.com/NBISweden/AGAT/files/9351343/bpd286.genomic.ncbi.txt)
[annogesic.bpd286_nutrientbhibrept1_sORF.txt](https://github.com/NBISweden/AGAT/files/9351346/annogesic.bpd286_nutrientbhibrept1_sORF.txt)
[sed_3rdcolumn_annogesic.bpd286_nutrientbhibrept1_sORF.txt](https://github.com/NBISweden/AGAT/files/9351347/sed_3rdcolumn_annogesic.bpd286_nutrientbhibrept1_sORF.txt)

**Comment by Juke34** [comment]
Hi, thank you for using AGAT.
1) parsing the sORF data gives 
```
=> Number of feature type (3rd column): 1
	* Level1: 0 => 
	* level2: 0 => 
	* level3: 0 => 
	* unknown: 1 => sORF
=> Version of the Bioperl GFF parser selected by AGAT: 3
gff3 reader warning: primary_tag error @ sorf still not taken into account! Please modify the json files to define the feature in one of the levels.
```
So you are right you need to modify the json file.
a) expose the json file: `agat_convert_sp_gxf2gxf.pl --expose`
b) Modify the level1 and add the line `"sort":"standalone",`

2 & 3) Run `agat_convert_sp_gff2gtf.pl` will add the `gene_id` attribute automatically (you need to use the `relax` option because `sorf` is not an accepted attribute in GTF)

4) Did you try to install the latest version of AGAT with conda: `conda install agat=0.9.2`

**Comment by EthanKhew** [comment]
Hi Jacques, thanks for taking the time to respond to me and apologies for the late reply. I have been unwell for the past few days. 

I see the mistake with what I was doing wrong now. The "sORF" tag of my .gff file are with large characters whereas editing the feature_level1.json file do not need to be character specific. Hence, your modification using `"sorf":"standalone",` worked instead of  `"sORF":"standalone",` that I was using and trying in all other feature_level$.json files. 
Your suggestion/solution helped me to proceed with my next step. 

Regarding issue 4., I have tried as suggested by you but I got back an "unjustifiable/unsatisfiable error" in my terminal. Should I delete my agat conda environment, uninstall my current AGAT version, and then try your suggestion again?

**Comment by Juke34** [comment]
> Regarding issue 4., I have tried as suggested by you but I got back an "unjustifiable/unsatisfiable error" in my terminal. Should I delete my agat conda environment, uninstall my current AGAT version, and then try your suggestion again?

Did you set the channel properly? If not try `conda install -c bioconda agat=0.9.2`
Otherwise create a new env `conda create -c bioconda -n agatnewenv agat` and then activate this new env `conda activate agatnewenv `
