### ISSUE TITLE
Modification of agat_sp_compare_two_annotations.pl for additional insights on reference annotation

### ISSUE THREAD

**Issue by sanyalab** [NBISweden/AGAT#280]
Hi Jacques,

I was wondering if the agat_sp_compare_two_annotations.pl script (or any other more suitable script) can be tweaked to get the following metrics

1) Fraction of reference.gff3 splice sites that exactly match the query.gff3 splice sites
2) Fraction of exons in the reference.gff3 file that exactly match the query.gff3 exons
3) Fraction of exons in the reference.gff3 file that overlap with exons in the query.gff3

The query.gff3 can either be an annotation or an mRNA/protein alignment in gff3 format. I use the F1 metric to compare a reference gene annotation to query. But I wanted some additional indicators. Can this be done? 

Thanks
Abhijit

**Comment by Juke34** [comment]
Hi, yes this type of thing could be developed but I unfortunately I currently do not have time to develop new AGAT features. I was working on  a version 1 of AGAT. I was also re-writing the `agat_sp_compare_two_annotations.pl` script which is currently bugged. I will see if I can add such task easily on the way, I will do it.

**Comment by sanyalab** [comment]
Sweet. Thanks Jacques

**Comment by sanyalab** [comment]
Hi Jacques,

I had a question regarding agat_sp_sensitivity_specificity.pl. Adding it here since this is along the lines of compare_annotations. If you compare the reference annotation of a gene model to all the evidence GFF3's that go on to create that gene model/add support to it, then does the sensitivity_specificity.pl script take into account the volume of the evidence? In other words, does the the exon sensitivity and specificity score an additive normalized score of the comparisons of each evidence with the reference gene model annotation?

Thanks
Abhijit

**Comment by Juke34** [comment]
Hi, the answer is `no`,  it does not take into account the volume evidence.

**Comment by sanyalab** [comment]
So the Sn and Sp values that are generated is an average of all the Sn and Sp values generated by comparing each alignment to the reference gene model?
