### ISSUE TITLE
agat_sp_split_by_level2_feature.pl: No such file or directory

### ISSUE THREAD

**Issue by Olivier144** [NBISweden/AGAT#281]
Hi all,

I have successfully installed AGAT via conda
I am trying to use it  as described here: https://www.biostars.org/p/394385/

However, I got this error message:
-bash: ~/.conda/envs/agat/bin/agat_sp_split_by_level2_feature.pl: No such file or directory

When I looked at it, I noticed two things:
Firstly,  in ~/.conda/envs/agat/bin/ there is no agat_sp_split_by_level2_feature.pl., however there is agat_sp_split.pl instead.
Secondly, all .pl files (as shown in the attached file) have "sq", not "sp" as it is in the above workflow (I mean here https://www.biostars.org/p/394385/)

Could you help me to solve the issue, kindly? I will appreciate your feedback.

<img width="661" alt="agat" src="https://user-images.githubusercontent.com/41971234/192156398-281164ea-2cd8-468d-8f70-ec012a68167d.png">

**Comment by Juke34** [comment]
The answer is here: #279 
Thnak you for the feedback I will update the biostar post.
