### ISSUE TITLE
gene set filter/selection for training ab initio annotation in AGAT

### ISSUE THREAD

**Issue by Olivier144** [NBISweden/AGAT#282]
Hi everyone,

I am trying to follow the procedure described here https://www.biostars.org/p/394385/ as preliminary steps in AGAT before ab initio training.

I plan to train Augustus in Braker or Busco. However, I will need the output in fasta format. Unfortunately, step 5 in the workflow (https://www.biostars.org/p/394385/) outputs is in gff format.

Any idea on how to do that? I will appreciate it.

**Comment by Juke34** [comment]
I don't get why you want the fasta format (I added an answer in Biostar how to get the fasta). If you read carefully the augustus intructions you will see that from the gff file you will have to prepare a genebank file will a augustus convenient script:
```
 gff2gbSmallDNA.pl gff_file genome_fasta out.gbk
```
then you split your data into training part and testing part
```
randomSplit.pl out.gbk testSize
```
Then you follow the training steps e.g.:  
```
 new_species.pl --species=$species_label
 etraining --species=$species_label $training_file
 augustus --species=$species_label $test_file | tee ${species_label}_run.log
```
