### ISSUE TITLE
gff3 reader warning: primary_tag error @ expressed_sequence_match still not taken into account!    Please modify the json files to define the feature in one of the levels.

### ISSUE THREAD

**Issue by Olivier144** [NBISweden/AGAT#283]
Hi guys,

I am using AGAT (agat_sp_separate_by_record_type.pl) to get coding genes from a genome annotation file. The process still ongoing, however, I got these warnings:

gff3 reader warning: primary_tag error @ expressed_sequence_match still not taken into account!   
 Please modify the json files to define the feature in one of the levels.

Is this normal?

**Comment by Juke34** [comment]
This featue is trown by AGAT because not known. You can add it manually see:
https://agat.readthedocs.io/en/latest/troubleshooting.html#agat-throws-features-out-because-the-feature-type-is-not-yet-taken-into-account

You must check in your file if the feature is child of another one or if it has children (look at links made with Parent/ID attributes) in order to add it properly.

**Comment by Olivier144** [comment]
Hi Juke,

I looked into my ggf file and found multiple IDs looking like the one below:
tigxxxx     maker   mRNA    340    40000  2351   -       .       ID=maker-tixxxx-exonerate_est2genome-gene-0.0-mRNA-2;Parent=maker-tixxxx-exonerate_est2genome-gene-0.0;Name=maker-tigxxxx-exonerate_est2genome-gene-0.0-mRNA-2;_AED=0.25;_eAED=0.25;_QI=70|1|1|1|0|0|2|140|51

I do not know how to identify the IDs of the features that were not taken into account.
I am wondering whether there is a way to extract all the features that were thrown out, with their their nature/type if possible?

**Comment by Juke34** [comment]
To see all features of type `expressed_sequence_match` in your file the best is t use awk.
`awk '{if($3=="expressed_sequence_match") print $0}' file.gff`

**Comment by Olivier144** [comment]
Thank you Juke for your help.

I exctrated all the features that were thrown out. 
They look like this:


tigxxxxxxx     cdna2genome     expressed_sequence_match        1000000   111000  301     +
       .       ID=tigxxxxxxx:hit:1023010:1.4.0.0;Name=vsearch_derep222%2Bsize%2Q1



There are a dozen of different IDs like the above, each with replicates. Regardless of the IDs, all the features are expressed_sequence_match.
In column 9 of the annotation file, the attributes of each of the ID are either Name=TRINITY_DN... or Name=vsearch_derep.....

My questions are, based on those ID attributes, how to tell whether  if that feature is child of another one or if it has children?
After knowing which feature level I should add that information to, and based on the explanation above, how to deal with this part of the procedure:

adding a paired-value like this:

	"bigRNA":"gene",
Where bigRNAis the feature type and gene the parent feature type expected. /!\ For level1 feature type the second value can be:

topfeature: feature does not expect children, and will be written first in the sequence

standalone: feature does not expect children

other values do not have any meaning but a value is required, write whatever you want.

**Comment by Juke34** [comment]
It's all about ID/Parent relationship. If you see an other feature type that has as `Parent` value the `ID` value of a `expressed_sequence_match` then this feature is a child of `expressed_sequence_match`. Usually when it comes to `match` feature types (like in your case), `match` is a level1 feature and you will have `match_part` child features that are level2 feature.
If you share few lines of your gff file around a `expressed_sequence_match` it should be easy to understand.

**Comment by Olivier144** [comment]
Thank you Juke.

I have added the below lines to Feature level1:
"contig":"region"
"expressed_sequence_match":"match"

 Agat is running now without any issues. I will update of the the outcomes.

**Comment by Juke34** [comment]
Did you add it at level1 or level2?

**Comment by Olivier144** [comment]
I added it to level1. I considered contig as regions.

And downstream processing of the resulting .gff into gbk. gives me the followoing warning. I am wondering if this will be an issue later on:


Have mRNA and UTR for gene maker-tigxxxxx-exonerate_protein2genome-gene-11.zzz-mRNA-1 in sequence tigxxxx. Ignoring UTR annotation and using mRNA annotation only.
Suppressing this error message from now on.
Warning: Had redundant UTR exon information for 100 genes.

**Comment by Juke34** [comment]
This sounds ok.
AGAT deflates information even if redundant to be sure to be conpliant with all tools. It means if the same exon is used for different isoforms, the exon feature will be present in the GFF for all the mRNA it is part of. Non-deflated GFF will tend to write the feature only once, and write in the Parent attribute the list of mRNA it is part of. But some tools are confused with that and do not deal properly with multiple parent features. EMBL and GenBank format does not like redundant information and will tends to remove those.

BTW I will release AGAT v1.0.0 that will contain `contig` and `expressed_sequence_match` features by default.
