### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by kathryncrouch** [NBISweden/AGAT#284]
**Describe the bug**
On [this](https://agat.readthedocs.io/en/latest/gff_to_gtf.html) page in the documentation, there is a link to a "complete review" of GFF and GTF formats. This link is broken. The current target for this link is: https://github.com/NBISweden/GAAS/blob/master/annotation/knowledge/gxf

I can see that the Markdown for this page is still in the repo. It would be great if you could fix this link - it's a great reference for those new to these formats!

**Comment by Juke34** [comment]
Thank you for pointing it. I will link it to the page present in the doc: https://agat.readthedocs.io/en/latest/gxf.html
