### ISSUE TITLE
agat_sp_compare_two_annotations.pl and agat_sp_complement_annotations.pl

### ISSUE THREAD

**Issue by EthanKhew** [NBISweden/AGAT#289]
Hi.

I am interested in looking for duplicate and unique genes from 2 separately predicted gff files (coculture and infection). Then I want to add unique genes from the second file (infection) into the first file (coculture). I found that both `agat_sp_compare_two_annotations.pl` and `agat_sp_complement_annotations.pl` will do the trick just fine based on the documentation. The files below were created chronologically and full script is found in the 5th file (_compared.coculture.infection.dataset.bpd286annogesic2.txt_)

The script `agat_sp_compare_two_annotations.pl` work as expected and is attached below (compared.coculture.infection.dataset.bpd286annogesic2.txt). I would like to get more information on which sequences are unique or found as duplicated between these two files. Is there a way for me to do so other than the `-v; verbose` option because there are too many lines and they would be flushed up to the top of the terminal quickly. 

The script `agat_sp_complement_annotations.pl` did not work as expected where none of the non-overlapping genes from file 2 were added to the first file. The output complement file is the same as my first input gff file. What should I do/manipulate to make the files merge the non-overlapping genes from -addfiles into the -referencefile?
**_P.S. The **complement.pl script** requires input files to possess gene_id or locus_tag, hence were converted (`agat_convert_sp_gxf2gxf.pl`) and then added locus_tag (`agat_sq_add_locus_tag.pl`) to make the script executable._**

In reference to closed issue #276, I had no luck in trying to update my AGAT version from 0.8.0 to 0.9.2 as suggested. Hence, my software version are as below. 

    AGAT version [v0.8.0]
    AGAT installation/use [bioconda/conda activate agatenv]
    OS: [Linux 22.04]

[coculture_dataset_bpd286.genomic.ncbi_sORF2.txt](https://github.com/NBISweden/AGAT/files/9783506/coculture_dataset_bpd286.genomic.ncbi_sORF2.txt)
[infection_dataset_bpd286.genomic.ncbi_sORF2.txt](https://github.com/NBISweden/AGAT/files/9783508/infection_dataset_bpd286.genomic.ncbi_sORF2.txt)
[coculturedataset_bpd286.genomic.ncbi_sORF.agatconverted.addedlocustag2.txt](https://github.com/NBISweden/AGAT/files/9783745/coculturedataset_bpd286.genomic.ncbi_sORF.agatconverted.addedlocustag2.txt)
[infectiondataset_bpd286.genomic.ncbi_sORF.agatconverted.addedlocustag2.txt](https://github.com/NBISweden/AGAT/files/9783520/infectiondataset_bpd286.genomic.ncbi_sORF.agatconverted.addedlocustag2.txt)
[compared.coculture.infection.dataset.bpd286annogesic2.txt](https://github.com/NBISweden/AGAT/files/9783737/compared.coculture.infection.dataset.bpd286annogesic2.txt)
[complement.coculture.infection.dataset.bpd286annogesic2.txt](https://github.com/NBISweden/AGAT/files/9783523/complement.coculture.infection.dataset.bpd286annogesic2.txt)

**Comment by Juke34** [comment]
Not easy to perform...I would follow those steps:
1) replace sORF in your files by CDS: `sed 's/	sORF	/	CDS	/' file.gff > file_cds.gff`
2) Add exon mRNA, gene feature by executing this command (the ID wll be use to group the features by locus and as you have only single exon gene locus, each ID correspond to a locus): `agat_convert_sp_gxf2gxf.pl --gff file_cds.gff --ct ID -o file_standardized.gff`
3) Update the second column to reflect the file used e.g. `ANNOgesic_file1` using an awk command: `awk '{$2="ANNOgesic_file1"; print $0}' file_standardized.gff > file_standardized_flagged.gff`
3) Use `agat_sp_complement_annotations.pl`  to add non-overlaping genes from a file to the other. `command -o resulting_file.gff`
4) Now look into the resulting file the genes that has been added filter by the flag of the second column `awk '{if ($2=="ANNOgesic_file1") print $0}' resulting_file.gff `

**Comment by EthanKhew** [comment]
Hi @Juke34 

You guide worked superbly well. However, I did made a few changes with the `sed` step that you have provided above. I swapped it with `awk` and then sorting by tabs with `sed` again. The rest of the steps worked and went through smoothly. 
Overall, I highly recommend your guide to others that face a similar situation like mine which is largely caused by the feature attribute (3rd column) of the gff file. Thanks so much.

**Comment by EthanKhew** [comment]
Hi @Juke34 

I have updated to the latest AGAT version1.2 using ``` conda update agat ``` but weirdly it is showing version1.0.0 when i check for the program's version in the terminal. I went through the program releases update and issue #306 and the ```--ct``` option has been replaced with editing the ```config.yaml``` file now. I want to perform the same task as you've guided previously in the replies from this post but my tries have been unsuccessful. Could you please guide me on which line and how to modify the ```config.yaml``` file to enable the ```agat_convert_sp_gxf2gxf.pl``` to achieve what I want? 


The input file is attached below. The output file that I am interested to generate is the one that has all four levels as you've guided previously (example attached below). Thank you 

>##gff-version 3
NZ_CP025307.1	bed2gff	gene	23464	23663	.	+	.	ID=nbis-gene-364
NZ_CP025307.1	bed2gff	mRNA	23464	23663	.	+	.	ID=nbisL2-cds-364;Parent=nbis-gene-364
NZ_CP025307.1	bed2gff	exon	23464	23663	.	+	.	ID=nbis-exon-295;Parent=nbisL2-cds-364
NZ_CP025307.1	bed2gff	CDS	23464	23663	.	+	.	ID=cds-364;Parent=nbisL2-cds-364
NZ_CP025307.1	bed2gff	gene	50503	50741	.	+	.	ID=nbis-gene-259
NZ_CP025307.1	bed2gff	mRNA	50503	50741	.	+	.	ID=nbisL2-cds-259;Parent=nbis-gene-259
NZ_CP025307.1	bed2gff	exon	50503	50741	.	+	.	ID=nbis-exon-178;Parent=nbisL2-cds-259
NZ_CP025307.1	bed2gff	CDS	50503	50741	.	+	.	ID=cds-259;Parent=nbisL2-cds-259


[D286gff.txt](https://github.com/NBISweden/AGAT/files/12463598/D286gff.txt)

**Comment by Juke34** [comment]
When using Conda, the best way to check the version is to run `Conda listant check manually the version installed.

**Comment by Juke34** [comment]
Run `agat config --expose` and modify the config as follow:

```
locus_tag:
  - locus_tag
  - gene_id
 ```

by 

```
locus_tag:
  - ID
 ```

**Comment by Juke34** [comment]
I do not see any attribute in the file (9th field), it only contains `.;`, so changing locus_tag parameter is useless.

**Comment by EthanKhew** [comment]
Yes, this file is different. Before this, your suggested method worked under version0.8.0. Now it doesn't seem to work under version1.0.0. Should I add attribute information to the 9th column using the ``` agat_sq_add_attributes_from_tsv.pl ``` function?

**Comment by Juke34** [comment]
Is each line supposed to be an exon from a different locus?

**Comment by EthanKhew** [comment]
Okay. I'll try it out and then let you know tomorrow how it goes.

**Comment by EthanKhew** [comment]
Hi @Juke34 

Your ``` awk ``` suggestion worked! Thank you very much. 
One last thing, is there a way to configure the ``` config.yaml ``` file to deposit ```.log ``` files to a specific directory?

**Comment by Juke34** [comment]
Currently it is not possible to decide where to write le log. You have to move it manually after the AGAT run.
