### ISSUE TITLE
strange gff causing gene number to double

### ISSUE THREAD

**Issue by sjfleck** [NBISweden/AGAT#290]
thank you for this useful tool. I've used it many times and it's been a great help. I often need to edit the input genome fasta or annotation gff to fix an error when converting a gff to a gff3 or extracting proteins, etc. since I'm usually working with publicly available genomes that are all annotated in different ways. This annotation is a bit different from what I'm used to seeing.

but here's an example of one gene from the annotation I'm working with:
# start RCORA115751
```
scaf_7	ERGO	gene	32269822	32270187	.	+	.	ID=RCORA115751
scaf_7	ERGO	mRNA	32269822	32270187	.	+	.	ID=RCORA115752;Parent=RCORA115751
scaf_7	ERGO	CDS	32269822	32270184	.	+	.	ID=RCORA115753;Parent=RCORA115751
```
# end RCORA115751

when I convert this into a gff3, it nearly doubles the number of genes from 47,210 to 93,337. I'm not exactly sure why this is happening besides the strange IDs. When I convert this segment, it becomes:
```
scaf_7	ERGO	gene	32269822	32270184	.	+	.	ID=nbis-gene-5348
scaf_7	ERGO	mRNA	32269822	32270184	.	+	.	ID=RCORA115751;Parent=nbis-gene-5348
scaf_7	ERGO	exon	32269822	32270184	.	+	.	ID=nbis-exon-22194;Parent=RCORA115751
scaf_7	ERGO	CDS	32269822	32270184	.	+	.	ID=RCORA115753;Parent=RCORA115751
scaf_7	ERGO	gene	32269822	32270187	.	+	.	ID=RCORA115751
scaf_7	ERGO	mRNA	32269822	32270187	.	+	.	ID=RCORA115752;Parent=RCORA115751
```

In this example, 1 gene became 2 and this is a consistent pattern. Can AGAT help with this issue? It looks like the ID's and parents would all need renaming and I'm not aware of a tool that would do this.

I could probably get around the issue by using this strange annotation as a reference in GeMoMa to re-annotate this same genome, but I'd like toalso know if AGAT can help. Thank you

**Comment by Juke34** [comment]
What is the version you are using?

**Comment by sjfleck** [comment]
I've been using AGAT v0.8.0. I must have been using an old script because I also have AGAT v0.9.1

**Comment by Juke34** [comment]
Is the problem still here with AGAT v0.9.1?

**Comment by sjfleck** [comment]
the problem is still there with v0.9.1. I always check the gene and mRNA number before and after a conversion. I just have it printed to an info.txt file. 

gff:
number of genes:
47210
number of mRNA:
48523

gff3:
number of genes:
93337
number of mRNA:
93444

It might also be worth mentioning that this is already a gff3 file, it's just not like other's I've used as mentioned in my previous comment. this is at the top of the gff file (I replaced the # with % so the formatting doesn't change):

%%gff-version 3
% This output was generated by ERGO(tm) by Igenbio, Inc.
% Genome Collinsia rattanii
% start RCORA108540
PGA_scaffold_4__128_contigs__length_56907126	ERGO	gene	28926557	28930105	.	-	.	ID=RCORA108540

as a test, I've "reformatted" a gff3 into a gff3 using AGAT and the gene doubling issue didn't happen. Also, when I extract proteins and run BUSCO, it doesn't give suspicious results like a high number of duplicated BUSCOs (it's only around 3.5%). I want to use this genome along with others and my genomes in OrthoFinder, CoGe, and MCScan for example. I just want to be confident that this gff3 is reliable to extract proteins and cds from. I'll attach the out file in case that's useful in any way. 
[AGAT-0.9.1.gxf2gxf.extract_sequences.Collinsia_rattanii-A.txt](https://github.com/NBISweden/AGAT/files/9846749/AGAT-0.9.1.gxf2gxf.extract_sequences.Collinsia_rattanii-A.txt)
[AGAT-0.9.1.gxf2gxf.extract_sequences.Collinsia_rattanii-B.txt](https://github.com/NBISweden/AGAT/files/9846750/AGAT-0.9.1.gxf2gxf.extract_sequences.Collinsia_rattanii-B.txt)

**Comment by sjfleck** [comment]
I want to give an update. Since I wasn't having luck with the current annotation, I tried re-annotating the genome with GeMoMa using the original _Collinsia rattanii_ annotation as the only reference. When I try it with the original gff3, only 20 gene models are created. When I try it with the gene-doubled gff3 version created with AGAT, only 24 gene models created. I'll reach out to the GeMoMa folks about this, but this annotation is different from any I've worked with before

**Comment by Juke34** [comment]
Could you give a try to the lastest AGAT version (v1.0.0). I might have fixed the issue.

**Comment by sjfleck** [comment]
I tried AGAT-v1.0.0 and got the same result. This was my command:
conda activate agat-1.0.0
agat_convert_sp_gxf2gxf.pl -g $GENOME.annotation.gff -o $GENOME.annotation.gff3

If you were interested in looking at this annotation for yourself, it can be downloaded from:
https://gsajournals.figshare.com/articles/online_resource/Supplemental_Material_for_Frazee_et_al_2021/14599995

I work with a lot of published genomes and this one is the most different gff3 format that I've seen so far

**Comment by Juke34** [comment]
This is the `FileS2_CORA.gff` annotation file right? 

```
PGA_scaffold_4__128_contigs__length_56907126	ERGO	gene	28931358	28932486	.	-	.	ID=RCORA108545
PGA_scaffold_4__128_contigs__length_56907126	ERGO	mRNA	28931358	28932486	.	-	.	ID=RCORA108546;Parent=RCORA108545
PGA_scaffold_4__128_contigs__length_56907126	ERGO	CDS	28931361	28931705	.	-	.	ID=RCORA108549;Parent=RCORA108545
PGA_scaffold_4__128_contigs__length_56907126	ERGO	CDS	28931819	28932031	.	-	.	ID=RCORA108549;Parent=RCORA108545
PGA_scaffold_4__128_contigs__length_56907126	ERGO	CDS	28932137	28932273	.	-	.	ID=RCORA108549;Parent=RCORA108545
PGA_scaffold_4__128_contigs__length_56907126	ERGO	CDS	28932393	28932486	.	-	.	ID=RCORA108549;Parent=RCORA108545
```
Their annotation is so wrong.... they have attached level3 features (exons CDS) directly to the gene, while it exists an mRNA feature. Two solutions... 
1) Remove all mRNA with a `awk` command then run `agat_convert_sp_gxf2gxf.pl`
2) Remove Parent attributes with `agat_sq_manage_attributes.pl` and then run `agat_convert_sp_gxf2gxf.pl`

I will see if I can do something in the AGAT parser to deal with this particular case
