### ISSUE TITLE
agat_sp_functional_statistics.pl output is not a file as described in documentation

### ISSUE THREAD

**Issue by toniher** [NBISweden/AGAT#297]
According to: https://agat.readthedocs.io/en/latest/tools/agat_sp_functional_statistics.html

`agat_sp_functional_statistics.pl --gff genome.gff3 -o file.txt` should generate a report as `file.txt`, however a directory named file.txt is created with a `report.txt` inside.

Tested in last 1.0.0 version.

**Comment by Juke34** [comment]
Thank you for the feedback, it will be corrected.
