### ISSUE TITLE
Can agat convert a gff to bed format and retain thickStart and thickEnd of non coding RNAs

### ISSUE THREAD

**Issue by loukesio** [NBISweden/AGAT#301]
I am using agat atm to convert a `gff` file to `bed` using the following command. 

```
agat_convert_sp_gff2bed.pl -gff Arabidopsis_thaliana_TAIR10.gff3  -o test.bed
``` 
When I convert the `gff` to `bed` I find NA values (aka `.`) in the thickStart and thickEnd column of the bed file for the non-coding RNAs. 
Is there a way to convert `gff` to `bed` and acquire a  thickStart and thickEnd values for these elements?

Thank you for your time  
In the link, I post the gff3 file that I am working on https://drive.google.com/drive/folders/1-wmbc9gKtbXFJ95E0n41WgPL-G313SNe?usp=sharing

**Comment by Juke34** [comment]
thickStart and thickEnd are usulally used to define coding part (CDS), which does not exist for non-coding genes. What do you think would be a correct value in this case?

**Comment by loukesio** [comment]
Dear Juke, 

Thank you so much for the prompt reply. I highly appreciate it. 
In the following picture I would fill thickStart and thickEnd with chromStart and chromEnd?
What do you think?


<img width="696" alt="Screenshot 2022-11-14 at 13 55 42" src="https://user-images.githubusercontent.com/13181494/201702911-63e39429-b31c-49b8-8acf-c5695b7eec9f.png">
