### ISSUE TITLE
the Script ‘agat_convert_sp_gxf2gxf.pl’ has no the parameter '--ct',but the docs showed the '--ct'

### ISSUE THREAD

**Issue by z626093820** [NBISweden/AGAT#306]
![image](https://user-images.githubusercontent.com/37371455/204780200-13541a00-232e-4c78-b642-dff565947868.png)
could you help me? thank you!

**Comment by Juke34** [comment]
Hi,
Right since v1.0.0 AGAT uses a config file.
```
agat config --expose
```
Then add the common tag you want at the proper field in the config.yaml file.

**Comment by z626093820** [comment]
![image](https://user-images.githubusercontent.com/37371455/204783863-385a2250-a1ff-42fd-baa4-fc358ca21820.png)
if i want to slove above problem about 'feature type missing and no Parent/gene_id',how can i change the below config file? i am not clear. thank you !
![image](https://user-images.githubusercontent.com/37371455/204784188-74063a08-4a1a-433f-a881-6688ed96436a.png)

**Comment by z626093820** [comment]
![image](https://user-images.githubusercontent.com/37371455/204784848-210d8e25-16e7-49bf-9df0-01c853e11df1.png)
this is my gff3 file,thank you !

**Comment by Juke34** [comment]
It sounds that this type of file does not clear feature to group several mRNA under a unique gene.
In your case you can use the common_tag/locus_tag parameter (I need to update the help to unify te use of those terms) Name:
```
locus_tag:
   - locus_tag
   - gene_id
   - Name
```
Despite the warning it should work

**Comment by z626093820** [comment]
thank you! i will try

**Comment by z626093820** [comment]
yes,the Ibat.Brg.01A_G000020 is the parent of Ibat.Brg.01A_G000020.1 and Ibat.Brg.01A_G000020.3,but the gff file has not the parent Ibat.Brg.01A_G000020,so i want to add Ibat.Brg.01A_G000020.
thank you ! i will try!

**Comment by z626093820** [comment]
Hello, I have another question, this script ‘agat_convert_sp_gxf2gxf.pl’  merges a part of the CDS and UTR located on different positive and negative chains, is this correct？Is it not necessary to consider positive and negative chains? i do not clear. THANK YOU!
![image](https://user-images.githubusercontent.com/37371455/204976199-8fd41996-0c3d-4164-897c-3c427a2675b5.png)

**Comment by Juke34** [comment]
Hmm, when applying this merging step AGAT works only transcript by transcript, it means that within a single transcript there are subfeatures (CDS and UTR) with a mix of strand. This is not supposed to happen (mix of strand within a transcript), so maybe the previous step didn't operate as expected.
