### ISSUE TITLE
agat_sp_keep_longest_isoform.pl can't open gff file

### ISSUE THREAD

**Issue by b524198065** [NBISweden/AGAT#31]
Hi,

I was trying to use agat_sp_keep_longest_isoform.pl script to extract the longest transcript in each gene model saving in a GFF3 format file using following command:

agat_sp_keep_longest_isoform.pl --gff gy14_maker10.all.ipr_update.standard_filter.gff3

But the script returned an error with output:
Reading file 2
Can't open $file_path": No such file or directory

What's wrong with my command? I installed AGAT through conda by conda install -c bioconda agat
I'm sure the GFF3 file I passed to the script is exactly here
-rw-rw-r--. 1  79M Mar 13 11:43 gy14_maker10.all.ipr_update.standard_filter.gff3
here is a snapshot of the GFF3 file
![1](https://user-images.githubusercontent.com/39608290/76606282-f32db400-654c-11ea-8201-39e1fbd7d384.png)

Thanks

**Comment by b524198065** [comment]
Sorry about the typo, the error output should be:

Reading file gy14_maker10.all.ipr_update.standard_filter.gff3
Can't open $file_path": No such file or directory

**Comment by Juke34** [comment]
could you do a `ls -l` bash command and confirm you file `gy14_maker10.all.ipr_update.standard_filter.gff3
` is in your working folder?

**Comment by b524198065** [comment]
> could you do a `ls -l` bash command and confirm you file `gy14_maker10.all.ipr_update.standard_filter.gff3 ` is in your working folder?

Yes, and I copy the script to my working directory and it didn't work either.
![2](https://user-images.githubusercontent.com/39608290/76607016-36d4ed80-654e-11ea-9a8c-d71ac8a9520e.png)

**Comment by b524198065** [comment]
![2](https://user-images.githubusercontent.com/39608290/76607127-65eb5f00-654e-11ea-9f43-6ed2b0002b26.png)

**Comment by Juke34** [comment]
Ok the message actually says the tool tries to read a file called `2`could you check your command line? and be sure to write 
`agat_sp_keep_longest_isoform.pl --gff gy14_maker10.all.ipr_update.standard_filter.gff3`

**Comment by b524198065** [comment]
Well, I'm sorry I made a typo in the issue description, here is the screenshot of the error.
![11](https://user-images.githubusercontent.com/39608290/76607762-7b14bd80-654f-11ea-8233-e65c61009d09.png)

**Comment by Juke34** [comment]
Ok I see, I will update the error message.
The tool cannot access JSON files that suppose to come during the installation.
Are you sure to have activated the correct conda environment? remove the local agat script and try `agat_` with autocompletion to see if all the script are suggested

**Comment by b524198065** [comment]
Yes, it returned all the agat scripts. I also activated conda enviromment  by "conda init bash", but the error still occured.
![3](https://user-images.githubusercontent.com/39608290/76611377-5d4a5700-6555-11ea-810b-87a8437ae948.png)

**Comment by Juke34** [comment]
what return the command:  `which agat_convert_bed2gff.pl` ?

**Comment by b524198065** [comment]
it is in the conda intstallation directory, so I think the install of AGAT should be OK.
![1123](https://user-images.githubusercontent.com/39608290/76614580-53c3ed80-655b-11ea-8527-439292fc2ab6.png)

**Comment by Juke34** [comment]
You could try to reinstall manually to see if any error message pop up (still in the agat conda env to be sure prerequisite are already installed):
```
git clone https://github.com/NBISweden/AGAT.git # Clone AGAT
cd AGAT                                         # move into AGAT folder
perl Makefile.PL                           # Check all the dependencies*
make                                            # Compile
make test                                      # Test
make install                                    # Install
```

If the problem still persists then it is the same issue as #4 

There is a way to bypass the problem. The tool check first in the local folder if the json files are present, and use those one in priority. So just copy past the json files from `AGAT/share/` folder locally.

**Comment by b524198065** [comment]
Thanks, that really worked! But the program requires me to move a serious of json files into /share directory, which confused me . Are there any choices to put these files elsewhere? The /share directory is actually not a private one on this server.

**Comment by Juke34** [comment]
I tried on miniconda2 on linux and it works fine for me (default installation).
I don't get why in your installation (was the same for #4) perl is looking the `share` folder at the root of the computer `/share` while it is suppose to look in the conda env location something like `/home/[user]/[conda]/envs/[agat_environement]/lib/site_perl/[5.26.2]/auto/share/dist/AGAT/`.

Good you found your way.
The fix for now in your case is either to copy yourself the files from AGAT/share into `/share` folder, or into the working directory.
Otherwise update/change conda installation.

**Comment by b524198065** [comment]
Yeah, anyway, thanks for your help!
