### ISSUE TITLE
"Prerequisite JSON 0 not found"

### ISSUE THREAD

**Issue by kbipinkumar** [NBISweden/AGAT#312]
**Describe the bug**
Hi i am trying to compile AGAT for Archlinux. while trying to create makefile i am able to fulfill all dependencies except for one as shown below
```
Warning: prerequisite JSON 0 not found.
Generating a Unix-style Makefile
Writing Makefile for AGAT
Writing MYMETA.yml and MYMETA.json
```
**General (please complete the following information):**
- AGAT version (1.0.0]
- AGAT installation/use [github source]
- OS: [Archlinux]

**Additional context**
i have installed perl-yaml perl-yaml-libyaml  packages in archlinux that are equivalent to libyaml-perl  ubuntu (as set of packages refer to same upstream URL [https://metacpan.org/dist/YAML-LibYAML](https://metacpan.org/dist/YAML-LibYAML))

any pointers on how the issue can be resolved.

**Comment by Juke34** [comment]
I forgot to remove JSON from the Makefile.PL
Try removing https://github.com/NBISweden/AGAT/blob/e39b239988f65434a869127ee4f5a1c823810f06/Makefile.PL#L51

**Comment by kbipinkumar** [comment]
Okay, that worked. thanks for the help
