### ISSUE TITLE
Make test 

### ISSUE THREAD

**Issue by kbipinkumar** [NBISweden/AGAT#313]
**Describe the bug**
```make test``` step exits Result: FAIL error
**General (please complete the following information):**
- AGAT version (e.g. v1.0.0]
- AGAT installation/use [Github source]
- OS: [Archlinux]
- perl version: 5.36

**To Reproduce**
`run make` test command

**Additional context**
please see attached link to see the output of ```make test``` command 

https://gist.github.com/kbipinkumar/d799da9d1dade08792d9460cd18011c2

i have installed all the required dependencies. 

can these errors be ignored or am i doing something wrong

**Comment by Juke34** [comment]
Sounds like a dependency is missing

**Comment by kbipinkumar** [comment]
> Sounds like a dependency is missing

but i do not get any missing dependency message when i run `perl Makefile.PL`

**Comment by Juke34** [comment]
I maybe forgot to mention one, or the dependencies didn't install to the proper perl version...
Could you give me the error message when you run a script?

**Comment by Juke34** [comment]
Feel free to re-open this issue if you still need help.
