### ISSUE TITLE
WARNING: Problem ! no sequence extracted for - <seq_id> ! (agat_sp_extract_sequences.pl)

### ISSUE THREAD

**Issue by FrancescoGarassino** [NBISweden/AGAT#316]
Hello,

I've succesfully been using agat_sp_extract_sequences.pl to extract protein sequences from gff + fasta files. As long as I worked with nuclear genomes, I had no issues. However, now I'm working with a collection of chloroplast and mitochondrion assemblies downloaded from NCBI and for a number of those I get this warning while running agat_sp_extract_sequences.pl:

`WARNING: Problem ! no sequence extracted for - <seq_id> ! (agat_sp_extract_sequences.pl)`

Specs:
- AGAT v1.0.0]
- AGAT installed and running with mamba 1.0.0 (running conda 22.9.0)
- OS: Ubuntu 18.04.6

The exact command I'm running is:
`agat_sp_extract_sequences.pl -g NC_049891.1_Brassica_rapa_subsp_rapa_chloroplast.gff3 -f NC_049891.1_Brassica_rapa_subsp_rapa_chloroplast.fasta -p --cis --cfs -o test_chl.fa`

I'm uploading the input files as well: [input_files.zip](https://github.com/NBISweden/AGAT/files/10236195/input_files.zip)

Thanks a lot in advance for your help!

**Comment by Juke34** [comment]
Right your fasta sequence is 155815 bases long and you ask to extract position  start:222435 end:222536 so it is why it warn you. I will improve the warning message.

**Comment by FrancescoGarassino** [comment]
Thanks a lot for the explanation and for taking action on this! And for this great toolbox as well :)
