### ISSUE TITLE
GTF/GFF 5' & 3' UTR

### ISSUE THREAD

**Issue by aabaricalla** [NBISweden/AGAT#317]
The 'agat_sp_statistics.pl' doesn't recognize the AUGUSTUS GTF/GFF annotations of 3' and 5' UTR.+

AGAT expects "five_prime_utr" and "three_prime_utr" in these explicit forms to count these features, but in the case of AUGUSTUS or BRAKER or TSEBRA the annotation usually is "5'-utr" or "3'-utr".

I think this could be a nice enhancement.

**Comment by Juke34** [comment]
You can add it in the feature_levels.yaml 

If you use agat v1.0.0 you can run ' agat levels --expose' to access the file
