### ISSUE TITLE
Perl error after agat installation

### ISSUE THREAD

**Issue by Nivskrishnan05** [NBISweden/AGAT#322]
I have installed agat using conda and it was successful. However, initiation of agat prints an error message. Kindly help me resolve the issue.  

(agat) [nivi@meg-5b ~]$ agat  `perl: symbol lookup error: /var/bin/perl5/lib/perl5/x86_64-linux-thread-multi/auto/Sub/Name/Name.so: undefined symbol:  Perl_xs_apiversion_bootcheck` 
 (agat) [nivi@meg-5b ~]$ which perl 
`/home2/niviyah_krishnan/.local/miniconda3/envs/agat/bin/perl `

**General :**
- AGAT version (1.0.0  )
- AGAT installation/use [ Conda]
- perl version (5.32.1)
- OS: [ Ubuntu]

**Comment by Juke34** [comment]
Sounds like your perl installation (/var/bin/perl5/lib/perl5/x86_64-linux-thread-multi/auto/Sub/Name/Name.so) interfers with the perl installed via Conda.
If a PERL5LIB environment variable is set you should remove it. 
Temporarly via "unset PERL5LIB", or definitely by removing the PERL5LIB environment variable from configuration file: e.g. bashrc, bash_profile, profile, /etc/envrironments, etc.
