### ISSUE TITLE
STDOUT print when --output file is defined

### ISSUE THREAD

**Issue by alexandre-jf-fernandes** [NBISweden/AGAT#324]
STDOUT print when --output file is defined, function agat_sp_manage_attributes.pl

- AGAT version (most recent, downloaded yesterday)
- AGAT installation/use miniconda3
- OS: macOS

**Comment by Juke34** [comment]
Hi, thank you for using AGAT.
Could you share the command you ran?
I think it might be related to extension provided to the output file defined by the user.

**Comment by Juke34** [comment]
As it is in such case STDOUT will just print informations. The gff result should go into the output file defined. If you expect an other behaviour, please tell me more.
