### ISSUE TITLE
AGAT created non-unique IDs

### ISSUE THREAD

**Issue by dirkjanvw** [NBISweden/AGAT#329]
**Describe the bug**
I ran AGAT with the TAIR10 annotation (_A. thaliana_) and I noticed something strange. It had split a miRNA feature over two genes and given the same ID to both a `gene` and a `primary_transcript`, whereas this should not be allowed in gff3 format.

**General (please complete the following information):**
- AGAT version: v1.0.0
- AGAT installation/use: bioconda
- OS: macOS (same issue also happens on linux)

**To Reproduce**
From the TAIR10 annotation:
```bash
CP002685.1	Genbank	gene	2805	3176	.	+	.	ID=gene-AT2G03855;Dbxref=Araport:AT2G03855;Name=MIR5642b;gbkey=Gene;gene=MIR5642b;gene_biotype=miRNA;locus_tag=AT2G03855
CP002685.1	Genbank	primary_transcript	2805	3176	.	+	.	ID=rna-gnl|JCVI|mRNA.AT2G03855.1;Parent=gene-AT2G03855;Dbxref=Araport:AT2G03855;gbkey=precursor_RNA;gene=MIR5642b;locus_tag=AT2G03855;orig_transcript_id=gnl|JCVI|mRNA.AT2G03855.1;product=microRNA ath-MIR5642b precursor
CP002685.1	Genbank	exon	2805	3176	.	+	.	ID=exon-gnl|JCVI|mRNA.AT2G03855.1-1;Parent=rna-gnl|JCVI|mRNA.AT2G03855.1;Dbxref=Araport:AT2G03855;gbkey=precursor_RNA;gene=MIR5642b;locus_tag=AT2G03855;orig_transcript_id=gnl|JCVI|mRNA.AT2G03855.1;product=microRNA ath-MIR5642b precursor
CP002685.1	Genbank	miRNA	3145	3164	.	+	.	ID=rna-AT2G03855;Parent=rna-gnl|JCVI|mRNA.AT2G03855.1;Dbxref=Araport:AT2G03855;Note=mature miRNA accession:MIMAT0022435;gbkey=ncRNA;gene=MIR5642b;locus_tag=AT2G03855;product=microRNA ath-miR5642b
CP002685.1	Genbank	exon	3145	3164	.	+	.	ID=exon-AT2G03855-1;Parent=rna-AT2G03855;Dbxref=Araport:AT2G03855;Note=mature miRNA accession:MIMAT0022435;gbkey=ncRNA;gene=MIR5642b;locus_tag=AT2G03855;product=microRNA ath-miR5642b
```

With `agat_convert_sp_gxf2gxf.pl -g test.gff3 -o test.gxf2gxf.gff3`, this results in:
```bash
##gff-version 3
CP002685.1	Genbank	gene	2805	3176	.	+	.	ID=gene-AT2G03855;Dbxref=Araport:AT2G03855;Name=MIR5642b;gbkey=Gene;gene=MIR5642b;gene_biotype=miRNA;locus_tag=AT2G03855
CP002685.1	Genbank	primary_transcript	2805	3176	.	+	.	ID=rna-gnl|JCVI|mRNA.AT2G03855.1;Parent=gene-AT2G03855;Dbxref=Araport:AT2G03855;gbkey=precursor_RNA;gene=MIR5642b;locus_tag=AT2G03855;orig_transcript_id=gnl|JCVI|mRNA.AT2G03855.1;product=microRNA ath-MIR5642b precursor
CP002685.1	Genbank	exon	2805	3176	.	+	.	ID=exon-gnl|JCVI|mRNA.AT2G03855.1-1;Parent=rna-gnl|JCVI|mRNA.AT2G03855.1;Dbxref=Araport:AT2G03855;gbkey=precursor_RNA;gene=MIR5642b;locus_tag=AT2G03855;orig_transcript_id=gnl|JCVI|mRNA.AT2G03855.1;product=microRNA ath-MIR5642b precursor
CP002685.1	Genbank	gene	3145	3164	.	+	.	ID=rna-gnl|JCVI|mRNA.AT2G03855.1;Dbxref=Araport:AT2G03855;Note=mature miRNA accession:MIMAT0022435;gbkey=ncRNA;gene=MIR5642b;locus_tag=AT2G03855;product=microRNA ath-miR5642b
CP002685.1	Genbank	miRNA	3145	3164	.	+	.	ID=rna-AT2G03855;Parent=rna-gnl|JCVI|mRNA.AT2G03855.1;Dbxref=Araport:AT2G03855;Note=mature miRNA accession:MIMAT0022435;gbkey=ncRNA;gene=MIR5642b;locus_tag=AT2G03855;product=microRNA ath-miR5642b
CP002685.1	Genbank	exon	3145	3164	.	+	.	ID=exon-AT2G03855-1;Parent=rna-AT2G03855;Dbxref=Araport:AT2G03855;Note=mature miRNA accession:MIMAT0022435;gbkey=ncRNA;gene=MIR5642b;locus_tag=AT2G03855;product=microRNA ath-miR5642b
```

**Expected behavior**
I did not expect the `primary_transcript` and `gene` to have the same ID. The [gff3 specification](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md) states:

> In the case of discontinuous features (i.e. a single feature that exists over multiple genomic locations) the same ID may appear on multiple lines. All lines that share an ID must collectively represent a single feature.

Therefore, I expected this not to happen. Even more, AGAT has created two genes whereas I expected only one.

**Additional context**
Might be related to #290

**Comment by Juke34** [comment]
I'm not sure to understand: ` It had split a miRNA feature over two genes and given the same ID to both a gene and a primary_transcript`
ID are different from what I see:
  * gene => `ID=gene-AT2G03855`
  * primary_transcript => `ID=rna-gnl|JCVI|mRNA.AT2G03855.1`

**Comment by dirkjanvw** [comment]
Ah sorry, I should have said that there are two unexpected things happening here:

1. There are now two `gene` features instead of one (as I expected). One is called `gene-AT2G03855` and has a primary_transcript as child and the other one is called `rna-gnl|JCVI|mRNA.AT2G03855.1` and has a miRNA as child.
2. The Parent feature (gene) of the miRNA is called `rna-gnl|JCVI|mRNA.AT2G03855.1` which is identical to the ID of the primary_transcript: `rna-gnl|JCVI|mRNA.AT2G03855.1`. Thus, two now unconnected features have received the same ID.

**Comment by Juke34** [comment]
Right, the `gene	3145	3164` feature should not have been created. If you wish to end up with two different genes you must provide different Parent attributes.
So yes it is a bug, I will have to find time to fix that. Thank you for pointing it.
(Both problem are related)

**Comment by Juke34** [comment]
I had a closer look. There is indeed a problem with identical ID used (point 2) but the fact that 2 parent genes exist (one is created), is due to the relationship ... miRNA expect a level1 feature (e.g. gene) but in your original file you linked it to a level2 feature (primary_transcript). If you wish to use AGAT and having miRNA child of primary_transcript you must change the expected relationship/level via the feature_levels.yaml file (`agat levels --expose` to access this file).

**Comment by dirkjanvw** [comment]
Aha, I understand! Thanks a lot for looking into it and fixing this, looking forward to this next release.

**Comment by Juke34** [comment]
Not related to #290
