### ISSUE TITLE
Issue installing with bioconda

### ISSUE THREAD

**Issue by ericmalekos** [NBISweden/AGAT#330]
I am having trouble installing the latest version of agat with bioconda.

This works, but installs the older version 0.6.2 of agat
```
conda create -n agat -c bioconda agat
conda list 
agat                      0.6.2           pl5262r35hdfd78af_0    bioconda
```

When I try to force the most recent version I get an error 

```
conda create -n agat1.0 -c bioconda agat=1.0.0 python=3.9

Package libgcc-ng conflicts for:
agat=1.0.0 -> libdb -> libgcc-ng[version='>=10.3.0|>=11.2.0|>=7.3.0|>=12|>=9.4.0|>=4.9']
python=3.9 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=7.2.0']
python=3.9 -> libgcc-ng[version='>=11.2.0|>=7.5.0|>=7.3.0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0
  - python=3.9 -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.35
```

Any suggestions?

**Comment by ericmalekos** [comment]
Update: adding the conda-forge channel resulted in successful install:

`conda create -n agat1.0 -c bioconda -c conda-forge agat=1.0 python=3.9`

**Comment by Juke34** [comment]
Try to force only agat without python
` conda create -n agat1.0 -c bioconda agat=1.0.0 `
Create first an env with a different python. Otherwise the easiest is to use singularity.
