### ISSUE TITLE
agat_sp_manage_functional_annotation.pl

### ISSUE THREAD

**Issue by DiegoSafian** [NBISweden/AGAT#339]
**Is your feature request related to a problem? Please describe.**
I would like to be able to manipulate/select what to add in the gff3 file when using this application. As it is, you can only functionally annotate a file if the GN (gene name) is present in the database. I would like to be able to pick another feature (e.g. ID of the gene) from the header.

**Describe the solution you'd like**
I would like to know how to edit the .pl file to keep what I need.

Thanks in advance!

**Comment by Juke34** [comment]
Hi Diego,
[here](https://github.com/NBISweden/AGAT/blob/master/bin/agat_sp_manage_functional_annotation.pl#L898-L899) we save the gene name from the protein header (we have a list of key=value attributes).  
[here](https://github.com/NBISweden/AGAT/blob/396df9e4ac6203e87837e4e80ad506de87f389fc/bin/agat_sp_manage_functional_annotation.pl#L307) we put the stored value within the Name attribute of the gene feature.
You can modify those lines.

**Comment by DiegoSafian** [comment]
Is there a way to save the gene name in the gff3 file using "gene_name" instead of "NAME"? I am trying to use it for STARsolo and apparently, I need the gtf to have "gene_name" to take the name of the gene. As it is now, STArsolo is taking gene_id twice (with an ensemble gtf, STARsolo takes gene_id and gene_name)

**Comment by DiegoSafian** [comment]
Thanks a lot. That helps me a ton.

If possible, I have another request. I need to create my own database to use agat_sp_manage_functional_annotation.pl. I understand that agat_sp_manage_functional_annotation.pl uses the tag GN in the database to keep the gene_name and add it to the functionally annotated gff3. I wonder how I can create a database (fast) with the GN tag using agat_sp_extract_attributes.pl, so then I can use  agat_sp_manage_functional_annotation.pl.
