### ISSUE TITLE
agat_sp_fix_longest_ORF.pl error

### ISSUE THREAD

**Issue by peterdfields** [NBISweden/AGAT#34]
Hi, 

I'm trying to run agat_sp_fix_longest_ORF.pl and I'm getting a number of errors. The gff file was originally generated using maker. A subset of the errors I'm seeing, many of which are repeated thousands of times, can be found here: https://gist.github.com/peterdfields/8ab6ce4b73b26812795348ab85689842

**Comment by Juke34** [comment]
To use the fixed version before I do an official release you can follow those steps:
```
git clone https://github.com/NBISweden/AGAT.git # Clone AGAT if not already 
cd AGAT                                         # move into AGAT folder
git pull                                             # update last version from master
perl Makefile.PL                             # Check all the dependencies
make                                            # Compile
make test                                       # Test
make install                                    # Install
```

**Comment by peterdfields** [comment]
Hi @Juke34 

I did download this version of AGAT (though I used the .yaml file and conda to setup the environment), did the make and install, and running the script from the bin directory still resulted in the same error. Would any additional info about my environment or gff be helpful for troubleshooting this issue? Thanks.

**Comment by Juke34** [comment]
Yes if you can send me the gff file along with the fasta, it would be nice.

**Comment by Juke34** [comment]
This thread didn't have any activity for a while. I consider you solved the problem or are passed to something else. Please do not hesitate to re-open the issue it you still need help.
