### ISSUE TITLE
failing to run busco support_protocol3 probably because agat does not like GFF files

### ISSUE THREAD

**Issue by JoseLopezArcondo** [NBISweden/AGAT#340]
I am trying to run support protocol3 of the busco pipeline here (https://currentprotocols.onlinelibrary.wiley.com/doi/full/10.1002/cpz1.323), which is working well with the example and some files, but does not work with some other GFF / genomes files. We guess the problem should be in the GFF which I get from GeneMarkEP+ (this one attached does not work, .txt so I can upload here)

would you have any clue what the issue could be here?
 
[GCA_001579715.1.gff.txt](https://github.com/NBISweden/AGAT/files/11051580/GCA_001579715.1.gff.txt))

[GCA_001579715.1.fna.txt](https://github.com/NBISweden/AGAT/files/11051579/GCA_001579715.1.fna.txt)

**Comment by Juke34** [comment]
Hi, what AGAT version are you using?

**Comment by Juke34** [comment]
I guess in that publication they use v0.8.0. I advise you to use the most recent version.

**Comment by Juke34** [comment]
You do not have the AGAT log or the error message? You can change the AGAT version used by the snake pipeline for one more recent.

**Comment by Juke34** [comment]
I have try AGAT V0.6.2 with your file (agat_convert_sp_gxf2gxf.pl) I do not see any problem.
