### ISSUE TITLE
Conda install

### ISSUE THREAD

**Issue by ndeimler99** [NBISweden/AGAT#342]
For some reason I am having issues with the conda install command "conda install -c bioconda agat". It is not a conda issue as other bioconda packages install perfectly fine.  However, with agat I get the solving environment: and then it will just sit there and spin for hours.  

According to the bioconda website this would be AGAT v1.0.0 with conda version 23.1.0.  

I have also run the following commands to ensure the proper channels are established.

conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict

Thanks for any advice.

**Comment by Juke34** [comment]
Force the version you want to install I.e agat=1.0.0 it might help

**Comment by Rafaelsoler13** [comment]
Same problem here

**Comment by Juke34** [comment]
Apparently there is an annoying dependency. Are you on MacOS, linux?
Did you try to install it via mamba? (to make it faster)
Remove the strict priority it can help:
`conda config --set channel_priority false`

**Comment by eduardo-pizarro** [comment]
I faced the same issue. The only way I could resolve it was install AGAT using mamba
`mamba create -n agat -c bioconda agat`

**Comment by kdm9** [comment]
> I faced the same issue. The only way I could resolve it was install AGAT using mamba `mamba create -n agat -c bioconda agat`

Even this didn't work for me, but I think the issue is with a dependency: the version of perl-lwp-simple agat=1.0.0 requires  isn't available for any installable version of perl.  I've bumped the build numbers of both agat and perl-lwp-simple in https://github.com/bioconda/bioconda-recipes/pull/40365 which hopefully fixes it, but the problem might be in more dependencies (or deeper still)

**Comment by Juke34** [comment]
Thank you for the feedbacks, let's have a look

**Comment by Juke34** [comment]
Could it be linked to libgcc-ng and the python version used by conda  the problem as in https://github.com/NBISweden/AGAT/issues/330?

Currently on my OSX the recipe is working (using  python 3.10.9 )...
Could you share your conflict / error messages?

**Comment by kdm9** [comment]
```
$ mamba create -n agat1 -c bioconda -c conda-forge agat=1.0

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.16.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['agat=1.0']

bioconda/linux-64        [====================] (00m:00s) No change
bioconda/noarch          [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
kdm801/noarch            [====================] (00m:00s) No change
kdm801/linux-64          [====================] (00m:00s) No change
conda-forge/noarch       [====================] (00m:02s) Done
conda-forge/linux-64     [====================] (00m:06s) Done
Encountered problems while solving:
  - package agat-1.0.0-pl5321hdfd78af_0 requires perl-lwp-simple >=6.39, but none of the providers can be installed
```

**Comment by kdm9** [comment]
the version bumps in the above bioconda PR seem to have fixed this for me. @Juke34 can you please test on OSX?

**Comment by alexbougdour** [comment]
Same problem to install agat using conda on a fresh install of ubuntu 22.04.

conda install -c bioconda agat=1.0.0 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
is running forever
Thank you in advance for anything you can do,
Alex

**Comment by kdm9** [comment]
Try using mamba? I gave up on conda itself a while ago for this reason among others --  it is slow to find solutions, and often fails to in strange cases.

I'd also try creating a fresh environment: `mamba create -n agat bioconda::agat`

**Comment by kcmtest** [comment]
> I faced the same issue. The only way I could resolve it was install AGAT using mamba `mamba create -n agat -c bioconda agat`

this worked conda installation somehow doesn't work
