### ISSUE TITLE
gff2 to gff3 converter ?

### ISSUE THREAD

**Issue by colindaven** [NBISweden/AGAT#343]
Hi,

I've heard good things about this package, so thanks for your efforts.

Do you know of any easy/hacky routes to convert a very simple gff2 into a minimal gff3 ? As in programs, without having to use sed and awk to hack it all together.

Format looks like this 

```
##gff-version 2 
##source-version NLR-Annotator 2
##date 2023-03-22 15:17
##Type DNA
#seqname        source  feature start   end     score   strand  frame   attribute
B73V4_ctg182    NLR_Annotator   NBSLRR  51969   53917   .       -       .       name=B73V4_ctg182_nlr1;nlrClass=NBARC-LRR
1       NLR_Annotator   NBSLRR  36589185        36592404        .       +       .       name=1_nlr1;nlrClass=NBARC-LRR
1       NLR_Annotator   NBSLRR  99772506        99775049        .       +       .       name=1_nlr2;nlrClass=CC-NBARC-LRR
1       NLR_Annotator   NBSLRR  175079657       175081660       .       +       .       name=1_nlr3;nlrClass=NBARC-LRR


```
Thanks.

**Comment by Juke34** [comment]
What do you mean by minimal? You want to get rid of all non-mandatory attribute (i.e. keep only ID/parent relationship)?
From GFF2 to GFF3 just run `agat_convert_sp_gxf2gxf.pl --gff fileIn.gff2 -o fileOut.gff3`

**Comment by colindaven** [comment]
Ok, thanks, that works.

But I had to add the NBSLRR and nbslrr feature types to the yml first, after running

`agat levels --expose`
