### ISSUE TITLE
Index Error retriving transcript

### ISSUE THREAD

**Issue by Harper75** [NBISweden/AGAT#344]
Hello,

I am trying to make the annotation of an insect species and I used agat to convert a gtf file from Braker into a gff3 to then use the gff3 in funannotate. 

I used the follwing command: 
`agat_convert_sp_gxf2gxf.pl -g augustus.hints.gtf -o augustus.hints.gff3`

When I use the gff3 file in funannotate I am getting an error that I do not know if is related to the conversion: 

[Mar 29 03:06 PM]: OS: CentOS Linux 7, 64 cores, ~ 264 GB RAM. Python: 3.8.13
[Mar 29 03:06 PM]: Running 1.8.13
[Mar 29 03:06 PM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[Mar 29 03:06 PM]: Parsing annotation and preparing annotation files.
[Mar 29 03:06 PM]: Found 37,040 gene models from GFF3 annotation
Index Error retriving transcript 0: (gene-1, {'name': None, 'type': 'transcript', 'transcript': [], 'cds_transcript': [], 'protein': [], '5UTR': [[]], '3UTR': [[]], 'gene_synonym': [], 'codon_start': [[]], 'ids': ['transcript-1'], 'CDS': [[]], 'mRNA': [[]], 'strand': '+', 'EC_number': [[]], 'location': (24852, 30033), 'contig': 'ptg000008l', 'product': ['hypothetical protein'], 'source': 'AUGUSTUS', 'phase': [[]], 'db_xref': [[]], 'go_terms': [[]], 'note': [[]], 'partialStart': [False], 'partialStop': [False], 'pseudo': False})
-------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3/envs/funannotate-v1.8.13_env/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3/envs/funannotate-v1.8.13_env/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3/envs/funannotate-v1.8.13_env/lib/python3.8/site-packages/funannotate/annotate.py", line 546, in main
    GeneCounts, GeneDB = lib.convertgff2tbl(
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3/envs/funannotate-v1.8.13_env/lib/python3.8/site-packages/funannotate/library.py", line 2055, in convertgff2tbl
    tranout.write('>%s %s\n%s\n' % (x, k, softwrap(Transcript)))
UnboundLocalError: local variable 'Transcript' referenced before assignment

Can you tell me if the error is coming from the agat conversion? 

Thank you!

**Comment by Juke34** [comment]
What AGAT version did you use?

**Comment by Harper75** [comment]
Thanks for you quick reply,
I used agat-v0.5.0

**Comment by Juke34** [comment]
Right I don't know if there is a link with AGAT but in case I would advise to try again converting the file with AGAT v1.0.0
