### ISSUE TITLE
Probles installing agat from conda

### ISSUE THREAD

**Issue by DiegoSafian** [NBISweden/AGAT#349]
**Describe the bug**
Someone in my group has been trying to install agat using Conda (conda install agat, python=3.7) as I did in the past, but it is not working. Would it be possible for you to help us on this? We also tried with conda install -c bioconda agat

**Comment by Juke34** [comment]
Hava a look at here, there are some solution: https://github.com/NBISweden/AGAT/issues/342

Do not force python 3.7 it would definitely help
And prefer to install it in a fresh and indenpant environement to avoid potential conflict with other tools
