### ISSUE TITLE
agat_sp_fix_overlaping_genes.pl does not seem to complete

### ISSUE THREAD

**Issue by sanyalab** [NBISweden/AGAT#359]
**Describe the bug**
agat_sp_fix_overlaping_genes.pl starts running fine, and parses the gff3 input file.

`=> OmniscientI total time: 125 seconds`
`isoseq_gmap_clean_1.gff file parsed`

After this there is no output on screen. Blank lines or carriage returns are printed on screen. The tool never finishes. I have to use `Cntrl-C` to kill. No output file is produced.

**General (please complete the following information):**
- AGAT version (v0.9.1)
- AGAT installation/use [Conda]
- OS: [CentOS]

**To Reproduce**
agat_sp_fix_overlaping_genes.pl -f isoseq_gmap_clean_1.gff -o isoseq_gmap_clean_1_out.gff

The input file size is more than 25 MB therefore cannot upload.

**Expected behavior**

**Screenshots**
![isoseq_gmap_clean_1_RunOutput](https://github.com/NBISweden/AGAT/assets/20696713/b5b275ae-c487-4a5e-9554-c9158aa78e7a)

**Comment by sanyalab** [comment]
Hi Jacques,
I used verbose. Seems to be working fine. Will restart this thread if I notice errors.
Thanks
Abhijit

**Comment by Juke34** [comment]
You may also try a more recent AGAT version. I think this script has been updated.

**Comment by sanyalab** [comment]
Hi Jacques,

The new version is definitely faster than the previous. This script worked fine.

I have a query. I have several genome annotations for the same line achieved using a Liftover strategy. I want to consolidate these annotations into a single one by getting rid of identical isoforms, overlaps, merging between isoforms. Is there any suitable tool to do this in the AGAT suite. I used fix_overlap, but it still gives me a lot more genes. Any advice?

Thanks
Abhijit

**Comment by Juke34** [comment]
Hi, I guess the _merge_annotation is the one you need to achieve that.

**Comment by sanyalab** [comment]
Hi Jacques,

Whats the difference between merge_annotations, and complement_annotations? In both cases do identical isoforms get removed? I want to the final annotation to retain non-identical isoforms per loci. 

Thanks
Abhijit
