### ISSUE TITLE
agat_sp_split_by_level2_feature Bus error

### ISSUE THREAD

**Issue by ViriatoII** [NBISweden/AGAT#36]
Hi!

I keep having this  Bus error. Is it related to memory? I'm using 20 Gbs memory in a PBSpro cluster.

This happened sometimes when using agat installed with conda and also when running your nextflow pipeline.

```
agat_sp_split_by_level2_feature.pl -g MPI_run.all.gff -o maker_results_noAbinitio_clean
Command error:
  .command.sh: line 2: 86004 Bus error   
```

error exit status (135)

**Comment by ViriatoII** [comment]
I think it has to do with the output directory already existing (often when the command ran unsuccessfuly before and created an empty folder). 

The function doesn't know how to deal with this and crashes in a bus error.

**Comment by Juke34** [comment]
I don't think the problem is related to AGAT. You can try to run the command standalone (outside the nextflow pipeline) to check if it is really related to AGAT. (you must activate the AGAT Conda env somewhere is the work dir, or install your own AGAT conda env)

**Comment by ViriatoII** [comment]
Hi!
Standalone now it worked. Generated 2 files:
1181933698 22. Apr 13:34 match_part.gff
72231711 22. Apr 13:34 mrna.gff

So is this a nextflow problem? That pipeline comes with it's own version of agat and automatically activates that environment, as I can see:

    source $(conda info --json | awk '/conda_prefix/ { gsub(/"|,/, "", $2); print $2 }')/bin/activate home/annotation_project/scratch/nxf_work/conda/agat-6b6131ed4ecf41887a64062ec60a9397  

But I remember having this bus error a couple of months ago, and then I was only using agat standalone.

**Comment by Juke34** [comment]
Ok probably memory issue. All AGAT scripts with `_sp_` in the name load the file into memory, that could end  to take ~6 time the size of the file in memory. So for 1Gb file it can take ~6 Gb in memory. It sounds you set up 2gb in your pbs profile, and your file is big. So there is not enough memory apparently. Either increase the memory size, or clean your GFF file first. Indeed it sounds to contain lot of unnecessary data (what end up in the match file). To clean it use  a awk command and keep only what is `maker` in the 3rd column.

**Comment by Juke34** [comment]
Sorry I meant 2nd column!

**Comment by ViriatoII** [comment]
Worked like a charm, thanks! Went further but as always, one error follows other..

```
Error executing process > 'abinitio_training:remove_incomplete_gene_models (codingGeneFeatures.filter.longest_cds)'

Caused by:
  Process `abinitio_training:remove_incomplete_gene_models (codingGeneFeatures.filter.longest_cds)` terminated with an error exit status (255)

Command executed:
  agat_sp_filter_incomplete_gene_coding_models.pl --gff codingGeneFeatures.filter.longest_cds.gff         -f b_tournefortii.fasta -o codingGeneFeatures.filter.longest_cds.complete.gff

Command exit status:
  255

Command output:
  Codon table 1 in use. You can change it using --table option.
  GFF3 file parsed
  Genome fasta parsed

Command error:
  Supplement information: seq_id=1 ; seq_id_correct=1 ; start=14801145 ; end=14802266 ; 1 sequence length: 17193957 )
  Problem ! The size of the sequence extracted 535 is different than the specified span: 534.
  That often occurs when the fasta file does not correspond to the annotation file. Or the index file comes from another fasta file which had the same name and haven't been removed.
  As last possibility your gff contains location errors (Already encountered for a Maker annotation)
  Supplement information: seq_id=77683 ; seq_id_correct=77683 ; start=130717 ; end=131250 ; 77683 sequence length: 205989 )
  Problem ! The size of the sequence extracted 865 is different than the specified span: 864.
  That often occurs when the fasta file does not correspond to the annotation file. Or the index file comes from another fasta file which had the same name and haven't been removed.
  As last possibility your gff contains location errors (Already encountered for a Maker annotation)
  (...)

 ------------- EXCEPTION: Bio::Root::Exception -------------
  MSG: Failed validation of sequence '[unidentified sequence]'. Invalid characters were: >77767
  STACK: Error::throw
  STACK: Bio::Root::Root::throw /gpfs/project/projects/qggp/C34_PS/experiments/annotation/maker/scratch/nxf_work/conda/agat-6b6131ed4ecf41887a64062ec60a9397/lib/site_perl/5.26.2/Bio/Root/Root.pm:447
  STACK: Bio::PrimarySeq::validate_seq /gpfs/project/projects/qggp/C34_PS/experiments/annotation/maker/scratch/nxf_work/conda/agat-6b6131ed4ecf41887a64062ec60a9397/lib/site_perl/5.26.2/Bio/PrimarySeq.pm:338
  STACK: Bio::PrimarySeq::_set_seq_by_ref /gpfs/project/projects/qggp/C34_PS/experiments/annotation/maker/scratch/nxf_work/conda/agat-6b6131ed4ecf41887a64062ec60a9397/lib/site_perl/5.26.2/Bio/PrimarySeq.pm:287
  STACK: Bio::PrimarySeq::seq /gpfs/project/projects/qggp/C34_PS/experiments/annotation/maker/scratch/nxf_work/conda/agat-6b6131ed4ecf41887a64062ec60a9397/lib/site_perl/5.26.2/Bio/PrimarySeq.pm:272
  STACK: Bio::PrimarySeq::new /gpfs/project/projects/qggp/C34_PS/experiments/annotation/maker/scratch/nxf_work/conda/agat-6b6131ed4ecf41887a64062ec60a9397/lib/site_perl/5.26.2/Bio/PrimarySeq.pm:229
  STACK: Bio::Seq::new /gpfs/project/projects/qggp/C34_PS/experiments/annotation/maker/scratch/nxf_work/conda/agat-6b6131ed4ecf41887a64062ec60a9397/lib/site_perl/5.26.2/Bio/Seq.pm:496
  STACK: main::extract_cds /gpfs/project/projects/qggp/C34_PS/experiments/annotation/maker/scratch/nxf_work/conda/agat-6b6131ed4ecf41887a64062ec60a9397/bin/agat_sp_filter_incomplete_gene_coding_models.pl:271
  STACK: /gpfs/project/projects/qggp/C34_PS/experiments/annotation/maker/scratch/nxf_work/conda/agat-6b6131ed4ecf41887a64062ec60a9397/bin/agat_sp_filter_incomplete_gene_coding_models.pl:135
  -----------------------------------------------------------
```

I also remember having this error twoin months ago with standalone agat, I think at the time I edited the perl script with a "+1" for expected sequence length, but I'm not much of a perl guy.

**Comment by Juke34** [comment]
I moved your last comment in a new issue (#37).
I consider this one resolved.
