### ISSUE TITLE
agat_sp_fix_longest_ORF.pl fails to produce gff

### ISSUE THREAD

**Issue by r-mashoodh** [NBISweden/AGAT#360]
AGAT has been working great for me so far, so thanks. I'm trying to determine if the ORFs of my GTF are properly defined. Trying to work out if the start/stop codons are missing from the CDS.

I've run into a bit of an issue. I'm using singularity to run AGAT.  I have the original reference GTF (GCF_001412225.1, converted to and a modified GTF where I extracted CDS only). The error occurs in both -- though the full GTF has a lot more warnings. 

`agat_sp_fix_longest_ORF.pl -gff cds_all.gtf --fasta genome.fa -o cds`

There error is as follows ...

`Can't modify non-lvalue subroutine call of &Bio::SeqFeature::Generic::end at /usr/local/bin/agat_sp_fix_longest_ORF.pl line 484.`

I've attached the std out here: [agat_error.txt](https://github.com/NBISweden/AGAT/files/11585735/agat_error.txt)

Is this an issue with my gtf? My bioperl is up-to-date as far as I can tell ...

thanks in advance

**Comment by Juke34** [comment]
Coud share or point me to the files that I can try by myself and see if it is a bug?

**Comment by kdm9** [comment]
@Juke34 Was this bug identified and fixed, or was this issue just closed for inactivity? I ask as I'm hitting the same bug myself, and want to know if I should bother debugging it or just try installing from the latest git revision.

**Comment by Juke34** [comment]
I closed it for inactivity

**Comment by Juke34** [comment]
I have tried  AGAT version 1.4.0 and I do not have any issue like this one. If you still hit the issue please re-open the issue and add more information. otherwise I would not be able to check/fix it.

**Comment by 123jjhy** [comment]
hi，
I have the same problem and need your help
GFF3 file parsed
Fasta file parsed
Can't modify non-lvalue subroutine call of &Bio::SeqFeature::Generic::end at ./agat_sp_fix_longest_ORF.pl line 487.

**Comment by 123jjhy** [comment]
It should be a problem of  the GTF file, could be about SuspiciousFrame

**Comment by Juke34** [comment]
Again I cannot help without sample to investigate myself. Please provide a piece of annotation file with the command you run to be able to reproduce the issue.
