### ISSUE TITLE
Chromosome "0" becomes "SEQ"

### ISSUE THREAD

**Issue by sivasubramanics** [NBISweden/AGAT#368]
**Describe the bug**
While I attempt to convert GFF to GTF, which contains "0" as chromosome name, the output GTF contains "SEQ" instead of "0".

**General (please complete the following information):**
- AGAT version v1.0.0
- AGAT installation/use  - conda
- OS: Ubuntu

**To Reproduce**
You can try with any GFF with 0 as sequence name

**Expected behavior**
The sequence name should be retained.

**Comment by Juke34** [comment]
Hi,

Sounds a perl problem. 0 is interpreted as false. When the sequence is checked and the value is 0, we think there is no sequence ID so  SEQ value is put by default. But I guess this Is BioPerl issue, not related to AGAT.
