### ISSUE TITLE
agat_sp_filter_feature_from_keep_list.pl keeps all mRNA records instead of just the selected

### ISSUE THREAD

**Issue by sanyalab** [NBISweden/AGAT#370]
Hi Jacques,

I used the agat_sp_filter_feature_from_keep_list.pl tool to extract records pertaining to specific mRNA using the following command

`agat_sp_filter_feature_from_keep_list.pl --gff Ref.gff --keep_list te1.lst --type mRNA`

The file `te1.lst` contains a a single mRNA ID `G1.2`. However, on running this script the output has both `G1.1` and `G1.2`. I want just `G1.2`. How can I achieve that?

Thanks
Abhijit

**Comment by Juke34** [comment]
This is intended by the script, it kept the whole record. To remove part of a record like in your case an isoforms you have to do the other way around using the kill list script with G1.1 in the list
