### ISSUE TITLE
Version issue with v1.1.0 conda/biocontainer builds

### ISSUE THREAD

**Issue by jmrussell** [NBISweden/AGAT#373]
**Describe the bug**

Both the biocontainers 1.1.0--pl5321hdfd78af_0 and 1.1.0--pl5321hdfd78af_1 (and the corresponding conda installs) are listed as version 1.1 but are installing agat version 1.0.

**General (please complete the following information):**
- AGAT version 1.1.0
- AGAT installation - CONDA + BIOCONTAINERS

**To Reproduce**
Run conda install or pull either of the two biocontainers

**Expected behavior**
AGAT version 1.1 would be present with the fix for #365  

**Screenshots**
![image](https://github.com/NBISweden/AGAT/assets/8886267/87a0d2c9-ed71-429d-a3d8-f4563cb4d043)

**Additional context**

I might be missing something obvious here, but wanted to give you the heads up that the build doesn't seem to reflect the versioning properly.

**Comment by Juke34** [comment]
Thank you for your feedback. I'm aware of this mistake, I released it like that.
