### ISSUE TITLE
bug in agat_sq_add_attributes_from_tsv.pl

### ISSUE THREAD

**Issue by Juke34** [NBISweden/AGAT#378]
Hello Dr @Juke34 thank you for creating this wonderfool tool I was using this utilities where my goal is to add new attributes from a tsv file to the existing gtf file. I did run based on the example you have given, in other words input as tsv file and another input as gtf file but Im not sure if I did get the right output I didn't raise a new issue as its should be a simple problem i believe unless Im doing something grossly wrong. I have asked the question [here ](https://www.biostars.org/p/9568841/) it would be really kind of you if you can have a look and let me know what I'm doing wrong.

After I ran the command i do see these

```
Number of header (2) different to number of columm (1) line 14834
Number of header (2) different to number of columm (1) line 14835
Number of header (2) different to number of columm (1) line 14836
Number of header (2) different to number of columm (1) line 14837
Number of header (2) different to number of columm (1) line 14838
Number of header (2) different to number of columm (1) line 14839
Number of header (2) different to number of columm (1) line 14840
Number of header (2) different to number of columm (1) line 14841
Number of header (2) different to number of columm (1) line 14842
```

_Originally posted by @kcmtest in https://github.com/NBISweden/AGAT/issues/44#issuecomment-1627513231_

**Comment by kcmtest** [comment]
is there any other way until you update the function I can do it ?

**Comment by Juke34** [comment]
You can first convert your gtf in gff with agat_convert_sp_gxf2gxf.pl and then use the tsv script. Otherwise I should be able to fix the issue today.

**Comment by kcmtest** [comment]
now to get the updated function I can just reinstall it ?

**Comment by Juke34** [comment]
Follow this protocol: https://agat.readthedocs.io/en/latest/troubleshooting.html#how-to-use-a-version-of-agat-from-a-specific-branch
