### ISSUE TITLE
Removing premature stop codons from gff

### ISSUE THREAD

**Issue by romseg** [NBISweden/AGAT#387]
Dear author,

Is there an option to remove all the features from my gff file flagged as premature stop codons done with agat_sp_flag_premature_stop_codons.pl? I want to translate the gff into amino acids and nucleotides without the premature stop codons entries. Thank you.

Rom

**Comment by Juke34** [comment]
Yes you can filter those feature out using `agat_sp_filter_feature_by_attribute_presence.pl` prior to extract/translate the sequences
