### ISSUE TITLE
A little bug -- word spelling mistake

### ISSUE THREAD

**Issue by wang-wldlsw** [NBISweden/AGAT#391]
https://github.com/NBISweden/AGAT/blob/master/bin/agat_sp_filter_feature_by_attribute_value.pl 
in [AGAT-v1.0.0]
![image](https://github.com/NBISweden/AGAT/assets/73244525/8f9d7a2f-0c31-46b9-8fc3-9200eeb53b1f)

**Comment by Juke34** [comment]
Thank you for using AGAT and for the feedback
