### ISSUE TITLE
Turning off the GFF3 parser

### ISSUE THREAD

**Issue by sanyalab** [NBISweden/AGAT#393]
Hi Jacques,

This is not a feature request but a question.

Is there a way to turn off the checking of GFF3 files in AGAT. I have a situation where I have already checked the accuracy of the GFF3 format, and I will be using another AGAT tool to compare the GFF3 files. For the comparison step, I do not wish to use the GFF3 parser to check the files again. Can this be turned off? What is the process?

Thanks
Abhijit

**Comment by Juke34** [comment]
Run `agat config --exopse`
The parser checks that can be disable are packed in that paragraph 

```
# ----------------------------- Checks made by the parser ----------------------
# in order of appearance wihtin the parser
check_sequential: true
check_l2_linked_to_l3: true
check_l1_linked_to_l2: true
remove_orphan_l1: true
check_all_level3_locations: true
check_cds: true
check_exons: true
check_utrs: true
check_all_level2_locations: true
check_all_level1_locations: true
check_identical_isoforms: true
```

Set everything to false.
But if the file has already been corrected, the computation time required for  passing through the test again is probably negligible.

If you use scripts with _sp_ prefix AGAT will anyway take the time needed to put everything in memory in a specific shape, with or without tests.

**Comment by sanyalab** [comment]
Hi Jacques,

Thank you for the reply. The GFF3 files are actually alignment files and pretty large in size ~5G. Therefore, I think making the changes to the config might help. I'll let you know.

Thanks
Abhijit
