### ISSUE TITLE
Semi-manual installation of AGAT fails most installation tests

### ISSUE THREAD

**Issue by pzit0** [NBISweden/AGAT#394]
I've tried installing AGAT but the following command prompts a huge error message (shown below, redacted). I've previously tried installing through conda, however, it cannot solve an environment issue, and it keeps going indefinitely. Is there any way to fix this? 

(base) pzito@IBIO-DRW7N0JQY0 AGAT % make test
Test Summary Report
-------------------
t/config.t         (Wstat: 512 Tests: 3 Failed: 2)
  Failed tests:  1, 3
  Non-zero exit status: 2
t/gff_other.t      (Wstat: 1024 Tests: 4 Failed: 4)
  Failed tests:  1-4
  Non-zero exit status: 4
t/gff_syntax.t     (Wstat: 11520 Tests: 45 Failed: 45)
  Failed tests:  1-45
  Non-zero exit status: 45
t/gff_version.t    (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/level_missing.t  (Wstat: 3328 Tests: 13 Failed: 13)
  Failed tests:  1-13
  Non-zero exit status: 13
t/scripts_compile.t (Wstat: 19712 Tests: 77 Failed: 77)
  Failed tests:  1-77
  Non-zero exit status: 77
t/scripts_output.t (Wstat: 20480 Tests: 80 Failed: 80)
  Failed tests:  1-80
  Non-zero exit status: 80
t/unitest.t        (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 15 tests but ran 0.
Files=8, Tests=222, 20 wallclock secs ( 0.06 usr  0.02 sys +  6.43 cusr  2.32 csys =  8.83 CPU)
Result: FAIL
Failed 8/8 test programs. 221/222 subtests failed.
make: *** [test_dynamic] Error 2

**Comment by Juke34** [comment]
When installing via conda, be sure to use a fresh new environment.
You can also try with Mamba instead of conda (you will need to install mamba first)

Otherwise, run `perl -I lib/ t/gff_other.t` to get more details about error when running the gff_other.t test

**Comment by pzit0** [comment]
Hi! 

I've tried on different conda environments, but it doesn't seem to be working for me. Here's the detailed version of the failed tests: 

(base) pzito@IBIO-DRW7N0JQY0 AGAT % perl -I lib/ t/gff_other.t
1..4
Can't locate AGAT/AGAT.pm in @INC (you may need to install the AGAT::AGAT module) (@INC contains: /Library/Perl/5.30/darwin-thread-multi-2level /Library/Perl/5.30 /Network/Library/Perl/5.30/darwin-thread-multi-2level /Network/Library/Perl/5.30 /Library/Perl/Updates/5.30.3 /System/Library/Perl/5.30/darwin-thread-multi-2level /System/Library/Perl/5.30 /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level /System/Library/Perl/Extras/5.30) at bin/agat_convert_sp_gxf2gxf.pl line 10.
BEGIN failed--compilation aborted at bin/agat_convert_sp_gxf2gxf.pl line 10.
diff: tmp.gff: No such file or directory
not ok 1 - zip_and_fasta check
#   Failed test 'zip_and_fasta check'
#   at t/gff_other.t line 40.
Can't locate AGAT/AppEaser.pm in @INC (you may need to install the AGAT::AppEaser module) (@INC contains: /Library/Perl/5.30/darwin-thread-multi-2level /Library/Perl/5.30 /Network/Library/Perl/5.30/darwin-thread-multi-2level /Network/Library/Perl/5.30 /Library/Perl/Updates/5.30.3 /System/Library/Perl/5.30/darwin-thread-multi-2level /System/Library/Perl/5.30 /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level /System/Library/Perl/Extras/5.30) at bin/agat line 8.
BEGIN failed--compilation aborted at bin/agat line 8.
Can't locate AGAT/AGAT.pm in @INC (you may need to install the AGAT::AGAT module) (@INC contains: /Library/Perl/5.30/darwin-thread-multi-2level /Library/Perl/5.30 /Network/Library/Perl/5.30/darwin-thread-multi-2level /Network/Library/Perl/5.30 /Library/Perl/Updates/5.30.3 /System/Library/Perl/5.30/darwin-thread-multi-2level /System/Library/Perl/5.30 /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level /System/Library/Perl/Extras/5.30) at bin/agat_convert_sp_gxf2gxf.pl line 10.
BEGIN failed--compilation aborted at bin/agat_convert_sp_gxf2gxf.pl line 10.
diff: tmp.gff: No such file or directory
not ok 2 - tabix check
#   Failed test 'tabix check'
#   at t/gff_other.t line 51.
Can't locate AGAT/AGAT.pm in @INC (you may need to install the AGAT::AGAT module) (@INC contains: /Library/Perl/5.30/darwin-thread-multi-2level /Library/Perl/5.30 /Network/Library/Perl/5.30/darwin-thread-multi-2level /Network/Library/Perl/5.30 /Library/Perl/Updates/5.30.3 /System/Library/Perl/5.30/darwin-thread-multi-2level /System/Library/Perl/5.30 /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level /System/Library/Perl/Extras/5.30) at bin/agat_convert_sp_gxf2gxf.pl line 10.
BEGIN failed--compilation aborted at bin/agat_convert_sp_gxf2gxf.pl line 10.
diff: tmp.gff: No such file or directory
not ok 3 - issue329 check
#   Failed test 'issue329 check'
#   at t/gff_other.t line 62.
Can't locate AGAT/AGAT.pm in @INC (you may need to install the AGAT::AGAT module) (@INC contains: /Library/Perl/5.30/darwin-thread-multi-2level /Library/Perl/5.30 /Network/Library/Perl/5.30/darwin-thread-multi-2level /Network/Library/Perl/5.30 /Library/Perl/Updates/5.30.3 /System/Library/Perl/5.30/darwin-thread-multi-2level /System/Library/Perl/5.30 /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level /System/Library/Perl/Extras/5.30) at bin/agat_convert_sp_gxf2gxf.pl line 10.
BEGIN failed--compilation aborted at bin/agat_convert_sp_gxf2gxf.pl line 10.
diff: tmp.gff: No such file or directory
not ok 4 - issue368 check
#   Failed test 'issue368 check'
#   at t/gff_other.t line 72.
# Looks like you failed 4 tests of 4.

Am I missing any prerequisite modules? Or do I have to install AGAT::AGAT module separately?

Thanks! 
Patricia

**Comment by Juke34** [comment]
Instead of conda you can try mamba it is much faster to resolve the env. Otherwise you may prefer to use the container.
For the manual installation, only the test throw errors?
From what Insee it sounds the test is not run from the correct location. Did you clone the repo and followed the protocol from the readme?
