### ISSUE TITLE
Problems with installation and usage via Docker and Singularity

### ISSUE THREAD

**Issue by Carolinacanettieri** [NBISweden/AGAT#397]
Hi Juke!

I have failed to install and use AGAT through Docker and Singularity. I have successfully installed it cloning the Git Repo and using Conda, though. I'm writing this issue to share some problems I've found while trying to use the mentioned programs, aiming to make it usefull for fixing bugs or making updates.

When I follow the recommended steps to install and run AGAT through Docker and Singularity, pulling the software image aparentely works. They return the following messages:

Docker:
`1.2.0--pl5321hdfd78af_0: Pulling from biocontainers/agat
642efca944a0: Pull complete 
bd9ddc54bea9: Pull complete 
4c206e81fe8e: Pull complete 
Digest: sha256:7ea8fa5a8428758cd87e3a5dcfaf277febdfcae95cd1fe473770abf8b928ec99
Status: Downloaded newer image for quay.io/biocontainers/agat:1.2.0--pl5321hdfd78af_0
quay.io/biocontainers/agat:1.2.0--pl5321hdfd78af_0`

Running ---help with the suggested AGAT script using Docker also works.

Singularity:
`INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob 642efca944a0 done  
Copying blob bd9ddc54bea9 done  
Copying blob 4c206e81fe8e done  
Copying config e45a46500f done  
Writing manifest to image destination
Storing signatures
2023/08/31 10:52:57  info unpack layer: sha256:642efca944a099a40fb3c07af9503df633650ab4299bba89f04e2106bfe2d85e
2023/08/31 10:52:57  info unpack layer: sha256:bd9ddc54bea929a22b334e73e026d4136e5b73f5cc29942896c72e4ece69b13d
2023/08/31 10:52:57  info unpack layer: sha256:4c206e81fe8eea5a444add96a5ae6fac74590cbdbf9af53b916f50c218f20c8a
INFO:    Creating SIF file...`

But after pulling the image, I am not able to run any AGAT script with input

Docker can't find the input and output paths and, when I add them to the options, it returns the following error:
`No such file or directory at /usr/local/lib/perl5/site_perl/AGAT/OmniscientO.pm line 67.`
It turns out that there is no `/usr/local/lib/perl5/` directory.

 In other hand, when running Singularity, although it indeed downloads the SIF file, the software cannot open it. It returns:
`FATAL:   could not open image WDPATH/agat_1.2.0--pl5321hdfd78af_0: failed to retrieve path for WDPATH/agat_1.2.0--pl5321hdfd78af_0: lstat WDPATH/agat_1.2.0--pl5321hdfd78af_0: no such file or directory`

I probably have some issues related to Perl in my Linux Server, but as all these programs create specific enviroments for softwares, I was not expecting to find any errors.

**Comment by Juke34** [comment]
What computer do you use? What architecture ARM or X86?

**Comment by Carolinacanettieri** [comment]
Hi
I use a Linux server x86_64

**Comment by Juke34** [comment]
Ok then it is most likely a problem with your command. I will give a try to the docker image to be sure it is working properly.

**Comment by Juke34** [comment]
I have not seen any problem on my side

**Comment by Carolinacanettieri** [comment]
Well, then it is probably some issue with my server.
Thank you for your update and your dedication to improve this great tool!
