### ISSUE TITLE
agat_sp_to_tabulated sort order changed 

### ISSUE THREAD

**Issue by elor77** [NBISweden/AGAT#40]
When running the script on a previously sorted maker gff  using `agat_sp_gxf_to_gff3.pl ` , I noticed that the output table is sort order changed back to the original gff. 
I'm assuming it's sorted using the ID or NAME tag.

**Comment by Juke34** [comment]
Right it is not sorted as the GFF it is sorted by ID name.
Do you recommend to sort the tabulated file in the same way as the GFF?
It can be done, I have to modify the name of this script too. It should be part of the converter i.e `agat_convert_sp_gff2tsv.pl`

**Comment by elor77** [comment]
I'm not sure what to recommend... Because i see the value of both orders - of course the value of agat tool is that the gene feature topology is kept correctly - so it's hard to sort manually post conversion.  
Maybe it would be best to add the argument for sorting? By gff order or by ID? 
Cheers
