### ISSUE TITLE
Possible tabular format for agat_sp_statistics.pl

### ISSUE THREAD

**Issue by KristinaGagalova** [NBISweden/AGAT#401]
Hi,

Thank you for implementing AGAT, it's very handy for the analysis of gffs

I was wondering if you could implement a tabular format output option that can enable the generation of a table. That can be read in python or R easily. So far I am using a small bash parser which on top of the tool to parse the output that you are providing

This could be a good tabular file output - 3 columns output with one feature per line
* Name of the feature
* Results with isoforms 
* Results with shortest isoforms removes

Thank you in advance

**Comment by Juke34** [comment]
I understand the need, would it be ok with yaml type output instead of tsv?

**Comment by KristinaGagalova** [comment]
That could work too! I would be able to convert it to tsv
