### ISSUE TITLE
STACK: Error::throw

### ISSUE THREAD

**Issue by BioHlT** [NBISweden/AGAT#405]
Hi,

I fairly new to the bioinformatics world. I was running the following command below to get the basic intron/exon stat, I run in the the following error. 
I am not sure what the error means or how to resolve it, I would appreciate any help you can offer
Thank you!
Command : agat_sq_stat_basic.pl -i VV_annotation.gtf -o VV_Intron_Exon_sum.txt

Error Message: 
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: '' is not a valid frame
STACK: Error::throw
STACK: Bio::Root::Root::throw /opt/anaconda3/envs/AGAT/lib/site_perl/5.26.2/Bio/Root/Root.pm:447
STACK: Bio::SeqFeature::Generic::frame /opt/anaconda3/envs/AGAT/lib/site_perl/5.26.2/Bio/SeqFeature/Generic.pm:503
STACK: Bio::Tools::GFF::_from_gff3_string /opt/anaconda3/envs/AGAT/lib/site_perl/5.26.2/Bio/Tools/GFF.pm:624
STACK: Bio::Tools::GFF::from_gff_string /opt/anaconda3/envs/AGAT/lib/site_perl/5.26.2/Bio/Tools/GFF.pm:437
STACK: Bio::Tools::GFF::next_feature /opt/anaconda3/envs/AGAT/lib/site_perl/5.26.2/Bio/Tools/GFF.pm:395
STACK: /opt/anaconda3/envs/agat/bin/agat_sq_stat_basic.pl:94
-----------------------------------------------------------

**Comment by Juke34** [comment]
It sounds that one of the mandatory field in you file is missing. You should check the frame column (8th field) that must contain '0', '1', '2' or '.'.
