### ISSUE TITLE
AGAT problem converting GFF to GTF

### ISSUE THREAD

**Issue by desmodus1984** [NBISweden/AGAT#408]
**Describe the bug**
Hi,
I was able to install AGAT in a SuperComputer Center, and now at Florida International University, I can't install AGAT using conda, but I was able to "download" the singularity, and now I cannot convert a GFF to GTF using agat_convert_sp_gff2gtf.pl.

**General (please complete the following information):**
- AGAT version /agat_1.0.0
- AGAT installation/use Singularity
- OS: Linux Linux 3.10.0-1127.19.1.el7.x86_64 x86_64 

**To Reproduce**
I downloaded the GFF file from Bombus vosnesenskii from NCBI
https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/011/952/255/GCF_011952255.1_Bvos_JDL3184-5_v1.1/
GCF_011952255.1_Bvos_JDL3184-5_v1.1_genomic.gff.gz
I decompress it with gzip -d 

and then I got the following error messages:
agat_convert_sp_gff2gtf.pl --gff Bvos_JDL3184-5_v1.1_gene.gff -o test.1.gtf
Using standard /usr/local/lib/perl5/site_perl/auto/share/dist/AGAT/config.yaml file
Update config
Reading input file
********************************************************************************
*                              - Start parsing -                               *
********************************************************************************
-------------------------- parse options and metadata --------------------------
=> Accessing the feature_levels YAML file
Using standard /usr/local/lib/perl5/site_perl/auto/share/dist/AGAT/feature_levels.yaml file
=> Attribute used to group features when no Parent/ID relationship exists (i.e common tag):
        * locus_tag
        * gene_id
=> merge_loci option deactivated
=> Machine information:
        This script is being run by perl v5.32.1
        Bioperl location being used: /usr/local/lib/perl5/site_perl/Bio/
        Operating system being used: linux 
=> Accessing Ontology
        No ontology accessible from the gff file header!
        We use the SOFA ontology distributed with AGAT:
                /usr/local/lib/perl5/site_perl/auto/share/dist/AGAT/so.obo
        Read ontology /usr/local/lib/perl5/site_perl/auto/share/dist/AGAT/so.obo:
                4 root terms, and 2596 total terms, and 1516 leaf terms
        Filtering ontology:
                We found 1861 terms that are sequence_feature or is_a child of it.
--------------------------------- parsing file ---------------------------------
=> Number of line in file: 0
=> Number of comment lines: 0
=> Fasta included: No
=> Number of features lines: 0
Use of uninitialized value $nb_ft in concatenation (.) or string at /usr/local/lib/perl5/site_perl/AGAT/OmniscientI.pm line 3354.
=> Number of feature type (3rd column): 
        * Level1: 0 => 
        * level2: 0 => 
        * level3: 0 => 
        * unknown: 0 => 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!Your file has less than 8 columns (0). It cannot be a GTF/GFF file. Please ver!
!                                ify your file                                 !
                
Singularity> agat_convert_sp_gff2gtf.pl --gff Bvos.gff -o test.gtf
Using config.yaml file found in your working directory.
verbose parameter missing in the configuration file.
progress_bar parameter missing in the configuration file.
progress_bar parameter missing in the configuration file.
debug parameter missing in the configuration file.
tabix parameter missing in the configuration file.
merge_loci parameter missing in the configuration file.
throw_fasta parameter missing in the configuration file.
force_gff_input_version parameter missing in the configuration file.
output_format parameter missing in the configuration file.
gff_output_version parameter missing in the configuration file.
gtf_output_version parameter missing in the configuration file.
create_level3_for_level2_orphan parameter missing in the configuration file.
locus_tag parameter missing in the configuration file.
prefix_new_id parameter missing in the configuration file.
check_sequential parameter missing in the configuration file.
check_l2_linked_to_l3 parameter missing in the configuration file.
check_l1_linked_to_l2 parameter missing in the configuration file.
remove_orphan_l1 parameter missing in the configuration file.
check_all_level3_locations parameter missing in the configuration file.
check_cds parameter missing in the configuration file.
check_exons parameter missing in the configuration file.
check_utrs parameter missing in the configuration file.
check_all_level2_locations parameter missing in the configuration file.
check_all_level1_locations parameter missing in the configuration file.
check_identical_isoforms parameter missing in the configuration file.

I am new to genomics. How can I check or verify the file? Can Agat help?
This GFF was generated by the internal software of NCBI, the Eukaryotic Annotation tool.

Thanks;

**Comment by Juke34** [comment]
You file is not accessible in the container. By default Singu mount few folders among them the current working directory. So apparently you are not launching the sigu container at the same place of your data.
You have to use the --bind parameter. Please have a look here to see how to do so: https://docs.sylabs.io/guides/3.0/user-guide/bind_paths_and_mounts.html
