### ISSUE TITLE
Unable to convert GFF to GFT

### ISSUE THREAD

**Issue by MrLocuace** [NBISweden/AGAT#419]
Hello,

I have these files in my pwd:

cd /project/PI/USERS/me/czi/data/tc/

[me@midway3-login3 tc]$ ls
agat_1.0.0--pl5321hdfd78af_0.sif
in.gff
out.gff

I installed AGAT via singularity:

module load singularity
singularity pull docker://quay.io/biocontainers/agat:1.0.0--pl5321hdfd78af_0
singularity run agat_1.0.0--pl5321hdfd78af_0.sif
agat_convert_sp_gxf2gxf.pl --help

I get the prompt:
Singularity> 

Then I run:

Singularity> agat_convert_sp_gff2gtf.pl --gff in.gff -o /project/PI/USERS/me/czi/data/tc/out.gtf
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.UTF-8",
	LC_CTYPE = "en_US.UTF-8",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
Using standard /usr/local/lib/perl5/site_perl/auto/share/dist/AGAT/config.yaml file
Could not open file '/project/PI/USERS/me/czi/data/tc/out.gtf' No such file or directory at /usr/local/bin/agat_convert_sp_gff2gtf.pl line 48.

I have tried different alternatives, such as:

cd /project/PI/USERS/me/czi/data/tc/

[me@midway3-login3 tc]$ singularity exec --bind /project/PI/USERS/me/czi/data/tc:/agat agat_convert_sp_gxf2gxf.pl --gff /agat/tc/in.gff -o /agat/tc/out.gtf
FATAL:   could not open image /project/PI/USERS/me/czi/data/tc/agat_convert_sp_gxf2gxf.pl: failed to retrieve path for /project/PI/USERS/me/czi/data/tc/agat_convert_sp_gxf2gxf.pl: lstat /project/PI/USERS/me/czi/data/tc/agat_convert_sp_gxf2gxf.pl: no such file or directory

Please help !

**Comment by Juke34** [comment]
In your first try did you get the help when running agat_convert_sp_gxf2gxf.pl --help?

What if you do agat_convert_sp_gxf2gxf.pl --gff in.gff -o out2.gff

**Comment by MrLocuace** [comment]
Hi,
Yes, I get the help.
After running your suggested command, I get:

**Comment by Juke34** [comment]
`ls -s` do you see the in.gff among your files in the current directory?

**Comment by MrLocuace** [comment]
Yes I do:

[me@midway3-login4 tc]$ ls -s
total 136000
69376 agat_1.0.0--pl5321hdfd78af_0.sif
   16 agat_convert_sp_gff2gtf.pl
    0 agat_convert_sp_gff2gtf.pl~
 1808 in.gff
64800 in_Orf50.gff

**Comment by Juke34** [comment]
1st why do you have agat_convert_sp_gff2gtf.pl file in that directory? (remove it or rename it to be sure to not use that file)
Are you I your container?  singularity run agat_1.0.0--pl5321hdfd78af_0.sif 
Does AGAT works?  Try `agat_convert_sp_gxf2gxf.pl -h`(it should display something)
Then check your have right on your in.gff file... and it contains something.

You might try also version 1.2.0 instead of 1.0.0

**Comment by MrLocuace** [comment]
I downloaded that .pl script because without it it did not work and I thought it would work in this way, but it does not..

[me@midway3-login4 tc]$ module load singularity
[me@midway3-login4 tc]$ singularity run agat_1.0.0--pl5321hdfd78af_0.sif
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

Singularity> agat_convert_sp_gxf2gxf.pl --help
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.UTF-8",
	LC_CTYPE = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Using standard /usr/local/lib/perl5/site_perl/auto/share/dist/AGAT/config.yaml file

 ------------------------------------------------------------------------------
|   Another GFF Analysis Toolkit (AGAT) - Version: v1.0.0                      |
|   https://github.com/NBISweden/AGAT                                          |
|   National Bioinformatics Infrastructure Sweden (NBIS) - www.nbis.se         |
 ------------------------------------------------------------------------------


Name:
    agat_convert_sp_gxf2gxf.pl

Description:
    This script fixes and/or standardizes any GTF/GFF file into full sorted
    GTF/GFF file. It AGAT parser removes duplicate features, fixes
    duplicated IDs, adds missing ID and/or Parent attributes, deflates
    factorized attributes (attributes with several parents are duplicated
    with uniq ID), add missing features when possible (e.g. add exon if only
    CDS described, add UTR if CDS and exon described), fix feature locations
    (e.g. check exon is embedded in the parent features mRNA, gene), etc...

    All AGAT's scripts with the _sp_ prefix use the AGAT parser, before to
    perform any supplementary task. So, it is not necessary to run this
    script prior the use of any other _sp_ script.

Usage:
        agat_convert_sp_gxf2gxf.pl -g infile.gff [ -o outfile ]
        agat_convert_sp_gxf2gxf.pl --help

Options:
    -g, --gtf, --gff or --gxf
            String - Input GTF/GFF file. Compressed file with .gz extension
            is accepted.

    -v      Integer - Verbose option. To modify verbosity. Default is 1. 0
            is quiet, 2 and 3 are increasing verbosity.

    -o or --output
            String - Output GFF file. If no output file is specified, the
            output will be written to STDOUT.

    -h or --help
            Boolean - Display this helpful text.

Feedback:
  Did you find a bug?:
    Do not hesitate to report bugs to help us keep track of the bugs and
    their resolution. Please use the GitHub issue tracking system available
    at this address:

                https://github.com/NBISweden/AGAT/issues

     Ensure that the bug was not already reported by searching under Issues.
     If you're unable to find an (open) issue addressing the problem, open a new one.
     Try as much as possible to include in the issue when relevant:
     - a clear description,
     - as much relevant information as possible,
     - the command used,
     - a data sample,
     - an explanation of the expected behaviour that is not occurring.

  Do you want to contribute?:
    You are very welcome, visit this address for the Contributing
    guidelines:
    https://github.com/NBISweden/AGAT/blob/master/CONTRIBUTING.md

Yes, the in.gff file does contain what it should contain

I changed the version but I ge the same

Thank you

**Comment by Juke34** [comment]
Ok the help works, so the tool is well installed and aviable via singularity.
In the singularity prompt, can you see your gff file? Can you read e.g. via a `cat` command?

**Comment by MrLocuace** [comment]
No, it can't:

[me@midway3-login4 tc]$ singularity run agat_1.2.0--pl5321hdfd78af_0.sif
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Singularity> cat in.gff
cat: can't open 'in.gff': No such file or directory

**Comment by Juke34** [comment]
But can you when you are out of the container? Try chmod +x in.gff

**Comment by MrLocuace** [comment]
[me@midway3-login4 tc]$ chmod +x in.gff
[me@midway3-login4 tc]$ singularity run agat_1.2.0--pl5321hdfd78af_0.sif
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Singularity> agat_convert_sp_gxf2gxf.pl --gff in.gff -o out.gtf
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.UTF-8",
	LC_CTYPE = "en_US.UTF-8",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
Using standard /usr/local/lib/perl5/site_perl/auto/share/dist/AGAT/agat_config.yaml file
File out.gtf already exist.

Now, if I specify the outdir path:

Singularity> agat_convert_sp_gxf2gxf.pl --gff in.gff -o /project/PI/USERS/me/czi/data/tc/out.gtf
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.UTF-8",
	LC_CTYPE = "en_US.UTF-8",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
Using standard /usr/local/lib/perl5/site_perl/auto/share/dist/AGAT/agat_config.yaml file
Could not open file '/project/PI/USERS/me/czi/data/tc/out.gtf' No such file or directory at /usr/local/lib/perl5/site_perl/AGAT/OmniscientO.pm line 67.

**Comment by Juke34** [comment]
`File out.gtf already exist.`
Just removed it and run it again, or change the output name.

Then if you do not succeed it means you probably do not have the proper rights in the folder you are working. You must chmod or chown it with proper rights. The problems are not AGAT related but seem to be basic linux rights on files and folders.
