### ISSUE TITLE
New script - add attributes from csv/tsv

### ISSUE THREAD

**Issue by Juke34** [NBISweden/AGAT#44]
Requested by @mostafaabuzaid25 here #43 

Add one more simple tool which add attribute information form csv/tsv for example:
if have annotation tsv:
```
gend_id annot_type1
gene1 anot_x
gene2 anoty
gene3 anotz
```

and a gff with attributes:
```
ID=gene1
ID=gene2
```

We will get with the tsv data added:
```
ID=gene1;annot_type1=anot_x
ID=gene2;annot_type1=anot_y
```

**Comment by Juke34** [comment]
No need to use omniscient for it, sequential approach would be fine.
So parsing the tsv and holding the info in a hash, then read line by line the gff and adding info when ID is met.

**Comment by mostafaabuzaid25** [comment]
> No need to use omniscient for it, sequential approach would be fine.
> So parsing the tsv and holding the info in a hash, then read line by line the gff and adding info when ID is met.

can you help me to write that script because i am not computer science guy  my background is biology

**Comment by Juke34** [comment]
Do you code in perl or python?

**Comment by mostafaabuzaid25** [comment]
> Do you code in perl or python?

mostly i using Perl tools

**Comment by Juke34** [comment]
If you wish you can try. You must fork the repo then clone your fork on your computer. Use an Agat sequential script as template ( agat_sq prefix) and adapt it. The script should first parse the tsv file, and save it in a hash (tsv_hash). Main keys of your hash is the feature ID column, second keys other column header, and values are related values.
Then you parse sequentially the gff and when you encounter an ID existing in the tsv_hash you add the values among the features attributes  before to print the  feature.

**Comment by mostafaabuzaid25** [comment]
> If you wish you can try. You must fork the repo then clone your fork on your computer. Use an Agat sequential script as template ( agat_sq prefix) and adapt it. The script should first parse the tsv file, and save it in a hash (tsv_hash). Main keys of your hash is the feature ID column, second keys other column header, and values are related values.
> Then you parse sequentially the gff and when you encounter an ID existing in the tsv_hash you add the values among the features attributes before to print the feature.

i am not quit sure i can do this my self its a bit complicated to edit one of your scripts but i will give it  a try

**Comment by Juke34** [comment]
I implemented `agat_sq_add_attributes_from_tsv.pl`, you can try it

**Comment by kcmtest** [comment]
Hello Dr @Juke34 thank you for creating this wonderfool tool I was using this utilities where my goal is to add new attributes from a tsv file to the existing gtf file. I did run based on the example you have given, in other words input as tsv file and another input as gtf file but Im not sure if I did get the right output I didn't raise a new issue as its should be a simple problem i believe unless Im doing something grossly wrong. I have asked the question [here ](https://www.biostars.org/p/9568841/) it would be really kind of you if you can have a look and let me know what I'm doing wrong

**Comment by Juke34** [comment]
Hi, yes it is just a warning to inform you about lines where you do have a missing field.
