### ISSUE TITLE
agat_sp_statistics.pl stuck and not generating output

### ISSUE THREAD

**Issue by pedrobdfp** [NBISweden/AGAT#45]
Hi!

I have a .gff3 file I obtained as an Output off Augustus, and I am trying to apply agat_sp_statistics.pl to get some gene counts and etc out of it.

However, the program gets stuck and does not generate any output, so I had to kill the process. I have allowed it many hours with 32 GB RAM available, and yet, nothing happened.

I installed it by conda, and these are the coomands I used:

agat_sp_statistics.pl --gff Augustus_unmasked_output.gff3 -o gff.stats

I also tried doing this before in case there was a formatting error of some sort:

agat_convert_sp_gxf2gxf.pl --gff Augustus_unmasked_output.gff3

This run fine and changed my file, but agat_sp_statistics still got stuck when using the modified gff3 file as imput.

 Is this a bug, or is there something with my file? I must say I have little experience and this is my first annotation, so it could very well be a silly mistake on my end.

Thanks!
Pedro

**Comment by Juke34** [comment]
Hi! Sorry for that. yes it has been reported here also #43. It is a regression present in v0.3.0 and v0.2.3. A loop related to statistics is not at all efficient. It is fixed in the master branch. I will push soon a release in bioconda. For now you can update the version you have using the master branch or use an older version in Conda.

**Comment by pedrobdfp** [comment]
Thank you for the very quick reply! I had not seen that post you link, I am sorry for the redundancy. How do I go about getting an earlier version by conda?

best;
Pedro

**Comment by Juke34** [comment]
No worries.

`conda install agat=0.2.3`

**Comment by pedrobdfp** [comment]
Thank you! it worked perfectly now!
