### ISSUE TITLE
New citations

### ISSUE THREAD

**Issue by dirkjanvw** [NBISweden/AGAT#454]
**Is your feature request related to a problem? Please describe.**
I am using a recent version of AGAT that I would like to cite; but I noticed that the most recent version on the Zenodo is only 1.2.0.

**Describe the solution you'd like**
Could you please add all novel releases since 1.2.0 on Zenodo too for citation?

**Describe alternatives you've considered**

**Additional context**

**Comment by Juke34** [comment]
Thank you for pointing this issue. I reactivated Zenodo to automatically create DOI for any new release. I manually added release v1.3.0 and v.1.4.0.
I didn't add the in between versions that might not be recommended to use in certain circumstances. Hope this is fine to you. If not ping me I will add extra versions.
