### ISSUE TITLE
Undefined subroutine &main::prepare_gffout called at agat_convert_sp_gxf2gxf.pl line 52.

### ISSUE THREAD

**Issue by karthickbrlab** [NBISweden/AGAT#459]
hi

I have installed agat manually from github.
Im trying to do gtf to gff3 conversion.
perl agat_convert_sp_gxf2gxf.pl -g braker.gtf -o br

 ------------------------------------------------------------------------------
|   Another GFF Analysis Toolkit (AGAT) - Version: v1.4.0                      |
|   https://github.com/NBISweden/AGAT                                          |
|   National Bioinformatics Infrastructure Sweden (NBIS) - www.nbis.se         |
 ------------------------------------------------------------------------------
=> Using standard /home/linuxbrew/.linuxbrew/opt/perl/lib/perl5/site_perl/5.38/auto/share/dist/AGAT/agat_config.yaml config file
Undefined subroutine &main::prepare_gffout called at agat_convert_sp_gxf2gxf.pl line 52.

**Comment by Juke34** [comment]
Seems to be related to #416

**Comment by Juke34** [comment]
AGAT Libraries are not reached. Probably installation didn't work well. The `make test` probably did not work, isn't it?
Feel free to re-open the issue if necessary.
