### ISSUE TITLE
Can't call method "strand" on an undefined value

### ISSUE THREAD

**Issue by ChemaMD** [NBISweden/AGAT#47]
Hi,

First of all, congratulations for such a nice and useful piece of software! I'm preparing my GFF3 genome annotation with AGAT to then use EMBLmyGFF3 and submit an annotated genome to ENA. If I run EMBLmyGFF3 on my original GFF3, there are errors of duplicated features (mRNAs and exons) and so I am running the AGAT script `agat_sp_fix_features_locations_duplicated.pl`. However, I am encountering an error, which I don't know how to fix:

    agat_sp_gxf_to_gff3.pl -g Owenia_annotation_v102519.gff3 -o Owenia_annotation_v102519_AGATchecked.gff3
    agat_sp_fix_features_locations_duplicated.pl -f Owenia_annotation_v102519_AGATchecked_noDups.gff3 -o Owenia_annotation_v102519_AGATchecked_fixduplications.gff3

The output is:

    06/03/2020 at 18h41m26s
    usage: /Users/Chema/src/miniconda2/envs/AGAT/bin/agat_sp_fix_features_locations_duplicated.pl -f Owenia_annotation_v102519_AGATchecked_noDups.gff3 -o Owenia_annotation_v102519_AGATchecked_fixduplications.gff3

    Parse file Owenia_annotation_v102519_AGATchecked_noDups.gff3
    ********************************************************************************
    *                              - Start parsing -                               *
    ********************************************************************************
    -------------------------- parse options and metadata --------------------------
    => Accessing the feature level json files
	Using standard /Users/Chema/src/miniconda2/envs/AGAT/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_level1.json file
	Using standard /Users/Chema/src/miniconda2/envs/AGAT/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_level2.json file
	Using standard /Users/Chema/src/miniconda2/envs/AGAT/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_level3.json file
	Using standard /Users/Chema/src/miniconda2/envs/AGAT/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_spread.json file
    => merge_locus option deactivated
    => Accessing Ontology
	No ontology accessible from the gff file header!
	We use the SOFA ontology distributed with AGAT:
		/Users/Chema/src/miniconda2/envs/AGAT/lib/site_perl/5.26.2/auto/share/dist/AGAT/so.obo
	Read ontology /Users/Chema/src/miniconda2/envs/AGAT/lib/site_perl/5.26.2/auto/share/dist/AGAT/so.obo:
		4 root terms, and 2472 total terms, and 1436 leaf terms
	Filtering ontology:
		We found 1757 terms that are sequence_feature or is_a child of it.
    -------------------------------- parse features --------------------------------
    => GFF version parser used: 3
    ********************************************************************************
    *                               - End parsing -                                *
    *                             done in 252 seconds                              *
    ********************************************************************************

    ********************************************************************************
    *                               - Start checks -                               *
    ********************************************************************************
    ---------------------------- Check1: feature types -----------------------------
    ----------------------------------- ontology -----------------------------------
    All feature types in agreement with the Ontology.
    ------------------------------------- agat -------------------------------------
    AGAT can deal with all the encountered feature types (3rd column)
    ------------------------------ done in 0 seconds -------------------------------

    ------------------------------ Check2: duplicates ------------------------------
    None found
    ------------------------------ done in 0 seconds -------------------------------

    -------------------------- Check3: sequential bucket ---------------------------
    Nothing to check as sequential !
    ------------------------------ done in 0 seconds -------------------------------

    --------------------------- Check4: l2 linked to l3 ----------------------------
    No problem found
    ------------------------------ done in 1 seconds -------------------------------

    --------------------------- Check5: l1 linked to l2 ----------------------------
    No problem found
    ------------------------------ done in 0 seconds -------------------------------

    --------------------------- Check6: remove orphan l1 ---------------------------
    We remove only those not supposed to be orphan
    None found
    ------------------------------ done in 0 seconds -------------------------------

    ----------------------------- Check7: check exons ------------------------------
    No exons created
    No exons locations modified
    No supernumerary exons removed
    No level2 locations modified
    ------------------------------ done in 16 seconds ------------------------------

    ------------------------------ Check8: check utrs ------------------------------
    No UTRs created
    No UTRs locations modified
    No supernumerary UTRs removed
    ------------------------------ done in 10 seconds ------------------------------

    ------------------------- Check9: all level2 locations -------------------------
    No problem found
    ------------------------------ done in 8 seconds -------------------------------

    ------------------------ Check10: all level1 locations -------------------------
    No problem found
    ------------------------------ done in 1 seconds -------------------------------

    ---------------------- Check11: remove identical isoforms ----------------------
    None found
    ------------------------------ done in 0 seconds -------------------------------
    ********************************************************************************
    *                                - End checks -                                *
    *                              done in 36 seconds                              *
    ********************************************************************************

    => OmniscientI total time: 288 seconds
    Owenia_annotation_v102519_AGATchecked_noDups.gff3 file parsed
    case3 (reshaping genes): nbisl1-transcript-33012 and nbisl1-transcript-33011 have same location
    case3 (reshaping genes): nbisl1-transcript-33131 and nbisl1-transcript-33132 have same location
    case3 (reshaping genes): nbisl1-transcript-33272 and nbisl1-transcript-33273 have same location
    case3 (reshaping genes): nbisl1-transcript-33285 and nbisl1-transcript-33284 have same location
    case3 (reshaping genes): nbisl1-transcript-33330 and nbisl1-transcript-33329 have same location
    Can't call method "strand" on an undefined value at /Users/Chema/src/miniconda2/envs/AGAT/lib/site_perl/5.26.2/AGAT/OmniscientI.pm line 2667.`

I have tried to remove the last case (removing one of the conflicting transcripts) and re-running the script, but still it crashes with the same error (but the parsed transcripts are different each case).

Any idea what might be causing this issue?

Thank you very much for your help,

Chema

**Comment by Juke34** [comment]
Interesting, you refer to agat_sp_gxf_to_gff3.pl while I have replaced that script by agat_convert_sp_gxf2gxf.pl. But the output you show is from the last release without the agat_sp_gxf_to_gff3.pl script...
Could you send a sample or the whole gff file?

**Comment by ChemaMD** [comment]
Ah, I didn't recognised there was that change of script (I used a few months ago AGAT to generate single isoform proteomes and just followed the script I had from then).

I attached the zipped GFF3 (It was generated through a Mikado+Augustus+PASA pipeline)

Thanks!

[Owenia_annotation_v102519.gff3.zip](https://github.com/NBISweden/AGAT/files/4725576/Owenia_annotation_v102519.gff3.zip)

**Comment by Juke34** [comment]
Hum actually your file is parsed sequentially by AGAT and as there is no Parent attribute for the transcript features, isoforms are attach to different genes, this mess up the `agat_sp_fix_features_locations_duplicated.pl` script.
```
Scaffold03	.	transcript	11706118	11713920	.	+	.	ID=Ofus.G031709.2;geneID=Ofus.G031709
Scaffold03	.	exon	11706118	11706222	.	+	.	Parent=Ofus.G031709.2
Scaffold03	.	exon	11708661	11709079	.	+	.	Parent=Ofus.G031709.2
Scaffold03	.	exon	11709276	11709530	.	+	.	Parent=Ofus.G031709.2
Scaffold03	.	exon	11710131	11710351	.	+	.	Parent=Ofus.G031709.2
Scaffold03	.	exon	11712062	11712242	.	+	.	Parent=Ofus.G031709.2
Scaffold03	.	exon	11712907	11713920	.	+	.	Parent=Ofus.G031709.2
Scaffold03	.	CDS	11708677	11709079	.	+	0	Parent=Ofus.G031709.2
Scaffold03	.	CDS	11709276	11709530	.	+	2	Parent=Ofus.G031709.2
Scaffold03	.	CDS	11710131	11710351	.	+	2	Parent=Ofus.G031709.2
Scaffold03	.	CDS	11712062	11712242	.	+	0	Parent=Ofus.G031709.2
Scaffold03	.	CDS	11712907	11713920	.	+	2	Parent=Ofus.G031709.2
Scaffold03	.	transcript	11706135	11713920	.	+	.	ID=Ofus.G031709.1;geneID=Ofus.G031709
Scaffold03	.	exon	11706135	11706222	.	+	.	Parent=Ofus.G031709.1
Scaffold03	.	exon	11708661	11709079	.	+	.	Parent=Ofus.G031709.1
Scaffold03	.	exon	11709279	11709530	.	+	.	Parent=Ofus.G031709.1
Scaffold03	.	exon	11710131	11710351	.	+	.	Parent=Ofus.G031709.1
Scaffold03	.	exon	11712062	11712242	.	+	.	Parent=Ofus.G031709.1
Scaffold03	.	exon	11712907	11713920	.	+	.	Parent=Ofus.G031709.1
Scaffold03	.	CDS	11708677	11709079	.	+	0	Parent=Ofus.G031709.1
Scaffold03	.	CDS	11709279	11709530	.	+	2	Parent=Ofus.G031709.1
Scaffold03	.	CDS	11710131	11710351	.	+	2	Parent=Ofus.G031709.1
Scaffold03	.	CDS	11712062	11712242	.	+	0	Parent=Ofus.G031709.1
Scaffold03	.	CDS	11712907	11713920	.	+	2	Parent=Ofus.G031709.1
Scaffold03	.	transcript	11706135	11713920	.	+	.	ID=Ofus.G031709.3;geneID=Ofus.G031709
Scaffold03	.	exon	11706135	11706222	.	+	.	Parent=Ofus.G031709.3
Scaffold03	.	exon	11708661	11709079	.	+	.	Parent=Ofus.G031709.3
Scaffold03	.	exon	11709279	11709530	.	+	.	Parent=Ofus.G031709.3
Scaffold03	.	exon	11710203	11710351	.	+	.	Parent=Ofus.G031709.3
Scaffold03	.	exon	11712062	11712242	.	+	.	Parent=Ofus.G031709.3
Scaffold03	.	exon	11712907	11713920	.	+	.	Parent=Ofus.G031709.3
Scaffold03	.	CDS	11708677	11709079	.	+	0	Parent=Ofus.G031709.3
Scaffold03	.	CDS	11709279	11709530	.	+	2	Parent=Ofus.G031709.3
Scaffold03	.	CDS	11710203	11710351	.	+	2	Parent=Ofus.G031709.3
Scaffold03	.	CDS	11712062	11712242	.	+	0	Parent=Ofus.G031709.3
Scaffold03	.	CDS	11712907	11713920	.	+	2	Parent=Ofus.G031709.3
```
```
Scaffold03	.	gene	11706118	11713920	.	+	.	ID=nbisL1-transcript-6266;geneID=Ofus.G031709
Scaffold03	.	transcript	11706118	11713920	.	+	.	ID=Ofus.G031709.2;Parent=nbisL1-transcript-6266;geneID=Ofus.G031709
Scaffold03	.	exon	11706118	11706222	.	+	.	ID=exon-45188;Parent=Ofus.G031709.2
Scaffold03	.	exon	11708661	11709079	.	+	.	ID=exon-45189;Parent=Ofus.G031709.2
Scaffold03	.	exon	11709276	11709530	.	+	.	ID=exon-45190;Parent=Ofus.G031709.2
Scaffold03	.	exon	11710131	11710351	.	+	.	ID=exon-45191;Parent=Ofus.G031709.2
Scaffold03	.	exon	11712062	11712242	.	+	.	ID=exon-45192;Parent=Ofus.G031709.2
Scaffold03	.	exon	11712907	11713920	.	+	.	ID=exon-45193;Parent=Ofus.G031709.2
Scaffold03	.	CDS	11708677	11709079	.	+	0	ID=cds-41957;Parent=Ofus.G031709.2
Scaffold03	.	CDS	11709276	11709530	.	+	2	ID=cds-41958;Parent=Ofus.G031709.2
Scaffold03	.	CDS	11710131	11710351	.	+	2	ID=cds-41959;Parent=Ofus.G031709.2
Scaffold03	.	CDS	11712062	11712242	.	+	0	ID=cds-41960;Parent=Ofus.G031709.2
Scaffold03	.	CDS	11712907	11713920	.	+	2	ID=cds-41961;Parent=Ofus.G031709.2
Scaffold03	.	five_prime_UTR	11706118	11706222	.	+	.	ID=nbis-five_prime_utr-9870;Parent=Ofus.G031709.2
Scaffold03	.	five_prime_UTR	11708661	11708676	.	+	.	ID=nbis-five_prime_utr-9870;Parent=Ofus.G031709.2
Scaffold03	.	gene	11706135	11713920	.	+	.	ID=nbisL1-transcript-6267;geneID=Ofus.G031709
Scaffold03	.	transcript	11706135	11713920	.	+	.	ID=Ofus.G031709.1;Parent=nbisL1-transcript-6267;geneID=Ofus.G031709
Scaffold03	.	exon	11706135	11706222	.	+	.	ID=exon-45194;Parent=Ofus.G031709.1
Scaffold03	.	exon	11708661	11709079	.	+	.	ID=exon-45195;Parent=Ofus.G031709.1
Scaffold03	.	exon	11709279	11709530	.	+	.	ID=exon-45196;Parent=Ofus.G031709.1
Scaffold03	.	exon	11710131	11710351	.	+	.	ID=exon-45197;Parent=Ofus.G031709.1
Scaffold03	.	exon	11712062	11712242	.	+	.	ID=exon-45198;Parent=Ofus.G031709.1
Scaffold03	.	exon	11712907	11713920	.	+	.	ID=exon-45199;Parent=Ofus.G031709.1
Scaffold03	.	CDS	11708677	11709079	.	+	0	ID=cds-41962;Parent=Ofus.G031709.1
Scaffold03	.	CDS	11709279	11709530	.	+	2	ID=cds-41963;Parent=Ofus.G031709.1
Scaffold03	.	CDS	11710131	11710351	.	+	2	ID=cds-41964;Parent=Ofus.G031709.1
Scaffold03	.	CDS	11712062	11712242	.	+	0	ID=cds-41965;Parent=Ofus.G031709.1
Scaffold03	.	CDS	11712907	11713920	.	+	2	ID=cds-41966;Parent=Ofus.G031709.1
Scaffold03	.	five_prime_UTR	11706135	11706222	.	+	.	ID=nbis-five_prime_utr-6125;Parent=Ofus.G031709.1
Scaffold03	.	five_prime_UTR	11708661	11708676	.	+	.	ID=nbis-five_prime_utr-6125;Parent=Ofus.G031709.1
Scaffold03	.	gene	11706135	11713920	.	+	.	ID=nbisL1-transcript-6268;geneID=Ofus.G031709
Scaffold03	.	transcript	11706135	11713920	.	+	.	ID=Ofus.G031709.3;Parent=nbisL1-transcript-6268;geneID=Ofus.G031709
Scaffold03	.	exon	11706135	11706222	.	+	.	ID=exon-45200;Parent=Ofus.G031709.3
Scaffold03	.	exon	11708661	11709079	.	+	.	ID=exon-45201;Parent=Ofus.G031709.3
Scaffold03	.	exon	11709279	11709530	.	+	.	ID=exon-45202;Parent=Ofus.G031709.3
Scaffold03	.	exon	11710203	11710351	.	+	.	ID=exon-45203;Parent=Ofus.G031709.3
Scaffold03	.	exon	11712062	11712242	.	+	.	ID=exon-45204;Parent=Ofus.G031709.3
Scaffold03	.	exon	11712907	11713920	.	+	.	ID=exon-45205;Parent=Ofus.G031709.3
Scaffold03	.	CDS	11708677	11709079	.	+	0	ID=cds-41967;Parent=Ofus.G031709.3
Scaffold03	.	CDS	11709279	11709530	.	+	2	ID=cds-41968;Parent=Ofus.G031709.3
Scaffold03	.	CDS	11710203	11710351	.	+	2	ID=cds-41969;Parent=Ofus.G031709.3
Scaffold03	.	CDS	11712062	11712242	.	+	0	ID=cds-41970;Parent=Ofus.G031709.3
Scaffold03	.	CDS	11712907	11713920	.	+	2	ID=cds-41971;Parent=Ofus.G031709.3
Scaffold03	.	five_prime_UTR	11706135	11706222	.	+	.	ID=nbis-five_prime_utr-10960;Parent=Ofus.G031709.3
Scaffold03	.	five_prime_UTR	11708661	11708676	.	+	.	ID=nbis-five_prime_utr-10960;Parent=Ofus.G031709.3
```

To fix that two solutions:  
 * replace in the original file `geneID` by `Parent` e.g using a `sed` command
 * or run agat_convert_sp_gxf2gxf.pl with -`-c geneID` (it specifies AGAT that the tag geneID has to be used to link features together )

Then I guess you should be able to run `agat_sp_fix_features_locations_duplicated.pl` successfully.

**Comment by ChemaMD** [comment]
Thanks @Juke34 . That solved the issue! I'm now getting a few 3'UTR or 5'UTR still duplicated, but those I can fix by hand.

**Comment by ChemaMD** [comment]
Hi @Juke34 , I'm now getting this particular error when converting to EMBL flat format from the AGAT fixed_features_locations_duplicated GFF3:

    ERROR: "5'UTR" Features locations are duplicated - consider merging qualifiers. [ line: 33334 of Owenia_annotation_v102519.embl.bz2,  line: 33290 of Owenia_annotation_v102519.embl.bz2]
    ERROR: "3'UTR" Features locations are duplicated - consider merging qualifiers. [ line: 39058 of Owenia_annotation_v102519.embl.bz2,  line: 39008 of Owenia_annotation_v102519.embl.bz2]
    ERROR: "5'UTR" Features locations are duplicated - consider merging qualifiers. [ line: 39841 of Owenia_annotation_v102519.embl.bz2,  line: 39699 of Owenia_annotation_v102519.embl.bz2]
    ERROR: "5'UTR" Features locations are duplicated - consider merging qualifiers. [ line: 46487 of Owenia_annotation_v102519.embl.bz2,  line: 46374 of Owenia_annotation_v102519.embl.bz2]
    ERROR: "5'UTR" Features locations are duplicated - consider merging qualifiers. [ line: 49216 of Owenia_annotation_v102519.embl.bz2,  line: 49159 of Owenia_annotation_v102519.embl.bz2]
    ERROR: "3'UTR" Features locations are duplicated - consider merging qualifiers. [ line: 52489 of Owenia_annotation_v102519.embl.bz2,  line: 52344 of Owenia_annotation_v102519.embl.bz2]
    ERROR: "5'UTR" Features locations are duplicated - consider merging qualifiers. [ line: 54389 of Owenia_annotation_v102519.embl.bz2,  line: 54032 of Owenia_annotation_v102519.embl.bz2]
    ERROR: Intron usually expected to be at least 10 nt long. Please check the accuracy. [ line: 73590-73593 of Owenia_annotation_v102519.embl.bz2]

There are some 5'UTRs o 3'UTRs that are shared by different gene transcripts, hence they appear duplicated. How and when do I merge qualifiers? In the AGAT step or at the EMBLmyGFF3 step?

Also, is there a way to remove the 10 nt length limit on introns?

Thanks and sorry if these are more EMBLmyGFF3-related issues (happy to close this and open one on the other repo)

Best wishes,

Chema

**Comment by Juke34** [comment]
The easiest here is to get rid of UTRs. You don't need to submit UTR and exon features, the information is indirectly held by the other features. The transcript contains the exon information it the locations and you can deduce the UTR by comparing the exons location to the CDS locations.
To get rid of the UTR you can do exactly as for the exon example [here](https://github.com/NBISweden/EMBLmyGFF3#feature-type). To access the json file to modify you need to use `--expose_translations`.
 

> Also, is there a way to remove the 10 nt length limit on introns?

You can keep short introns but you have to add a special attribute to the feature. This script will perform the necessary modifications: `agat_sp_flag_short_intron.pl`

**Comment by ChemaMD** [comment]
OK! thank you very much! Now it worked like a charm. Thanks a lot for your help and for developing all these tools!

**Comment by webbchen** [comment]
Dear developers
I'm getting the same issue but for seemingly unrelated reasons
I had merged some extra genes into a file produced by BRAKER and that produced a few duplicate features I need to remove for submission to EMBL
I ran:
`agat_convert_sp_gxf2gxf.pl -g assembly_pbs3_v1_braker_full.gff3 -c geneID -o file1.gff3`
then
`agat_sp_fix_features_locations_duplicated.pl -f file1.gff3 -o assembly_pbs3_v1_braker_full_agat_dedup.gff3` 
and after lots of ordinary output it terminates with:
(...)

\********************************************************************************
\*                                - End checks -                                *
\*                              done in 5 seconds                               
\*********************************************************************************

=> OmniscientI total time: 29 seconds
file1.gff3 file parsed
case2 (removing mRNA identic from different genes: g6489gm_br_rna.t1
case3 (reshaping genes): g3273 and g6591gm have same location
Can't call method "strand" on an undefined value at /scratch/software/miniconda3/envs/AGAT_gffs/lib/site_perl/5.26.2/AGAT/OmniscientI.pm line 3043.

Here is a part of my gff3:

contig_100_0    AUGUSTUS        gene    38269   38592   0.67    +       .       ID=g1130_br_RNA;
contig_100_0    AUGUSTUS        mRNA    38269   38592   0.67    +       .       ID=g1130_br_RNA.t1;Parent=g1130_br_RNA;
contig_100_0    AUGUSTUS        start_codon     38269   38271   .       +       0       ID=g1130_br_RNA.t1.start1;Parent=g1130_br_RNA.t1;
contig_100_0    AUGUSTUS        CDS     38269   38592   0.67    +       0       ID=g1130_br_RNA.t1.CDS1;Parent=g1130_br_RNA.t1;
contig_100_0    AUGUSTUS        exon    38269   38592   .       +       .       ID=g1130_br_RNA.t1.exon1;Parent=g1130_br_RNA.t1;
contig_100_0    AUGUSTUS        stop_codon      38590   38592   .       +       0       ID=g1130_br_RNA.t1.stop1;Parent=g1130_br_RNA.t1;
contig_100_0    AUGUSTUS        gene    44903   48115   1       +       .       ID=g3715;
contig_100_0    AUGUSTUS        mRNA    44903   48115   1       +       .       ID=g3715.t1;Parent=g3715;
contig_100_0    AUGUSTUS        exon    44903   48115   .       +       .       ID=g3715.t1.exon1;Parent=g3715.t1;
contig_100_0    AUGUSTUS        CDS     44903   48115   1       +       0       ID=g3715.t1.CDS1;Parent=g3715.t1;
contig_100_0    AUGUSTUS        start_codon     44903   44905   .       +       0       ID=g3715.t1.start1;Parent=g3715.t1;
contig_100_0    AUGUSTUS        stop_codon      48113   48115   .       +       0       ID=g3715.t1.stop1;Parent=g3715.t1;
contig_100_0    AUGUSTUS        gene    48895   50964   1       -       .       ID=g3716;
contig_100_0    AUGUSTUS        mRNA    48895   50964   1       -       .       ID=g3716.t1;Parent=g3716;
contig_100_0    AUGUSTUS        stop_codon      48895   48897   .       -       0       ID=g3716.t1.stop1;Parent=g3716.t1;
contig_100_0    AUGUSTUS        CDS     48895   50964   1       -       0       ID=g3716.t1.CDS1;Parent=g3716.t1;
contig_100_0    AUGUSTUS        exon    48895   50964   .       -       .       ID=g3716.t1.exon1;Parent=g3716.t1;
contig_100_0    AUGUSTUS        start_codon     50962   50964   .       -       0       ID=g3716.t1.start1;Parent=g3716.t1;
contig_100_0    GeneMark.hmm    gene    51202   52132   .       -       .       ID=g4675gm_br_RNA;
contig_100_0    GeneMark.hmm    mRNA    51202   52132   .       -       .       ID=g4675gm_br_RNA.t1;Parent=g4675gm_br_RNA;
contig_100_0    GeneMark.hmm    exon    51202   51497   .       -       .       ID=g4675gm_br_RNA.t1.exon1;Parent=g4675gm_br_RNA.t1;
contig_100_0    GeneMark.hmm    CDS     51202   51497   .       -       2       ID=g4675gm_br_RNA.t1.CDS1;Parent=g4675gm_br_RNA.t1;
contig_100_0    AUGUSTUS        intron  51498   51600   1       -       .       ID=g3717.t1.intron1;Parent=g3717.t1;
contig_100_0    AUGUSTUS        CDS     51601   52132   1       -       0       ID=g3717.t1.CDS2;Parent=g3717.t1;
contig_100_0    AUGUSTUS        exon    51601   52132   .       -       .       ID=g3717.t1.exon2;Parent=g3717.t1;
contig_100_0    GeneMark.hmm    exon    51601   52132   .       -       .       ID=g4675gm_br_RNA.t1.exon2;Parent=g4675gm_br_RNA.t1;
contig_100_0    GeneMark.hmm    CDS     51601   52132   .       -       0       ID=g4675gm_br_RNA.t1.CDS2;Parent=g4675gm_br_RNA.t1;
contig_100_0    AUGUSTUS        start_codon     52130   52132   .       -       0       ID=g3717.t1.start1;Parent=g3717.t1;
contig_100_0    AUGUSTUS        gene    52379   53418   1       -       .       ID=g3718;
contig_100_0    AUGUSTUS        mRNA    52379   53418   1       -       .       ID=g3718.t1;Parent=g3718;
contig_100_0    AUGUSTUS        exon    52379   52425   .       -       .       ID=g3718.t1.exon1;Parent=g3718.t1;
contig_100_0    AUGUSTUS        stop_codon      52379   52381   .       -       0       ID=g3718.t1.stop1;Parent=g3718.t1;
contig_100_0    AUGUSTUS        CDS     52379   52425   1       -       2       ID=g3718.t1.CDS1;Parent=g3718.t1;
contig_100_0    AUGUSTUS        intron  52426   52499   1       -       .       ID=g3718.t1.intron1;Parent=g3718.t1;
contig_100_0    AUGUSTUS        exon    52500   52827   .       -       .       ID=g3718.t1.exon2;Parent=g3718.t1;
contig_100_0    AUGUSTUS        CDS     52500   52827   1       -       0       ID=g3718.t1.CDS2;Parent=g3718.t1;
contig_100_0    AUGUSTUS        intron  52828   52892   1       -       .       ID=g3718.t1.intron2;Parent=g3718.t1;
contig_100_0    AUGUSTUS        exon    52893   52970   .       -       .       ID=g3718.t1.exon3;Parent=g3718.t1;
contig_100_0    AUGUSTUS        CDS     52893   52970   1       -       0       ID=g3718.t1.CDS3;Parent=g3718.t1;
contig_100_0    AUGUSTUS        intron  52971   53039   1       -       .       ID=g3718.t1.intron3;Parent=g3718.t1;
contig_100_0    AUGUSTUS        CDS     53040   53075   1       -       0       ID=g3718.t1.CDS4;Parent=g3718.t1;
contig_100_0    AUGUSTUS        exon    53040   53075   .       -       .       ID=g3718.t1.exon4;Parent=g3718.t1;
contig_100_0    AUGUSTUS        intron  53076   53161   1       -       .       ID=g3718.t1.intron4;Parent=g3718.t1;
contig_100_0    AUGUSTUS        CDS     53162   53249   1       -       1       ID=g3718.t1.CDS5;Parent=g3718.t1;
contig_100_0    AUGUSTUS        exon    53162   53249   .       -       .       ID=g3718.t1.exon5;Parent=g3718.t1;
contig_100_0    AUGUSTUS        intron  53250   53347   1       -       .       ID=g3718.t1.intron5;Parent=g3718.t1;
contig_100_0    AUGUSTUS        exon    53348   53418   .       -       .       ID=g3718.t1.exon6;Parent=g3718.t1;
contig_100_0    AUGUSTUS        CDS     53348   53418   1       -       0       ID=g3718.t1.CDS6;Parent=g3718.t1;
contig_100_0    AUGUSTUS        start_codon     53416   53418   .       -       0       ID=g3718.t1.start1;Parent=g3718.t1;
(...)

Unlike in the case above, the description for gene just contains an  "ID", but no "geneID" thereafter.

**Comment by Juke34** [comment]
Could you provide your input file? I will have a look.

**Comment by webbchen** [comment]
Good morning!

I updated agat yesterday (conda update agat) and the problem persists. How can I send you the file without sharing it with everyone else on here?

**Comment by webbchen** [comment]
Any news on the issue? Did you find the file I attached?

**Comment by Juke34** [comment]
It should be fixed in the master branch. Follow those instruction: https://agat.readthedocs.io/en/latest/troubleshooting.html#how-to-use-a-version-of-agat-from-a-specific-branch

**Comment by webbchen** [comment]
Hi Juke
It works when running it with -m 1,3 but not when -m is unspecified.

**Comment by webbchen** [comment]
Update: running it with-m1 to 4 works, setting -m to 5 or including 5 or not specifying it at all, makes it keel over, like here:
`case5 (reshaping genes): g2150 and g10471gm have same location
Can't call method "strand" on an undefined value at /scratch/software/miniconda3/envs/AGAT_gffs/lib/site_perl/5.26.2/AGAT/OmniscientI.pm line 3043.`

**Comment by Juke34** [comment]
Yes it is a case not yet handled, but I will add a fix. But in your case I think AGAT will not be able to fix all problems, you will have to make manual modification. Indeed you have gene models from genemark and Augustus that slighly differ in the exon/cds end or start location in internal exon/cds, and do not have UTRs. I will add a log to be able to point those case easily, but I'm afraid you will have a lot of them.
Maybe using a tool like Evidence Modeler can help to remove that kind of redundancy and keep only the best gene model.
You should have a look in a genome browser for a better feeling.

**Comment by webbchen** [comment]
Thank you for the feedback and for looking into it! I followed your suggestions and threw out the offending genes manually.  It solved the problem for the time being.
