### ISSUE TITLE
agat_convert_genscan2gff: --inflate-off  is not a parameter

### ISSUE THREAD

**Issue by Leila011** [NBISweden/AGAT#477]
**Describe the bug**
In agat_convert_genscan2gff, the help mention a parameter `--inflate-off`, it is also in the list of parameters in the source code but doe snot seems to be use anywhere in the code.

**General (please complete the following information):**
- AGAT version: 1.4.0
- AGAT installation/use: container from quay.io
- OS: FEDORA

**To Reproduce**
docker run quay.io/biocontainers/agat:1.4.0--pl5321hdfd78af_0 agat_convert_genscan2gff.pl --help
[agat_convert_genscan2gff source code](https://github.com/NBISweden/AGAT/blob/83641ef2d0a815a783b64f204cac3ed2cec44818/bin/agat_convert_genscan2gff.pl#L289C11-L289C22)

**Expected behavior**
Parameters listed in the help should exists

**Screenshots**

**Additional context**

**Comment by Juke34** [comment]
Thank you for the feedback. This is a remaining from another script used to develop this one. This has no place here. I will remove that.

**Comment by Juke34** [comment]
Fixed in last PR
