### ISSUE TITLE
Issue in finding required dependencies

### ISSUE THREAD

**Issue by timregan** [NBISweden/AGAT#48]
Hi, 
I'm having issues installing and running AGAT. As I only need to run one script (agat_sp_keep_longest_isoform.pl), I decided to install any dependencies as I required them.  This is because I was running into space issues (Disk quota exceeded) when all dependencies were automatically installed. 

I've installed AGAT using conda specifying "--no-deps" and installed the perl dependencies, R, etc. using conda separately.
When I try to call "agat_sp_keep_longest_isoform.pl", I get the following error:
"Can't locate Bio/Tools/GFF.pm in @INC (you may need to install the Bio::Tools::GFF module)"

This occurred with a couple of other modules, such as "List::Moreutils". I solved this problem by installing the programs to my conda environment, in this case "perl-list-moreutils".
I can't find a conda installation for Bio::Tools::GFF, although I suspect there may be other issues. 

Do you have any idea what might be wrong, or have a minimal installation workaround to allow me to run agat_sp_keep_longest_isoform.pl?

Many thanks,
Tim

**Comment by Juke34** [comment]
Bio::Tools::GFF is part of Bioperl, you should install Bioperl too.

**Comment by timregan** [comment]
Thanks very much for the speedy reply.
Unfortunately, Bioperl was installed already. These are the perl dependencies I had installed (from your installation instructions): 
"conda install -c bioconda perl-bioperl perl-clone perl-graph perl-lwp-simple perl-statistics-r perl-json perl-carp perl-sort-naturally perl-file-share perl-file-sharedir-install --no-deps"

**Comment by Juke34** [comment]
Then something went wrong when installing Bioperl. Can you check doing `conda list` to see if bioperl is well installed?

You can create a script.sh that you make executable with this code 
```
#!/bin/bash

if [[ $# != 1 ]];then
    echo "usage example: ./script Bio::Seq"
    exit
fi

perl -M${1} -le "\$mname=\"${1}.pm\";\$mname=~s#::#/#g;print \"$1 INSTALLED AT \$INC{\$mname}\";" 2>/dev/null || echo "${1} NOT INSTALLED"
```

Then execute:
`./script.sh Bio::Tools::GFF`

**Comment by Juke34** [comment]
You can re-install perl-bioperl without --no-deps, maybe it could solve the issue.

**Comment by timregan** [comment]
So when I run that script I get "Bio::Tools::GFF NOT INSTALLED". 
When I try to install Bioperl without --no-deps, 271 dependencies are installed. This runs out of space unfortunately..

**Comment by Juke34** [comment]
Then you should try to use cpanm to install Bio::Tools::GFF in this conda env

**Comment by timregan** [comment]
I have 1.5Gb space on my home drive and >10Gb in my conda env dir. 
But I'm getting the same error of disk quota exceeded when I attempt running from CPAN, even when I set the installation to the conda env dir. 
I feel like it shouldn't really require that much space? But I'm not sure what else it could be. 

Anyway, I'd hoped the problem might have sounded familiar, but it seems like it's something on my end specifically... Let me tinker with it and I'll let you know if I manage to solve it.
Thanks again for the help.
T

**Comment by Juke34** [comment]
The AGAT conda env takes ~1.2 GB. Either you have installed many other things in the same env, or you have other envs that take the space. To list the envs you have in your conda run `conda env list` then you can remove what ever env you feel you don't need anymore (remove the agat one too to start properly the installation from scratch). to remove an env `conda env remove --name env_name`. If you have installed all tools in the `base` env you should maybe clean it or revert it to the initial state and install tools you usually use in separate dedicated envs.

**Comment by timregan** [comment]
Ok, I got there in the end...
Without setting "--no-deps", I was being asked to install >270 dependencies (see atatched). The most problematic (huge) one was "libdb", which is where installation failed due to disk space. 

I got around this by installing each module through conda individually with "--no-deps" until I no longer received error messages when I called the script. 
Basically, this is what you need:

cd <your/drive>
conda install --no-deps -c bioconda -p <your/drive> agat\
perl perl-bioperl perl-bioperl-core perl-exporter-tiny perl-list-moreutils perl-list-moreutils-xs perl-try-tiny \
perl-file-sharedir perl-class-inspector perl-file-sort perl-sort-naturally perl-lwp-protocol-https perl-lwp-mediatypes \
perl-libwww-perl perl-net-http perl-http-cookies perl-http-daemon perl-http-date perl-http-message perl-http-negotiate \
perl-uri perl-graph perl-clone perl-json perl-statistics-r perl-regexp-common perl-ipc-run
#change the header in the script from "#!/usr/bin/env perl" to "<your/drive>/bin/perl"
bin/agat_sp_keep_longest_isoform.pl --help
#Success!

Thanks again for the support. 
Hopefully this might help if anyone else gets stuck in this situation.

[Conda_dependencies.txt](https://github.com/NBISweden/AGAT/files/4753136/Conda_dependencies.txt)
Best wishes,
Tim

**Comment by Juke34** [comment]
Thank you for your feedback.
