### ISSUE TITLE
perl 5.38 agat1.4 blankfile

### ISSUE THREAD

**Issue by 18700951101** [NBISweden/AGAT#485]
------------------------------------------------------------------------------
|   Another GFF Analysis Toolkit (AGAT) - Version: v1.4.0                      |
|   https://github.com/NBISweden/AGAT                                          |
|   National Bioinformatics Infrastructure Sweden (NBIS) - www.nbis.se         |
 ------------------------------------------------------------------------------
=> Using standard /home/cml/miniconda3/envs/agat/lib/perl5/site_perl/auto/share/dist/AGAT/agat_config.yaml config file
The test to apply is Wrong: !.
We want something among this list: <,>,<=,>=,! or =.

**Comment by Juke34** [comment]
Hi,
What script provided this error?

**Comment by Juke34** [comment]
I think out has been resolved in v1.4.1
