### ISSUE TITLE
gff2gtf converter

### ISSUE THREAD

**Issue by Damirit** [NBISweden/AGAT#49]
Greetings,

It seems I am unable to make gff2gtf converter to work. This is wat I get with the test file:

=> OmniscientI total time: 2 seconds
'cp' is not recognized as an internal or external command,
operable program or batch file.
'sed' is not recognized as an internal or external command,
operable program or batch file.
The process cannot access the file because it is being used by another process.
'rm' is not recognized as an internal or external command,
operable program or batch file.
Bye Bye

**Comment by Juke34** [comment]
Could you show the command you run? What is your operating system.
I is related to those lines of code:  https://github.com/NBISweden/AGAT/blob/f6f0cd5b8afc3eb654f0df46efd01042a531aa9a/bin/agat_convert_sp_gff2gtf.pl#L263-L268
It is a leftover from the past (when using Bioperl parser)... it is not needed anymore.

I will fix it in the master branch. 

If you get an output file it should be fine, you can ignore the message, else you can fix it yourself by
doing `which agat_convert_sp_gff2gtf.pl` to see where is standing the script and remove those lines.

**Comment by Damirit** [comment]
Thank you!

**Comment by Damirit** [comment]
And this is the file (first 150 lines of original, cut out to be used as a test). I am beginning to thing this is not truly GFF.
[atest-or.zip](https://github.com/NBISweden/AGAT/files/4787217/atest-or.zip)

**Comment by Juke34** [comment]
It makes sense, these bash commands (see, rm,  cp...) do not exist on windows.

**Comment by Juke34** [comment]
Yes your file is particular you should first sanitise your file running this command:

```
agat_convert_sp_gxf2gxf.pl --gff atest-or.gff --ct name 
```

Then you will be able to convert to GTF successfully.

**Comment by Damirit** [comment]
It worked! And I do not know how to thank you for that! They have to include your script into every official bio-tool package.

Many, many thanks!
