### ISSUE TITLE
use AGAT::AGAT

### ISSUE THREAD

**Issue by antzellie** [NBISweden/AGAT#497]
**Describe the bug**
I installed all the code and perl modules for AGAT, and I am trying to run agat_sp_add_introns.pl
However, I keep on getting an error message (as seen in the screenshot attached). I have updated all my packages and perl, but I can't seem to fix this problem. Am I missing a step?

**General (please complete the following information):**
- AGAT version Version v0.8.0
- AGAT installation/use: Installed using Conda
- OS: Ubuntu 24.04

**Screenshots**
![Capture](https://github.com/user-attachments/assets/15dfe6d4-f9a2-4d7f-acf0-cb87a88b6635)

**Comment by Juke34** [comment]
Did you install AGAT via conda or only the dependencies?
If you installed AGAT via conda did the  installation went well? Did you activate / use the correct env?

**Comment by antzellie** [comment]
Hi.

I assume it was done correctly, these are some screenshots of what I did. 

![Capture2](https://github.com/user-attachments/assets/e738c33b-9ffa-4151-b686-0d99f1828d77)

![Capture3](https://github.com/user-attachments/assets/cedb2b7f-a15c-42ab-9a4e-9b5d71f73d10)

![Capture4](https://github.com/user-attachments/assets/78791d19-2f27-4faf-9c4c-dda00704406f)

**Comment by Juke34** [comment]
Could you run   
`config --add channels bioconda  
conda config --add channels conda-forge  
conda config --set channel_priority strict  
`

And then try again in a fresh env:  
`Conda create -n agat_fresh agat`. 
Activate the new env:  
`conda activate agat_fresh`

And try agat

**Comment by antzellie** [comment]
Thank you for the suggestion. I will try it and let you know if I still
have any issues.

**Comment by antzellie** [comment]
Hello.
So I tried running the "config --add channels bioconda" commmand but it says that the config command is not found. I did try and do it in roott with "sudo" but that still didn't work. I am doing this in Ubuntu.

**Comment by Juke34** [comment]
Right the correct command is 
`conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict `

**Comment by antzellie** [comment]
Hi.
Thank you for all the assistance, I got it all sorted, it is running now.
