### ISSUE TITLE
Output empty

### ISSUE THREAD

**Issue by Juke34** [NBISweden/AGAT#5]
From @wuxiaopei0509
Hi,Juke
I just did agat_sp_gxf_to_gff3.pl -g transcripts.gff3 -o out.gff3',the output file have only two lines as below:
##gff-version 3
##feature-ontology https://github.com/The-Sequence-Ontology/SO-Ontologies/raw/master/subsets/SOFA.obo

**Comment by Juke34** [comment]
Any information from the parser?
Could you copy past few lines here that I give a try?

**Comment by Juke34** [comment]
```=> parse option and metadata:
   Accessing the feature level files:
      Using local features_level1.json file
      Using local features_level2.json file
      Using local features_level3.json file
      Using local features_spread.json file
   merge_locus option deactivated
   Accessing Ontology
      feature-ontology URI defined within the file: https://github.com/The-Sequence-Ontology/SO-Ontologies/raw/master/subsets/SOFA.obo
      feature-ontology parsed correctly
=> start parsing:
   GFF version parser used: 3

--------------------- WARNING ---------------------
MSG: ##feature-ontology header tag parsing unimplemented
---------------------------------------------------
   done in 32 seconds
=> report duplicates:
###############################################################################
#        Achthung /\ Attention /\ Be carefull => Duplicates removed !         #
#             (Same chr/contig/scaffold, same position, same ID)              #
###############################################################################
There were 3331 duplicated match feature for a total of 4094 duplicates.
   done in 0 seconds

******************************************************
*               - Start extra check -                *
******************************************************

**********************************
*   Check1: _check_sequential    *
**********************************
   Nothing to check as sequential !
   done in 0 seconds

**********************************
* Check2: _check_l2_linked_to_l3 *
**********************************
   done in 0 seconds

**********************************
* Check3: _check_l1_linked_to_l2 *
**********************************
   done in 0 seconds

**********************************
*   Check4: _remove_orphan_l1    *
**********************************
We removed 185325 level1 features that had no subfeature linked to it.
   done in 2 seconds

**********************************
*      Check5: _check_exons      *
**********************************
   done in 0 seconds

**********************************
*      Check6: _check_utrs       *
**********************************
   done in 0 seconds

**********************************
* Check7: _check_all_level2_posi *
**********************************
   done in 0 seconds

**********************************
* Check8: _check_all_level1_posi *
**********************************
   done in 0 seconds

**********************************
* Check10: _check_identical_isof *
**********************************
   done in 0 seconds

******************************************************
*                - End extra check -                 *
*                 done in 0 seconds                  *
******************************************************

=> OmniscientI total time: 34 seconds
GFF3 file parsed
```

**Comment by Juke34** [comment]
What I understand you have only `match` feature type in your file, which is a top feature (feature level1), so no parent (because top feature) and no children (that is weird usually that kind of file usually get also `match_part` features that are the children of `match` features ).    
As default behavior AGAT remove top features (Level1) when they have not children, because it is most likely an error... it cannot determine if it is coding or non-coding child feature (mRNA, tRNA, miRNA, etc in most of cases.).  But match/match_part is particular (never seen `match` feature alone btw).  
So there are several ways to make it work with AGAT in that particular case.

1) Use the option `--no_check _remove_orphan_l1` to skip that check that remove orphan level1 feature. But in that case you end up again will only Level1 feature in the output as it was in the input (minus the duplicated feature found). You will not be able to use other scripts because I have not implemented this option in the other scripts.
 
2) Change (with sed) your file by replacing 3rd column `match` by `match_part`. Then AGAT will create `match` features for comprehensiveness. (I think the best choice here)

3) Change the relationship in the json file (put `match` in the level2 file pointing to `gene` parent, and remove `match` from the level1 file) => AGAT will create `gene` features then.

Otherwise do not use a script with the _sp_ prefix. You can use scripts with _sq_ prefix without that type of complexity.
i.e for basic statistics there is `agat_sq_stat_basic.pl`

**Comment by wuxiaopei0509** [comment]
Thank you ,Juke .
I will not statistics the transcripts.gff3 file. by the way, I have another question, which script I can use to compare the two anntation : the evidence one and the abinitio one, and finally obtain number of  genes are specific to each annotation ; number of  genes from the evidence annotation have been fused together by the abinitio annotation ?

**Comment by Juke34** [comment]
hehe, good question I had a script in GAAS doing that (you can find it there in the [GAAS](https://github.com/NBISweden/GAAS) repo: GAAS/annotation/Tools/Deprecated/maker_checkFusionSplitBetweenTwoBuilds.pl), but I haven't transplanted it in AGAT because has to be re-implemented in a different way ( too old, and it is not perfect). You are welcome to have a try. I will probably include such script in a future AGAT release.

**Comment by Juke34** [comment]
Btw there is now a script to compare annotations and look at split and fusions. It is called agat_sp_compare_two_annotations.pl
