### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by vinay-swamy** [NBISweden/AGAT#50]
Is there a publication for AGAT that I can cite?

**Comment by Juke34** [comment]
I did not published AGAT yet.
You can cite as follow specifying the version you have used:

Dainat J. AGAT: Another Gff Analysis Toolkit to handle annotations in any GTF/GFF format.  (Version v0.4.0). Zenodo. https://www.doi.org/10.5281/zenodo.3552717

**Comment by Juke34** [comment]
It is now on the main page (readme).
