### ISSUE TITLE
agat_sp_add_start_and_stop.pl MSG: Each line of the file must be less than 65,536 characters. Line 28 is 85016 chars.

### ISSUE THREAD

**Issue by Xueliang24** [NBISweden/AGAT#505]
**Describe the bug**
When I ran the scripts `agat_sp_add_start_and_stop.pl`, it told that MSG: Each line of the file must be less than 65,536 characters. Line 28 is 85016 chars.

**General (please complete the following information):**
- AGAT version 1.4.1
- AGAT installation  by conda 
- Ubuntu

**To Reproduce**
```
agat_sp_add_start_and_stop.pl -g /home/dell/Public/01_genome/Blas/03.Iso_seq/ccs_bam/Blas_std.gtf \
-f ../../Blas.Chr.softmask.fasta \
--out Blas_stdAGATstart_and_stop.gff
```

**Screenshots**
The process was stopped and the Blas_stdAGATstart_and_stop.gff was empty
```
------------- EXCEPTION -------------
MSG: Each line of the file must be less than 65,536 characters. Line 28 is 85016 chars.
STACK Bio::DB::IndexedBase::_check_linelength /home/dell/anaconda3/envs/AGAT/lib/perl5/site_perl/Bio/DB/IndexedBase.pm:758
STACK Bio::DB::Fasta::_calculate_offsets /home/dell/anaconda3/envs/AGAT/lib/perl5/site_perl/Bio/DB/Fasta.pm:227
STACK Bio::DB::IndexedBase::_index_files /home/dell/anaconda3/envs/AGAT/lib/perl5/site_perl/Bio/DB/IndexedBase.pm:660
STACK Bio::DB::IndexedBase::index_file /home/dell/anaconda3/envs/AGAT/lib/perl5/site_perl/Bio/DB/IndexedBase.pm:488
STACK Bio::DB::IndexedBase::new /home/dell/anaconda3/envs/AGAT/lib/perl5/site_perl/Bio/DB/IndexedBase.pm:365
STACK toplevel /home/dell/anaconda3/envs/AGAT/bin/agat_sp_add_start_and_stop.pl:94

```
I ran `awk 'length($0) > 65536' input.gff` to check the lines, but no line appeared

**Comment by Juke34** [comment]
This is related to bioperl limitation.
Have a look here for a quick fix: https://agat.readthedocs.io/en/latest/troubleshooting.html#how-to-fix-bio-root-exception-met-in-agat
