### ISSUE TITLE
 EXCEPTION: Bio::Root::Exception

### ISSUE THREAD

**Issue by bijendrabio** [NBISweden/AGAT#506]
Hello,
I received a following error while converting gtf to gff3. Kindly suggest

agat_convert_sp_gxf2gxf.pl -g input.gtf > output.gff3

Error;
 EXCEPTION: Bio::Root::Exception -------------
MSG: '.transcript_id "anno1.g123180.t1"; gene_id "g_183256";' is not a valid frame
STACK: Error::throw
STACK: Bio::Root::Root::throw
STACK: Bio::SeqFeature::Generic::frame 

Regards,
B

**Comment by Juke34** [comment]
Something is wrong in your file. Check the line. Containing '.transcript_id "anno1.g123180.t1"; gene_id "g_183256";'
You must have 9 columns tab separated

**Comment by bijendrabio** [comment]
> Something is wrong in your file. Check the line. Containing '.transcript_id "anno1.g123180.t1"; gene_id "g_183256";' You must have 9 columns tab separated

Indeed. It was due to space error in gff3 as indicated in ERROR msg. Thanks @Juke34
