### ISSUE TITLE
agat_sp_statistics.pl for outputing whole distribution results as csv format

### ISSUE THREAD

**Issue by Jasminefyh** [NBISweden/AGAT#507]
Dear authors,

Thank you for providing this excellent tool for genome structure statistics. I have been using the command `agat_sp_statistics.pl` and found it very helpful for generating distribution plots of genome features, such as exons, introns, and CDS regions.

I am wondering if it is possible to obtain the statistical distribution results as a CSV file, including details like Transcript ID, Transcript Sequence Length, Number of Exons, Total Exon Sequence Length, etc. This would greatly help us in performing additional custom analyses and plotting genome features independently.

I appreciate your time and look forward to your response.

Sincerely,  
Jasmine

**Comment by Juke34** [comment]
If you get the yaml file e.g.:
```
repeat_region:
  isoform: NA
  value:
    90 percentile repeat_region length (bp): na
    Longest repeat_region (bp): 101
    Number of repeat_region: 2
    Number repeat_region overlapping: 0
    Shortest repeat_region (bp): 101
    Total repeat_region length (bp): 202
    mean repeat_region length (bp): 101
    median repeat_region length (bp): 101
```

It should be easy to get a table 

| title | value |
|  -- | -- |
90 percentile repeat_region length (bp) |  na
Longest repeat_region (bp) | 101
Number of repeat_region | 2
Number repeat_region overlapping | 0
Shortest repeat_region (bp) | 101
Total repeat_region length (bp) | 202
mean repeat_region length (bp) | 101
median repeat_region length (bp) | 101

**Comment by gchevignon** [comment]
Yes indeed but this not what we  ask ... 
We want the table that the script use to produce this type of plot :
[mrnaClass_cds.pdf](https://github.com/user-attachments/files/17996422/mrnaClass_cds.pdf)
And those data are not in the yaml file ...
Ideally we'll have a table per plot
Thanks !

**Comment by Juke34** [comment]
Ok I understand you do not want the resulting statistics but the raw data. Yes it is feasible. Will see when time allow this implementation.
