### ISSUE TITLE
Provide option for padding with agat_sp_manage_IDs.pl?

### ISSUE THREAD

**Issue by dirkjanvw** [NBISweden/AGAT#508]
**Is your feature request related to a problem? Please describe.**
When renaming features using `agat_sp_manage_IDs.pl`, genes are named 1, 2, 3, etc. after some prefix. This makes `grep`'ing a gene difficult: PREFIX1 and PREFIX10 both match `grep PREFIX1` whereas I only want the former.

**Describe the solution you'd like**
Is it possible to add padding to the numbering? To my understanding your parser parses the entire GFF first and only then starts renaming, so it knows the total number of features to rename (and thus how much padding is needed). In the case of <100 features it should rename to "PREFIX01", "PREFIX02", ..., "PREFIX99" for example.

**Describe alternatives you've considered**
I know that it is possible to do `grep -E "PREFIX1\b"` to fix this for `grep` specifically, but I think there is added benefit to provide padding for more use cases :)

**Additional context**
NA

**Comment by dirkjanvw** [comment]
What would be the difference? Just a standard number of digits instead of counting it and rounding up?

**Comment by Juke34** [comment]
Yes exactly

**Comment by dirkjanvw** [comment]
Aha, yes; it would be great if the could be implemented!

**Comment by Juke34** [comment]
Then I guess using `--ensembl` should kind of already perform this task.
Can you check if it already fulfills your request?

**Comment by dirkjanvw** [comment]
Aha yes I see, I didn't realise I could combine `--tair` with `--ensembl`! This is indeed what I was after, thanks so much!
