### ISSUE TITLE
GFF2GTF long_terminal_repeat being reported as transcript in gtf

### ISSUE THREAD

**Issue by sivasubramanics** [NBISweden/AGAT#517]
**Describe the bug**
While we try to convert the gff3 to gtf, I observed some weird behaviour specially for the "long_terminal_repeat" features. The GFF3 files were downloaded from the ncbi reference genomes.

**General :**
- AGAT version v1.4.1
- AGAT installation/use mamba
- OS: Ubuntu

**To Reproduce**
Scripts and parameters to reproduce the behavior.
``` agat_convert_sp_gff2gtf.pl --gff GCF_000146045.2/genomic.gff --gtf_version 3 --output GCF_000146045.2/genomic.gtf```
Input file description: The GFF file was downloaded directly from ncbi using ncbi-datasets-cli

```
Input GFF contains:
NC_001135.5     RefSeq  long_terminal_repeat    291373  291712  .       +       .       ID=id-NC_001135.5:291373..291712;Dbxref=SGD:S000006839;Note=Ty1 LTR;gbkey=repeat_region;rpt_type=long_terminal_repeat
NC_001135.5     RefSeq  long_terminal_repeat    291922  292167  .       +       .       ID=id-NC_001135.5:291922..292167;Dbxref=SGD:S000006841;Note=Ty5 LTR;gbkey=repeat_region;rpt_type=long_terminal_repeat

Output GTF contains:
NC_001135.5     RefSeq  transcript      291373  291712  .       +       .       gene_id "gene-YCR095W-A"; transcript_id "id-NC_001135.5:291373..291712"; Dbxref "SGD:S000006839"; ID "id-NC_001135.5:291373..291712"; Note "Ty1 LTR"; Parent "gene-YCR095W-A"; gbkey "repeat_region"; original_biotype "long_terminal_repeat"; rpt_type "long_terminal_repeat";
NC_001135.5     RefSeq  transcript      291922  292167  .       +       .       gene_id "gene-YCR095W-A"; transcript_id "id-NC_001135.5:291922..292167"; Dbxref "SGD:S000006841"; ID "id-NC_001135.5:291922..292167"; Note "Ty5 LTR"; Parent "gene-YCR095W-A"; gbkey "repeat_region"; original_biotype "long_terminal_repeat"; rpt_type "long_terminal_repeat";
```
**Expected behavior**
Probably these features are to be ignored during the conversion and carefully removed, or provide an option to the user to choose

Best,
Siva

**Comment by Juke34** [comment]
This is expected. GTF3 does not accept any other type of level2 feature. To accept any kind of GTF feature use —relax parameter
