### ISSUE TITLE
possible precedence issue

### ISSUE THREAD

**Issue by markusmoest** [NBISweden/AGAT#52]
Hi ,

Thanks for providing this resource! I want to optain protein sequences from a gff3 and a genome fasta file.
I've installed AGAT using conda and also updated. When running agat_sp_extract_sequences.pl -h, I get the following error: 
"Possible precedence issue with control flow operator at /home/moestmar/miniconda3/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805."
I have just started playing with the script and have not encountered anything unusual yet, but could this issue affect the results I get?

Thanks for your help!
Markus

**Comment by Juke34** [comment]
This is a warning message left in a previous version of Bioperl. They have removed it in recent Bioperl release. It does not affect the result.

**Comment by markusmoest** [comment]
Many thanks!
