### ISSUE TITLE
Error importing InterPro.tsv file (agat_sp_manage_functional_annotation) 

### ISSUE THREAD

**Issue by AMMMachado** [NBISweden/AGAT#57]
Hi Juke,

First of all, thank you for this amazing toolkit. It has been very useful to correct and manage gft/gff files. 
I tried to import the InterPro output to the gff3 file, however gave me an error and didn't import any feature to the gff file. 
I have checked all input formats and seems to be correct. I have install the Agat toolkit with conda.

I used the command: 

agat_sp_manage_functional_annotation.pl -f X342.gff3 -i InterPro.tsv --output X342_annotated.gff3 

Error:
"
=> OmniscientI total time: 479 seconds
[12:31:04] Parsing Finished
[12:31:04] Compute statistics
Reading features from InterPro.tsv...
[12:31:27] load FUNCTIONAL information

Use of uninitialized value $term in concatenation (.) or string at /home/anaconda3/envs/agaat/lib/site_perl/5.26.2/AGAT/Utilities.pm line 266, <GEN1> line 889.
Use of uninitialized value $term in concatenation (.) or string at /home/anaconda3/envs/agaat/lib/site_perl/5.26.2/AGAT/Utilities.pm line 266, <GEN1> line 889.
... " 

The report seems +- ok. 

--------------------------------------------------------------------------------

 _________________________________________________________________________________________________________________________________
|                         | Nb Total term           | Nb mRNA with term       | Nb mRNA updated by term | Nb gene updated by term |
|                         | in raw File             |   in raw File           | in our annotation file  | in our annotation file  |
|_________________________________________________________________________________________________________________________________|
|           CDD           |            47           |                         |            0            |            0            |
|_________________________________________________________________________________________________________________________________|
|           Coils         |            17           |                         |            0            |            0            |
|_________________________________________________________________________________________________________________________________|
|            GO           |            98           |                         |            0            |            0            |
|_________________________________________________________________________________________________________________________________|
|          Gene3D         |            84           |                         |            0            |            0            |
|_________________________________________________________________________________________________________________________________|
|         InterPro        |           236           |                         |            0            |            0            |
|_________________________________________________________________________________________________________________________________|
|           KEGG          |            5            |                         |            0            |            0            |
|_________________________________________________________________________________________________________________________________|
|         MetaCyc         |            10           |                         |            0            |            0            |
|_________________________________________________________________________________________________________________________________|
|        MobiDBLite       |            41           |                         |            0            |            0            |
|_________________________________________________________________________________________________________________________________|
|           PIRSF         |            5            |                         |            0            |            0            |
|_________________________________________________________________________________________________________________________________|
|          PRINTS         |            15           |                         |            0            |            0            |
|_________________________________________________________________________________________________________________________________|
|           Pfam          |            96           |                         |            0            |            0            |
|_________________________________________________________________________________________________________________________________|
|     ProSitePatterns     |            23           |                         |            0            |            0            |
|_________________________________________________________________________________________________________________________________|
|     ProSiteProfiles     |            61           |                         |            0            |            0            |
|_________________________________________________________________________________________________________________________________|
|         Reactome        |            20           |                         |            0            |            0            |
|_________________________________________________________________________________________________________________________________|
|           SMART         |            61           |                         |            0            |            0            |
|_________________________________________________________________________________________________________________________________|
|       SUPERFAMILY       |            79           |                         |            0            |            0            |
|_________________________________________________________________________________________________________________________________|
nb mRNA without Functional annotation (CDD,Coils,GO,Gene3D,InterPro,KEGG,MetaCyc,MobiDBLite,PIRSF,PRINTS,Pfam,ProSitePatterns,ProSiteProfiles,Reactome,SMART,SUPERFAMILY) = 28040
nb mRNA with Functional annotation (CDD,Coils,GO,Gene3D,InterPro,KEGG,MetaCyc,MobiDBLite,PIRSF,PRINTS,Pfam,ProSitePatterns,ProSiteProfiles,Reactome,SMART,SUPERFAMILY) = 0
nb gene without Functional annotation (CDD,Coils,GO,Gene3D,InterPro,KEGG,MetaCyc,MobiDBLite,PIRSF,PRINTS,Pfam,ProSitePatterns,ProSiteProfiles,Reactome,SMART,SUPERFAMILY) = 28040
nb gene with Functional annotation (CDD,Coils,GO,Gene3D,InterPro,KEGG,MetaCyc,MobiDBLite,PIRSF,PRINTS,Pfam,ProSitePatterns,ProSiteProfiles,Reactome,SMART,SUPERFAMILY) = 0

Thank you in advance

André

**Comment by Juke34** [comment]
I guess you can ignore the error message, it is probably  just because nothing was found, so $term is empty. I will add a fix to avoid this message.

But you have a problem in your data, the mRNA/gene identifier are probably different between the interpro file and the gff file.
Could you provide a sample of each file?

**Comment by AMMMachado** [comment]
Thank you Juke. 
You are correct, i found the differences in mRNA/gene identifiers of the interpro file and the gff file.
Now it's working like a charm. 

One more question. 

I intend to use the blast output of NR database to annotate/atribute the gene name. Can i import the blast output of NR with NR in fasta ? Or the agat_sp_manage_functional_annotation script just work for uniprot outm6 file ?

André

**Comment by Juke34** [comment]
You can use the blast output with the DB (the fasta file of the DB actually) to attach the putative gene names. The blast format is the default one I think. You can invoke the help to check.

**Comment by AMMMachado** [comment]
Thank you Juke.
I close the issue.

André
