### ISSUE TITLE
Propagate attributes from level 1 to level 3

### ISSUE THREAD

**Issue by wflynny** [NBISweden/AGAT#59]
Hi, I recently found AGAT and it's a great tool!  I'm merging and converting a few GFFs to GTF and my downstream tools expect the `gene_name` attribute on level 3 features (CDS, exons, etc.).  Is there a simple way to do this with AGAT?  I've looked through the `agat_sp_manage_*.pl` scripts and couldn't find that functionality. Thanks!

For example, starting with (GTF):
```
##gtf-version 3
chrM	insdc	gene	7173	7863	.	+	.	gene_id "ENSGACG00000020938"; ID "ENSGACG00000020938"; Name "mt-co2"; protein_id "ENSGACP00000027663";
chrM	insdc	transcript	7173	7863	.	+	.	gene_id "ENSGACG00000020938"; transcript_id "ENSGACT00000027730"; ID "ENSGACT00000027730"; Name "mt-co2-201"; Parent "ENSGACG00000020938"; original_biotype "mrna";
chrM	insdc	exon	7173	7863	.	+	.	gene_id "ENSGACG00000020938"; transcript_id "ENSGACT00000027730"; ID "nbis-exon-1"; Parent "ENSGACT00000027730";
chrM	insdc	CDS	7173	7863	.	+	0	gene_id "ENSGACG00000020938"; transcript_id "ENSGACT00000027730"; ID "ENSGACT00000027730.CDS_1"; Parent "ENSGACT00000027730";
```
is it possible to have something like `ParentName` that we can then replace with `agat_sp_manage_attributes.pl`:
```
##gtf-version 3
chrM	insdc	gene	7173	7863	.	+	.	gene_id "ENSGACG00000020938"; ID "ENSGACG00000020938"; Name "mt-co2"; protein_id "ENSGACP00000027663";
chrM	insdc	transcript	7173	7863	.	+	.	gene_id "ENSGACG00000020938"; transcript_id "ENSGACT00000027730"; ID "ENSGACT00000027730"; Name "mt-co2-201"; Parent "ENSGACG00000020938"; original_biotype "mrna"; ParentName "mt-co2";
chrM	insdc	exon	7173	7863	.	+	.	gene_id "ENSGACG00000020938"; transcript_id "ENSGACT00000027730"; ID "nbis-exon-1"; Parent "ENSGACT00000027730"; ParentName "mt-co2";
chrM	insdc	CDS	7173	7863	.	+	0	gene_id "ENSGACG00000020938"; transcript_id "ENSGACT00000027730"; ID "ENSGACT00000027730.CDS_1"; Parent "ENSGACT00000027730"; ParentName "mt-co2";
```

**Comment by Juke34** [comment]
With agat_sp_manage_attributes.pl you can duplicate an attribute and change its tag. Look at the help to do so, you will be able to copy the `gene_id` attribute into `gene_name ` with the same value.

**Comment by Juke34** [comment]
Ok I get what you want know. Forget what I said before. I don’t think I have anything like that for now.

**Comment by wflynny** [comment]
Ah ok, thanks @Juke34.  Anyway, great tool!

**Comment by wflynny** [comment]
Ended up just writing a small python script to add this info.  Leaving a link to it here in case it is useful to anyone else:
https://gist.github.com/wflynny/a4c1bde3ac60bd5f3c88976a55035d27

**Comment by Juke34** [comment]
Thank you for your feedback!
