### ISSUE TITLE
agat_convert_sp_gff2gtf.pl output empty file

### ISSUE THREAD

**Issue by olechnwin** [NBISweden/AGAT#63]
Hello,

I am trying to use `agat_convert_sp_gff2gtf.pl `to convert my gff3 file to a gtf file. After running for a while, it outputs an empty gtf file. Can you please help me with this?

This is the command I ran:
`agat_convert_sp_gff2gtf.pl --gff cns_p.phased.0.lifted_cleaned_sort_name.gff -o cns_p.phased.0.lifted_cleaned_sort_name.gtf 2>&1 | tee log_phased0_agat.txt`

I am attaching the log file:
[log_phased0_agat.txt](https://github.com/NBISweden/AGAT/files/5143669/log_phased0_agat.txt)

and a few lines of my gff file:

```
##displayName=gene_name
000000F_0       HAVANA  transcript      254417  373621  .       +       .       ID=ENST00000602303.1;gene_id=ENSG00000170035.11;transcript_id=ENST00000602303.1;gene_type=protein_coding;gene_status=KNOWN;gene_name=UBE2E3;transcript_type=protein_coding;transcript_status=KNOWN;transcript_name=UBE2E3-007;level=2;protein_id=ENSP00000473525.1;tag=alternative_5_UTR,mRNA_end_NF,cds_end_NF;havana_gene=OTTHUMG00000132585.12;havana_transcript=OTTHUMT00000334331.7
000000F_0       HAVANA  exon    254417  254519  .       +       .       ID=exon:ENST00000602303.1:1;Parent=ENST00000602303.1;gene_id=ENSG00000170035.11;transcript_id=ENST00000602303.1;gene_type=protein_coding;gene_status=KNOWN;gene_name=UBE2E3;transcript_type=protein_coding;transcript_status=KNOWN;transcript_name=UBE2E3-007;exon_number=1;exon_id=ENSE00003396943.1;level=2;protein_id=ENSP00000473525.1;havana_gene=OTTHUMG00000132585.12;havana_transcript=OTTHUMT00000334331.7;tag=alternative_5_UTR,mRNA_end_NF,cds_end_NF
000000F_0       HAVANA  exon    267543  267629  .       +       .       ID=exon:ENST00000602959.1:1;Parent=ENST00000602959.1;gene_id=ENSG00000170035.11;transcript_id=ENST00000602959.1;gene_type=protein_coding;gene_status=KNOWN;gene_name=UBE2E3;transcript_type=protein_coding;transcript_status=KNOWN;transcript_name=UBE2E3-003;exon_number=1;exon_id=ENSE00003372694.1;level=2;protein_id=ENSP00000473639.1;ccdsid=CCDS2282.1;havana_gene=OTTHUMG00000132585.12;havana_transcript=OTTHUMT00000334325.1;tag=basic,alternative_5_UTR,appris_principal,CCDS
000000F_0       HAVANA  transcript      267543  375511  .       +       .       ID=ENST00000602959.1;gene_id=ENSG00000170035.11;transcript_id=ENST00000602959.1;gene_type=protein_coding;gene_status=KNOWN;gene_name=UBE2E3;transcript_type=protein_coding;transcript_status=KNOWN;transcript_name=UBE2E3-003;level=2;protein_id=ENSP00000473639.1;tag=basic,alternative_5_UTR,appris_principal,CCDS;ccdsid=CCDS2282.1;havana_gene=OTTHUMG00000132585.12;havana_transcript=OTTHUMT00000334325.1

```

A little background about the gff file. The gff file was created by lifting over gencode gff file to our assembled genome to convert the coordinate. So, I'm assuming since this is assembled genome there are many sequences that are missing which makes some of the annotation missing ? I'm not too familiar with gtf/gff specification to know for sure.

Thanks in advance for your help.

**Comment by Juke34** [comment]
The log shows lot of problem in your input file.
Difficult to say the sample you give works well. Depending tools liftover may mess-up off/gtf files.
Could you try `agat_convert_sp_gxf2gxf.pl` first?

**Comment by olechnwin** [comment]
Thanks so much for your quick reply. I am currently trying your suggestions.

**Comment by olechnwin** [comment]
@Juke34 ,

I was able to run `agat_convert_sp_gxf2gxf.pl` and get a gff3 file. Unfortunately, using this gff3 file, it still generated empty gtf file.

**Comment by Juke34** [comment]
Could you send me the original file?

**Comment by Juke34** [comment]
What AGAT version did you use?

**Comment by olechnwin** [comment]
I installed AGAT using conda. It's version 0.4.0.
How do I send the original file? I tried uploading it here but it's too big.
Thanks again for all your help.

**Comment by Juke34** [comment]
Dropbox? google drive? ftp?

**Comment by olechnwin** [comment]
Thanks for the idea. I've uploaded my original gff file here: [https://www.dropbox.com/sh/qv1uo2ox219tu91/AAAHoRzSpo8OCCWAVpZsXshHa?dl=0](https://www.dropbox.com/sh/qv1uo2ox219tu91/AAAHoRzSpo8OCCWAVpZsXshHa?dl=0). 
Please let me know if you have problems accessing the file.

**Comment by Juke34** [comment]
I see the problem, I will see what I can do.
What was the liftover tool you used?

**Comment by olechnwin** [comment]
Thank you so much!! I was using [flo](https://github.com/wurmlab/flo) to liftover [gencode v19](https://www.gencodegenes.org/human/release_19.html). I wonder whether it is the original gencode file?

**Comment by Juke34** [comment]
Hi, here is your file converted https://www.dropbox.com/s/rxey6s0xkvyl37n/cns_p.phased.0.lifted_cleaned_sort_name.agat.gtf?dl=0
The input gff was a bit particular, AGAT didn't parse it properly, then the converter was catching a discrepancy in the parent/child relationship between features on a same record (message was We replace the gene_id ENSG00000013306.11 by ENSG00000099834.14. Is it normal ?). It was due to the fact that some `transcript` features didn't have any parent in the attributes (see #64 for an example), AGAT was parsing them as sequential attaching as parent the last level1 feature (e.g. gene) met. And the previous level1 feature was not necessarily the correct parent. I had to add an extra checkup in the code to check the level3 feature (e.g exon) which them contain information about the correct level1 feature expected.
I will push the fix in the master branch and release soon a new AGAT version.

**Comment by olechnwin** [comment]
@Juke34, thank you so much!!! I really appreciate your help and the time you spent to convert my file.
The file that you converted is one of the two alleles. Not to sound ungrateful but how do I convert the other allele? It is this one [cns_p.phased.1.lifted_cleaned_sort_name.gff.gz](https://www.dropbox.com/s/ze62qodvyj3q7ap/cns_p.phased.1.lifted_cleaned_sort_name.gff.gz?dl=0).
Sorry I probably should mention this before.

**Comment by Juke34** [comment]
Install the last AGAT version from the master branch then you should be able to use `agat_convert_sp_gff2gtf.pl ` without any problem:
Activate your AGAT conda env.
once your AGAT Conda env activated do:
```
git clone https://github.com/NBISweden/AGAT.git # Clone AGAT
cd AGAT                                         # move into AGAT folder
perl Makefile.PL                                # Check all the dependencies*
make                                            # Compile
make test                                       # Test
make install                                    # Install
```

**Comment by olechnwin** [comment]
@Juke34,
Thank you so much for your installation instruction. I will try this!

**Comment by olechnwin** [comment]
Hi @Juke34 
I tried to use `agat_convert_sp_gff2gtf.pl` to convert the other allele after following your instruction above to get the latest version, but it still created an empty output. 
Here is the log: 
[log_phased1_agat_gff2gtf.txt](https://github.com/NBISweden/AGAT/files/5191887/log_phased1_agat_gff2gtf.txt)

Thank you again!

**Comment by Juke34** [comment]
Right there is still something to fix...

**Comment by olechnwin** [comment]
Just want to leave a note to say how grateful I am for your time and commitment for this.

**Comment by Juke34** [comment]
Ok I found the problem. You end up having different genes mapping at the same location. So AGAT create a gene feature umbrella that have 2 transcripts having different gene_id. While only one gene_id must be shared within the record to be a correct gtf. I think I will add a fix where in a record the collective gene_id will be the one for the first transcript meet. For the next transcript I will save the previous gene_id in a new attribute `previous_gene_id` and replace the gene_id by the selected one.

Btw, as it is a lift-over a part of a gene (exon) can be mapped on sequenceA while the rest map on other sequence(s).  That can be problematic depending what you plan to achieve.

**Comment by olechnwin** [comment]
Thanks so much for the explanation @Juke34! I can't wait to run AGAT after you added the additional checks.

I'm not familiar at all with genome annotation format to understand what you meant by "Btw, as it is a lift-over a part of a gene (exon) can be mapped on sequenceA while the rest map on other sequence(s). That can be problematic depending what you plan to achieve." Did you mean that for example gene A has 2 exons, exon 1 can map to sequence 000852F_1 while exon 2 map to sequence 001670F_1? Isn't this the intended way since it probably shows gene A in the assembled genome doesn't exist only the exon can be mapped or gene A is chimeric?

**Comment by Juke34** [comment]
> Did you mean that for example gene A has 2 exons, exon 1 can map to sequence 000852F_1 while exon 2 map to sequence 001670F_1? 
Yes it is what I meant.
The reasons for that can be multiple.

**Comment by olechnwin** [comment]
> > Did you mean that for example gene A has 2 exons, exon 1 can map to sequence 000852F_1 while exon 2 map to sequence 001670F_1?
> 
> Yes it is what I meant.
> 
> The reasons for that can be multiple.

I completely agree. Thanks for the notes. I'll keep this in mind as I used the annotation for my downstream analysis.

**Comment by Juke34** [comment]
this commit 4772cff0c6213e5b923d9f414a8394e9c1d14b18 should fix the problem. You can try again. I suggest to run the first conversion too.

**Comment by olechnwin** [comment]
Thank you so much for updating AGAT. I'll try again. 
By "run the first conversion", did you mean to run `agat_convert_sp_gxf2gxf.p` then `agat_convert_sp_gff2gtf.pl` ?

**Comment by Juke34** [comment]
No sorry I meant to re run the conversion for your first file too.
`agat_convert_sp_gxf2gxf` is useful to get a log to understand how AGAT deals with the gff file to parse it. No need to run it.

**Comment by olechnwin** [comment]
Hi @Juke34 ,
I've tried it and it's still generating empty gtf file. 
Here is the log again. [log_phased1_agat_gff2gtf.txt](https://github.com/NBISweden/AGAT/files/5240294/log_phased1_agat_gff2gtf.txt)

**Comment by Juke34** [comment]
From your log it seems the parsing stopped in the middle, the conversion didn't even start. Are you sure to not have stopped the script in the middle?

**Comment by olechnwin** [comment]
I didn't stop the script but I'll run it again to make sure it wasn't interrupted.

**Comment by olechnwin** [comment]
I was able to convert my gff file to gtf. It ran out of memory when the conversion didn't even start.
Thank you so much for all your help. I really appreciate it!!
