### ISSUE TITLE
missing PERL lib?

### ISSUE THREAD

**Issue by lsterck** [NBISweden/AGAT#69]
when using the --expose option I got the following response:

```
=> Expose feature level json files
=> Accessing the feature level json files
Undefined subroutine &AGAT::OmniscientJson::copy called at /AGAT/OmniscientJson.pm line 138.
```

Perhaps the relevant PERL module is missing from the package?
https://metacpan.org/pod/File::Copy

**Comment by Juke34** [comment]
Yes I had removed the import ^^
