### ISSUE TITLE
Split a gff3 file based on specified coordinates 

### ISSUE THREAD

**Issue by sanyalab** [NBISweden/AGAT#73]
Hi Jacques,

I would like to suggest implementation of a module in AGAT to subset a gff3 file based on a chromosome and coordinate range/ranges. There is one such implementation in gffread. But the problem is that it will extract between a range only if there are genes/transcripts within that range. It will create an empty file if extraction is from a repeat rich region for example. Using an awk script where you specify coordinate ranges, will get you the contents. But the boundaries have the risk of being incomplete, if the coordinates lie in the middle of a level1 feature. In this case I would like to be inclusive and extend the coordinate at the boundaries to included the closest level 1 feature.

Thanks for the help

Best Regards
Abhijit

**Comment by ferrojm** [comment]
Hi!

Has this been implemented in newer versions of AGAT (i.e., to extract by range or coordinates?)

Thanks!
Juan

**Comment by Juke34** [comment]
Have a look here https://nbisweden.github.io/AGAT/tools/agat_sp_filter_record_by_coordinates/
