### ISSUE TITLE
required perl modules wont install. alternatives?

### ISSUE THREAD

**Issue by pedrobdfp** [NBISweden/AGAT#76]
Hi!

I have agat up and running in a virtual machine, however, when I try to use it in our local server (which has higher computational power and houses all of datasets, making life easier), I keep running into problems with perl modules, even tought they are both running the same Perl version (v5.26.2 built for x86_64-linux-thread-multi)

For example:

```
(genometools) [pb21@nlogin2 cds]$ agat_sp_statistics.pl
Can't locate Bio/Tools/GFF.pm in @INC (you may need to install the Bio::Tools::GFF module)
(genometools) [pb21@nlogin2 cds]$ agat_sp_extract_sequences.pl -h
 Can't locate Clone.pm in @INC (you may need to install the Clone module) 
```

but when I try to install the modules I need with CPANM, they ALWAYS fail.

Here is one example:

```
(genometools) [pb21@nlogin2 cds]$ cpanm Clone --force
--> Working on Clone
Fetching http://www.cpan.org/authors/id/A/AT/ATOOMIC/Clone-0.45.tar.gz ... OK
Configuring Clone-0.45 ... OK
==> Found dependencies: B::COW
--> Working on B::COW
Fetching http://www.cpan.org/authors/id/A/AT/ATOOMIC/B-COW-0.004.tar.gz ... OK
Configuring B-COW-0.004 ... OK
Building and testing B-COW-0.004 ... FAIL
! Installing B::COW failed. See /home/pb21/.cpanm/work/1601647781.17645/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'B::COW' is not installed
! Bailing out the installation for Clone-0.45.
(genometools) [pb21@nlogin2 cds]$ cpanm B::COW --force
--> Working on B::COW
Fetching http://www.cpan.org/authors/id/A/AT/ATOOMIC/B-COW-0.004.tar.gz ... OK
Configuring B-COW-0.004 ... OK
Building and testing B-COW-0.004 ... FAIL
! Installing B::COW failed. See /home/pb21/.cpanm/work/1601647792.17769/build.log for details. Retry with --force to force install it.

```
Do you have any suggestions on how to get a perl instalation with all required modules up and running?

Thanks!
Pedro

**Comment by Juke34** [comment]
If you can I definitely advise you to switch to Conda to manage tool installations. The installation of AGAT will be much easier.
If you do not want to use Conda, I recommend to use perlbrew to mange perl version installation and manages packages.
Otherwise you could try cpan instead of cpanm. Do you have all the right in the folder where the dependencies are installed? You might try with sudo.

I don't know really what can be the problem. I think you will be more lucky to find an answer by asking on a dedicated forum as stackoverflow.com.

**Comment by pedrobdfp** [comment]
Hi!

The installation was performed via conda (in a fresh environment), so I just supposed it would install along all required perl packages. Is still requiring perl packages expected?

best;
Pedro

**Comment by Juke34** [comment]
is it normal you called you env `genometools` ?

**Comment by Juke34** [comment]
do `conda list` and check you should have `perl-clone`. Check you have agat too.

**Comment by Juke34** [comment]
Another alternative is to use docker or singularity: 
`docker pull quay.io/biocontainers/agat`

**Comment by pedrobdfp** [comment]
Good catch!  I created the fresh environment, but forgot to activate it before installing.

I just tested, and it works well when starting from a fresh environment.

Well, at least now you (and me) are sure agat is incompatible with genometools.

Thanks for the help, and sorry for taking your time!

best;
Pedro
