### ISSUE TITLE
disable log output into the gff file, remove StopCodon from last CDS

### ISSUE THREAD

**Issue by estolle** [NBISweden/AGAT#84]
Hi there

I just came across AGAT and love all the functionality as it fixes lots of issues with GFFs. I'm trying to parse and properly format NCBI RefSeq GFFs. It works for the most part but I do have always the issue that AGAT (agat_convert_sp_gxf2gxf.pl -v 0 -g $INPUTFILENAME.gff) is printing alot of things in the front and end of the resulting gff file, rendering it invalid even for other AGAT tools (eg agat_sp_add_start_and_stop.pl). Is there a way to disable this?

Another issue I have with the GFFs is that they contain the stopcodon as part of the last CDS. Some downstream tools have an issue with this as the * (stop) after translation is making them crash. Thus I wouldlike to remove the Stop Codon (and Start codon) from the CDS and (as done with agat_sp_add_start_and_stop.pl) add them as separate features. An option for this would be great! Is there any AGAT script which can do this? (if I use agat_sp_add_start_and_stop.pl they are correctly IDed and added, but the last CDS still contains them, i.e. redundant).

I am trying right now to see if reading the NCBI RefSeq GTF instead GFF and hope this conversion will avoid the StopCodons. But it seems to to get stuck (been running few hrs without any output except the first few steps of reading in data 
agat_convert_sp_gxf2gxf.pl -v 1 --gff_version_input 2.5 --gff_version_output 3 -g $INPUTFILENAME.gtf

This script is being run by perl v5.26.2
Bioperl location being used: /home/ek/.conda/envs/gff/lib/site_perl/5.26.2/Bio/
-------------------------------------------------------------------------------
********************************************************************************
*                              - Start parsing -                               *
********************************************************************************
-------------------------- parse options and metadata --------------------------
=> Accessing the feature level json files
	Using standard /home/ek/.conda/envs/gff/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_level1.json file
	Using standard /home/ek/.conda/envs/gff/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_level2.json file
	Using standard /home/ek/.conda/envs/gff/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_level3.json file
	Using standard /home/ek/.conda/envs/gff/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_spread.json file
=> Attribute used to group features when no Parent/ID relationship exists:
	* locus_tag
	* gene_id
=> merge_loci option deactivated
=> Accessing Ontology
	No ontology accessible from the gff file header!
	We use the SOFA ontology distributed with AGAT:
		/home/ek/.conda/envs/gff/lib/site_perl/5.26.2/auto/share/dist/AGAT/so.obo
	Read ontology /home/ek/.conda/envs/gff/lib/site_perl/5.26.2/auto/share/dist/AGAT/so.obo:
		4 root terms, and 2472 total terms, and 1436 leaf terms
	Filtering ontology:
		We found 1757 terms that are sequence_feature or is_a child of it.
-------------------------------- parse features --------------------------------
=> GFF version parser used: 2.5
********************************************************************************
*                               - End parsing -                                *
*                             done in 244 seconds                              *
********************************************************************************

********************************************************************************
*                               - Start checks -                               *
********************************************************************************
---------------------------- Check1: feature types -----------------------------
----------------------------------- ontology -----------------------------------
All feature types in agreement with the Ontology.
------------------------------------- agat -------------------------------------
AGAT can deal with all the encountered feature types (3rd column)
------------------------------ done in 0 seconds -------------------------------

------------------------------ Check2: duplicates ------------------------------
None found
------------------------------ done in 0 seconds -------------------------------

-------------------------- Check3: sequential bucket ---------------------------
1 cases of interleaved locus. ( Features of the locus data are defined earlier in the file.
None found
------------------------------ done in 2 seconds -------------------------------

--------------------------- Check4: l2 linked to l3 ----------------------------

The file I want to parse/convert is this:
https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/254/395/GCF_003254395.2_Amel_HAv3.1/GCF_003254395.2_Amel_HAv3.1_genomic.gff.gz
https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/254/395/GCF_003254395.2_Amel_HAv3.1/GCF_003254395.2_Amel_HAv3.1_genomic.gtf.gz
https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/254/395/GCF_003254395.2_Amel_HAv3.1/GCF_003254395.2_Amel_HAv3.1_genomic.fna.gz

**Comment by Juke34** [comment]
GTF or GFF will end up with the same result with AGAT.
Logs are quite inconsistent depending scripts, most of time you can deactivate then using `-v 0` but as in your case it does not work. The good way that works in all cases is to provide an output file with the appropriate option e.g. `-o result.gff` and in this case you will not have anything else than you proper gff in the result.

For the stop codon, I guess you talk about `agat_sp_extract_sequences.pl`, there are options to deal with that. Call the help and read it carefully.  See `--clean_internal_stop` and `--clean_final_stop`

**Comment by Juke34** [comment]
So running `agat_sp_add_start_and_stop.pl ` and then `agat_convertsp_gff2gtf.pl` will do the job. But you need to install the version from the master branch (see https://github.com/NBISweden/AGAT#use-a-version-of-agat-from-a-specific-branch).
