### ISSUE TITLE
AGAT merging exons but not CDS

### ISSUE THREAD

**Issue by 14zac2** [NBISweden/AGAT#86]
Hello! I'm hoping you could give me your advice with something. First of all, AGAT is working great for me! You've created a super useful tool! My issue arises when I'm working with a gff file of manually curated genes, in which some of the exons and CDS attributes are adjacent. The output by AGAT merges the exons but not the CDS regions, resulting in warnings, such as:

`Peculiar rare case, we found 10 cds while 13 expected.`

Is there a way I could either merge the CDS regions or prevent this from happening? I just want to keep the CDS and exons the same for my own sanity.

Thanks!
Zoe

**Comment by Juke34** [comment]
Right I don’t think AGAT fix the CDS when it is badly defined as in your case several part that overlap or are adjacent.
That might be implemented. But this case should be avoided.
How did you curate your file? Directly in the file or using something like Webapollo?

**Comment by 14zac2** [comment]
Thank you for responding so quickly! I am surprised that AGAT can merge exons but not CDS. I have been provided with a list of a few thousand manually curated genes that I am combining with new gene predictions. The manually curated set has adjacent exon/CDS regions, I'm not sure why. Is this what you are asking?

**Comment by Juke34** [comment]
If a proper third part tool has been used for the manual curation (e.g. Webapollo) you should not end up with such case. Indeed when modifying an exon, the underlying CDS if any is supposed to be modified accordingly. It is why I would like to know how the manual curation has been done.

**Comment by Juke34** [comment]
To resume adjacent CDs are merged as well as adjacent exons. In this case there is a synchronization problem between the exon-intron structure and the CDs-intron structure of a mRNA.
