### ISSUE TITLE
N50

### ISSUE THREAD

**Issue by herlianal12** [NBISweden/AGAT#87]
Hi Juke,

Your tool is awesome. I can get the most of the statistics that I want from a gtf file using agat_sp_statistics.pl. This is not an issue just a request. From your script, I got a number, the mean, total, the longest and the shortest for gene, rna (transcript) and exon. Is that possible to get N50 value from a gtf file?

Cheers,
Lina

**Comment by Juke34** [comment]
N50 calculation does not require gff/gtf file but only fasta. So I have a script for it but not within AGAT. See gaas_fasta_statistics.pl within GAAS

**Comment by herlianal12** [comment]
So I need to extract fasta file from the reference genome based on gff/gtf information first then. I would like to compare the transcripts that I generated using Cufflink with the published transcript using Trinity (de novo assembly) pipeline. However, cufflink only generates transcript.gtf file.

Thanks for your quick response.

**Comment by herlianal12** [comment]
Hi Juke,

Problem solved

Thanks
