### ISSUE TITLE
Problem after installation

### ISSUE THREAD

**Issue by lucasrocmoreira** [NBISweden/AGAT#88]
Hi, 

I don't have a lot of experience dealing with Perl modules. After installing AGAT on my HPC cluster, I keep getting the following error:

`Can't locate AGAT/Omniscient.pm in @INC (you may need to install the AGAT::Omniscient module)`

Do you know what might be causing this?

Thanks,
Lucas

**Comment by Juke34** [comment]
You cannot install it using conda?

For a manual installation you should follow the steps carefully. It sounds you forgot to run ‘make install’. Could you give more information about your installation, your location folder and the command ran?

**Comment by lucasrocmoreira** [comment]
I found an error in my conda environment, I fixed it and managed to install it successfully.

I'm closing the issue. Thanks.
