### ISSUE TITLE
Feature request: To extract the TSS information from GTF file

### ISSUE THREAD

**Issue by Rohit-Satyam** [NBISweden/AGAT#89]
Hi @Juke34 

This is more of a feature request if you could add this feature in AGAT in upcoming upgrades. For UCSC genomes, downloading TSS is pretty straight forward. For Ensembl genomes especially for plants genome for which only gtf file is present, how can one retrieve TSS information along with strand information?

**Comment by Juke34** [comment]
AGAT deals already with tss feature type if present in the gtf/gff file. So you should be able to extract this feature with agat_sp_extract_sequences.pl

**Comment by Rohit-Satyam** [comment]
Can you lead this by an example? I want TSS for Oryza Sativa Indica, whose gtf I obtained from ENSEMBL Plant.

**Comment by Juke34** [comment]
If the feature type (3rd column) is called tss in your file you do:
`agat_sp_extract_sequences.pl -g infile.gff -f infile.fasta -t tss`

**Comment by Juke34** [comment]
Did you succeed @Rohit-Satyam ?

**Comment by Rohit-Satyam** [comment]
Hi, @Juke34 I tried it but didn't get any output. Moreover, it's the coordinates that  I want rather than the fasta sequence itself along with the strand information. Since I have dealt mostly with bacterial viral and human gtf/gff3 file formats, I don't think any feature like "TSS" is explicitly mentioned in either of the feature files (Pardon my ignorance if I missed it somehow, would like to hear more on it if it exists). AGAT on running the following commands throws the following error:

`agat_sp_extract_sequences.pl -g gencode.v35.primary_assembly.annotation.gff3 -f GRCh38.primary_assembly.genome.fa -t tss -o temp.fasta`

```
Possible precedence issue with control flow operator at /home/genome1/miniconda3/envs/agat/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
We will extract the tss sequences.
Reading file gencode.v35.primary_assembly.annotation.gff3
********************************************************************************
*                              - Start parsing -                               *
********************************************************************************
-------------------------- parse options and metadata --------------------------
=> Accessing the feature level json files
        Using standard /home/genome1/miniconda3/envs/agat/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_level1.json file
        Using standard /home/genome1/miniconda3/envs/agat/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_level2.json file
        Using standard /home/genome1/miniconda3/envs/agat/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_level3.json file
        Using standard /home/genome1/miniconda3/envs/agat/lib/site_perl/5.26.2/auto/share/dist/AGAT/features_spread.json file
=> Attribute used to group features when no Parent/ID relationship exists:
        * locus_tag
        * gene_id
=> merge_loci option deactivated
=> Accessing Ontology
        No ontology accessible from the gff file header!
        We use the SOFA ontology distributed with AGAT:
                /home/genome1/miniconda3/envs/agat/lib/site_perl/5.26.2/auto/share/dist/AGAT/so.obo
        Read ontology /home/genome1/miniconda3/envs/agat/lib/site_perl/5.26.2/auto/share/dist/AGAT/so.obo:
                4 root terms, and 2472 total terms, and 1436 leaf terms
        Filtering ontology:
                We found 1757 terms that are sequence_feature or is_a child of it.
-------------------------------- parse features --------------------------------
=> GFF version parser used: 3
gff3 reader warning: primary_tag error @ stop_codon_redefined_as_selenocysteine still not taken in account! Please modify the json files to define the feature in one of the levels.
gff3 reader warning: primary_tag error @ stop_codon_redefined_as_selenocysteine still not taken in account! Please modify the json files to define the feature in one of the levels.
gff3 reader warning: primary_tag error @ stop_codon_redefined_as_selenocysteine still not taken in account! Please modify the json files to define the feature in one of the levels.
gff3 reader warning: primary_tag error @ stop_codon_redefined_as_selenocysteine still not taken in account! Please modify the json files to define the feature in one of the levels.
gff3 reader warning: primary_tag error @ stop_codon_redefined_as_selenocysteine still not taken in account! Please modify the json files to define the feature in one of the levels.
gff3 reader warning: primary_tag error @ stop_codon_redefined_as_selenocysteine still not taken in account! Please modify the json files to define the feature in one of the levels.
gff3 reader warning: primary_tag error @ stop_codon_redefined_as_selenocysteine still not taken in account! Please modify the json files to define the feature in one of the levels.
gff3 reader warning: primary_tag error @ stop_codon_redefined_as_selenocysteine still not taken in account! Please modify the json files to define the feature in one of the levels.
gff3 reader warning: primary_tag error @ stop_codon_redefined_as_selenocysteine still not taken in account! Please modify the json files to define the feature in one of the levels.
gff3 reader warning: primary_tag error @ stop_codon_redefined_as_selenocysteine still not taken in account! Please modify the json files to define the feature in one of the levels.
gff3 reader warning: primary_tag error  ************** Too much WARNING message we skip the next **************
```
I get the following warnings and then the program hangs there.

**Comment by Rohit-Satyam** [comment]
Also, I have one more request to make if that's possible. Your tool is currently a swiss knife for handling GTF/GFF files and it would be wonderful if it could also help separate intronless genes(IGs) from intron-containing genes (like it dumps two gtf file one of intronless genes with coordinates and other containing genes with introns)

**Comment by Juke34** [comment]
To see all feature types present in your file just do
```
awk '{print $3}' myFile.gff3 | sort -u
```
If there is no TSS/tss then AGAT cannot create them for you. AGAT does not predict such feature.

-------
To avoid that AGAT throw away the stop_codon_redefined_as_selenocysteine feature type you have to follow similar step than here: https://github.com/NBISweden/AGAT#agat-throws-features-out-because-child-features-are-not-provided modyfing the `features_level3.json` file addinf ` "stop_codon_redefined_as_selenocysteine ":"exon",` (be carreful to the coma terminating the line if it is not the last line)

------

If AGAT hangs, it might be a problematic file. What is the size of your file? Could you provide a sample of your file to have a quick look?

**Comment by Rohit-Satyam** [comment]
Hi @Juke34 

I followed the above instruction and realized that the gff3 file indeed didn't consist of TSS as a separate feature. The files were obtained from Gencode so there wasn't an issue with the files. I reran it on the server (it was perhaps a hardware issue of agat getting stuck) and yes because of the absence of explicit mention of TSS in the gff3 file it couldn't retrieved

Following features were found in the gff3 file
```
annotation
CDS
exon
five_prime_UTR
gene
start_codon
stop_codon
stop_codon_redefined_as_selenocysteine
three_prime_UTR
transcript
```

**Comment by Juke34** [comment]
Hi, 
I have think back about tss and acutally if you trust the annotaiton you have it is just about looking about the beginning  of the transcript. 
So you can extract the info playing with awk command e.g.  to create/get the tss (from transcript feature of your GFF)
```
# it takes the transcript line and do some modification to become tss feature
awk 'BEGIN{OFS="\t"}{if($3=="transcript"){$3="tss";$5=$4;print $0}}' test.gff > tss_file.gff 
```
If you wish to put back this information to the orignal GFF/GTF file you need to modify ID to avoid problems:
```
# needed to repair parent which is now wrong
sed 's/Parent=/gene_id=/' tss.gff | sed 's/ID/Parent/' > tss_fixed.gff
# append the original file with newly created tss feature
cat tss_fixed.gff >> test.gff
# needed to create clean IDs for tss that is missing at this point
agat_convert_sp_gxf2gxf.pl --gff test.gff -o test_with_tss_clean.gff 
```

Or you can extract the DNA sequence using agat_sp_extract_sequences.pl to extract e.g. the 3 (or any number you think valuable) first nucleotides of the transcript starting point:  
```
agat_sp_extract_sequences.pl --gff input.gff --fasta input.fasta -t transcript --eo --up "-3"
```
or  e.g. the 3 nucleotids before the transcript starting point:
```
agat_sp_extract_sequences.pl --gff input.gff --fasta input.fasta --eo --up 3
```


The same is possible for tts looking at end of transcript.
