### ISSUE TITLE
MSG: Each line of the fasta entry must be the same length except the last. Line above #3 '

### ISSUE THREAD

**Issue by sstwins21** [NBISweden/AGAT#90]
Hi,

Thank you so much for AGAT. I am having problem with MAKER functional annotation on gff3 files and found your tools.
I used agat_sp_manage_functional_annotation.pl --f renamed_CFSA.all.gff --db dos_protein.fasta -b output.blastp --output CFSA.AGAT.function.gff commnad line and got up to the statistics.

But it gave me an error message:

MSG: Each line of the fasta entry must be the same length except the last. Line above #3 '

..' is 2321 != 305 chars.
STACK: Error::throw
STACK: Bio::Root::Root::throw /scale_wlg_nobackup/filesets/nobackup/ga02470/prevent_from_delete/software/condaEnv/agat/lib/site_perl/5.26.2/Bio/Root/Root.pm:447
STACK: Bio::DB::Fasta::_calculate_offsets /scale_wlg_nobackup/filesets/nobackup/ga02470/prevent_from_delete/software/condaEnv/agat/lib/site_perl/5.26.2/Bio/DB/Fasta.pm:209
STACK: Bio::DB::IndexedBase::_index_files /scale_wlg_nobackup/filesets/nobackup/ga02470/prevent_from_delete/software/condaEnv/agat/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm:659
STACK: Bio::DB::IndexedBase::index_file /scale_wlg_nobackup/filesets/nobackup/ga02470/prevent_from_delete/software/condaEnv/agat/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm:487
STACK: Bio::DB::IndexedBase::new /scale_wlg_nobackup/filesets/nobackup/ga02470/prevent_from_delete/software/condaEnv/agat/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm:364
STACK: /scale_wlg_nobackup/filesets/nobackup/ga02470/software/AGAT/bin/agat_sp_manage_functional_annotation.pl:210
-----------------------------------------------------------

In the error message it claims that the fasta sequence lengths need to be same for all the entries and the differences in my fasta file seems to cause the error. dos_protein.fasta is the fasta file from uniprot database and I am not too sure why I would get this error...

Could you help me how I can solve this please?

Kind regards,
Shane

**Comment by Juke34** [comment]
This is a bioperl problem, I guess this can be fixed by reshaping your fasta file.
Could you try the bash command fold?

fold input.fa > output.fa

**Comment by sstwins21** [comment]
Hi Juke,

Thank you so much for your reply. I am running on the folded fasta file and get back to you when it finishes.

Kind regards,
Shane

**Comment by Juke34** [comment]
Did it work?
When using fold you must be sure that the headers are smaller than the fold value (80 by default) otherwise you will have the header put over several lines and then you fasta file is corrupted.

**Comment by sstwins21** [comment]
Hi Juke,

Yes, thank you so much!

It worked. Sorry for late reply. I was making sure, since this is my first time doing annotation,

Kind regards,
Shane

**Comment by sstwins21** [comment]
Hi Juke,

I am so sorry to reopen this, but I tried to solve this without any luck...

AGAT gave me this error message "ERROR B4M9I2 not found among the db! You probably didn't give to me the same fasta file than the one used for the blast. (l2=shane_00002788-ra)", so I thought I have missed fasta file. But I ran two times, making sure I used the right ones, but still gives me the same error message.

I checked blastp report and the missing query was clearly there:
SHANE_00002788-RA       B4M9I2  64.545  110     37      1       15      124     49      156     1.28e-42        139

I do not understand why AGAT cannot recognize the reports. Sorry I am very new at this and self teaching step by step...
I was thinking if I couldn't get this to work, should I insert the gene name myself?

For example, the given query in the gff file is written as:
filtered_hic.counts_GATC.18g4   maker   gene    12428   21415   .       +       .       ID=SHANE_00002788;Alias=maker-filtered_hic.counts_GATC.18g4-exonerate_protein2genome-gene-0.0

Then should I change the query by adding gene name in the attribute section:

filtered_hic.counts_GATC.18g4   maker   gene    12428   21415   .       +       .       ID=SHANE_00002788;Alias=maker-filtered_hic.counts_GATC.18g4-exonerate_protein2genome-gene-0.0;gene_name "B4M9I2";

Please let me know what you think.

Kind regards,
Shane

**Comment by Juke34** [comment]
The transcript SHANE_00002788-RA matchs against the protein  B4M9I2  according to the blast output file. But AGAT does not find B4M9I2  within the db fasta file you provieded with the --db file. So grep the db file to see if B4M9I2  is present, If it is, it is either a  problem with your index file that is compromised, remove it, AGAT will recreate it, or something in the header of this sequence has changed.
If the problem persist I invite you to share the files or at least a sample with the investigated case.

**Comment by sstwins21** [comment]
Hi Juke,

Thank you so much for your reply.
I have searched the db fasta file and it does contain that gene:

>tr|B4M9I2|B4M9I2_DROVI Thioredoxin domain-containing protein OS=Drosophila virilis OX=7244 GN=Dvir\GJ17911 PE=3 SV=1

Is the format of the name inappropriate? The fasta file is from Uniprot.
The command I used to run AGAT is:

agat_sp_manage_functional_annotation.pl --f CFSA.all.gff --db "./db/UP000008792.fasta" -b output.blastp --output CFSA.AGAT_folded.function.gff

If the name of the gene in the db fasta file seems appropriate, could I send you the .gff and Uniprot files to you?
If you let me know your email address, I can send them via google drive.
How would you like me to send them?


Kind regards,
Shane

**Comment by Juke34** [comment]
In the blast output file you have
```
SHANE_00002788-RA       B4M9I2  64.545  110     37      1       15      124     49      156     1.28e-42        139
```
where the protein id is `B4M9I2`

---------
In the blast db fasta file you have
```
tr|B4M9I2|B4M9I2_DROVI Thioredoxin domain-containing protein OS=Drosophila virilis OX=7244 GN=Dvir\GJ17911 PE=3 SV=1
```
where the protein id is `tr|B4M9I2|B4M9I2_DROVI`

---------
So as says by AGAT `B4M9I2` is different than `tr|B4M9I2|B4M9I2_DROVI`, so I don't know how you ended up with that. Are you sure you have use the same fasta file running the blast and then provided to AGAT by the --db parameter?
How many cases like that do you have? is is the only one?

**Comment by sstwins21** [comment]
Yes, this is the only one that I used for both blasp and AGAT.
This is the command I used for blastp:

blastp -query CFSA.all.maker.proteins.fasta -db UP000008792.fasta -evalue 1e-6 -max_hsps 1 -max_target_seqs 1 -outfmt 6 -out output.blastp

For the solution, do you think making the copy of db.fasta file and edit the scaffold names to:

B4M9I2 Thioredoxin domain-containing protein OS=Drosophila virilis OX=7244 GN=Dvir\GJ17911 PE=3 SV=1

And use this edited file as a db input to AGAT?

Kind regards,
Shane

**Comment by sstwins21** [comment]
Sorry for the cases, it seems that all the gene names in the db.fasta files are in that format and none of them were identified by AGAT...

**Comment by Juke34** [comment]
Interesting, what is your version of blast? It means that this version extract from the first field of the protein header only the protein ID instead to keep the whole field. Yes you can edit the protein file in the way it matches.
It can be problematic if once cleaned the ID is not uniq within the file.

**Comment by sstwins21** [comment]
The blast version I used to blastp is ' BLAST/2.10.0-GCC-9.2.0'.

What version of BLAST would you recommend to run with AGAT? I am running with edited fasta file but gave me the very first error message and trying to fix them again.

Kind regards,
Shane

**Comment by Juke34** [comment]
I tried blast 2.10.1+,
when I put header like that as input
```
>tr|Q14919|NC2A_HUMAN Dr1-associated corepressor OS=Homo sapiens OX=9606 GN=DRAP1 PE=1 SV=3
```
as expected I got output like that
```
transcript:Os01t0102400-01	tr|Q14919|NC2A_HUMAN	27.632	76	55	0	44	119	12	87	0.008	41.2
```

So I do not know how you end up with something like `Q14919`instead of `tr|Q14919|NC2A_HUMAN` in the 2nd column of the blast output.

You must check step by step what you have done.

**Comment by sstwins21** [comment]
Hi Juke,

So sorry for late reply. I checked every step I did and so far the only command it seems to affect the blast report is the blastp and I cannot see any problem with it...

I changed the blast report matching the scaffold names and it seems to work fine now.

Thank you so much for your help !

Kind regards,
Shane
