### ISSUE TITLE
Odd length statistics

### ISSUE THREAD

**Issue by ctxchris** [NBISweden/AGAT#91]
Hi,

I'm using agat_sp_statistics.pl v0.5.1 to calculate statistics from a gff3 file like that
`agat_sp_statistics.pl --gff genome.gff3 -o genome.gff3.stats -g genome.fasta -d`

Some length statistics looked odd, e.g. for 
> Longest exon                 
> Longest five_prime_utr       
> Longest three_prime_utr                 
> Longest five_prime_utr piece 
> Longest three_prime_utr piece

I get numbers >200k.
I then calculated the length of these features from the start and end position as given in columns 4 and 5 in the gff3 file. None of the above features had values nearly as high as those calculated by agat.

Best,
Chris

**Comment by Juke34** [comment]
Let's imagine a UTR of one gene in a genome, it will look like this
 UTR5 part1+part2 + part3 +part4 = utr5 of one gene
```
  UTR5 part1              UTR5 part2                      UTR5 part3              UTR5 part4
==================          =======                     =============             ==========
^ ...............^
Longest five_prime_utr piece 

^...........................................................................................^                                                                                                                                              
                                         Longest five_prime_utr                
````
I guess the problem you mention is about `Longest five_prime_utr` and  `Longest three_prime_utr` which can be very long if introns regions are big

You can run agat_sq_stat_basic.pl to compare (this script does not modify the file) but you will not have  `Longest five_prime_utr` and  `Longest three_prime_utr` information.

You can run agat_convert_sp_gxf2gxf.pl on your file and look at the log to see if AGAT does modify the file in a wrong way. (All modifications mentioned by this script are also made by scripts with the _sp_ flag like agat_sp_statistics.pl)

**Comment by Juke34** [comment]
@ctxchris did you figured out what is going on?
