### ISSUE TITLE
Gene names not updated with agat_sp_manage_functional_annotation.pl

### ISSUE THREAD

**Issue by 14zac2** [NBISweden/AGAT#92]
Hello!

I'm having a bit of trouble figuring out how to format the input files for agat_sp_manage_functional_annotation.pl. I am trying to update gene names with blast hits, and I think the issue is either in the format of my blast results or protein fasta file. My blast results are in output format 6, and I have tried the following output formats in terms of the query gene name:
`geneName\tblastGene\tetc...`
`primaryTranscriptName\tblastGene\tetc...`
`transcriptName\tblastGene\tetc...`
In other words, I have formatted my blast queries so that they either correspond to the gene name, primary transcript name, or every transcript name in the gff file (by every transcript, I mean multiple child transcript features from the same parent gene).
For my blast database, I have a protein file with the following header:
```
>geneName protein description goes here
SDFKLCNWJDFKDJV...
```
When I run agat_sp_manage_functional_annotation.pl, the Name attribute disappears from the gff file and report.txt says `0 gene names have been retrieved in the blast file. 0 gene names have been successfully inferred. Among them there are 0 names that are shared at least per two genes for a total of 0 genes.`. My thoughts are that perhaps there is something missing from my blast database/protein fasta file headers that agat uses to infer the gene name and protein product. I am sure I can easily change it, I'm just not sure what will work. Any help is much appreciated!

**Comment by Juke34** [comment]
You should let the the default outfmt 6 from blast.
Ususally we extract the proteins using `agat_sp_extract_sequences.pl -g infile.gff -f infile.fasta -p  -o infile_proteins.fa` then we run the blast on the infile_proteins.fa file.
So you could try on a subsample to see in the blast output what is in the qseqid column. I guess it is the mRNA identifier.

**Comment by 14zac2** [comment]
Thanks for your quick response! I did use the default outfmt6 from blast, and I also extracted the proteins using `agat_sp_extract_sequences.pl -p`, running blast on the resulting protein fasta (as I poorly described with `transcriptName\tblastGene\tetc...`). But `agat_sp_manage_functional_annotation.pl` only deleted the `Name=` attribute from the gff file. 

Do you think the issue might be in how I formatted the blast database? One thing I realized is that there are duplicated gene names in this file because alternate isoforms have the same gene name. For example, the blast protein database sometimes looks like this:
```
>geneSymbol1 protein description
AKJSSDKGJDSGD...
>geneSymbol1 protein isoform description
AKJSSDKGJDSGD...
>geneSymbol2 protein description
SKDFJSLJDKJFS...
```
This was so that I could easily see which gene symbols were matching to my predicted proteins.

**Comment by Juke34** [comment]
Ok then yes it is due to the formatting of the header in the fasta file use as DB. It should follow the standard of the Uniprot DB (with keywords in the header like GN for gene name, PE for protein existence, etc...)

**Comment by 14zac2** [comment]
Aaah I see! So as long as I added `GN=geneName PE=5` etc. to the end of the header I should be okay? Which fields are required? I see UniProt includes GN, PE, OX, SV,  and OS. Thanks again for helping clear this up for me!

**Comment by Juke34** [comment]
Only GN is mandatory (PE is used only if you add the PE filter). If no function it becomes "hypothetical protein"
Here an example of header:
```
>sp|P37256|PSBT_CHLRE Photosystem II reaction center protein T OS=Chlamydomonas reinhardtii OX=3055 GN=psbT PE=1 SV=1
                      ^......................................^                                      ^....^
                                   1                                                                  2
```
1= Function (Must be between the first space and before the first = characher with 2 letter before it. What is in the second parenthesis in this regex: /(^[^\s]+)\s(.+?(?= \w{2}=))(.+)/)            )
2 = Gene name

**Comment by 14zac2** [comment]
Great, thank you so much! I made the changes and the gene names are indeed updating now. Really appreciate it!
